# Carga de imagenes al datastore y mosaic dataset

Flujo operativo posterior a la preparacion del notebook `008`. Usa `04_ready_for_datastore.csv` para copiar archivos al datastore y `06_attribute_updates.csv` para actualizar atributos del mosaic dataset.

In [1]:
from datetime import datetime
from pathlib import Path
import importlib

import pandas as pd

import core.mosaic_loader as mosaic_loader
mosaic_loader = importlib.reload(mosaic_loader)
from core.mosaic_loader import *

# PARAMETROS
RUN_PREPARACION = "20260615_155625"
OUTPUT_PREPARACION_DIR = Path.cwd() / "outputs" / "preparacion_carga_mosaico" / RUN_PREPARACION

READY_FOR_DATASTORE_CSV = OUTPUT_PREPARACION_DIR / "04_ready_for_datastore.csv"
ATTRIBUTE_UPDATES_CSV = OUTPUT_PREPARACION_DIR / "06_attribute_updates.csv"

PATH_MOSAIC_DATASET = r"\\amssclgis08.ams.gmams.cl\CL_MLP_PAO\01_Proyectos_ArcGIS\APRX\CL MLP PAO Aereo Image Server_v2\SQLServer-amssclgis06_ArcGIS-Aereo.sde\OWD.CL_MLP_PAO_IF_Ortho_Geosupport"

# Seguridad operacional: validar primero con DRY_RUN=True. Cambiar a False para ejecutar copia/carga/update.
DRY_RUN = False
OVERWRITE_COPY = False
SKIP_EXISTING_MOSAIC_NAME = True

# Valores fijos definidos para esta carga.
MAXPS_VALUE = 10000
LOWPS_VALUE = 0.15

run_timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
OUTPUT_DIR = Path.cwd() / "outputs" / "carga_mosaico" / run_timestamp
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

print("Preparacion:", OUTPUT_PREPARACION_DIR)
print("CSV carga:", READY_FOR_DATASTORE_CSV)
print("CSV atributos:", ATTRIBUTE_UPDATES_CSV)
print("Mosaic dataset:", PATH_MOSAIC_DATASET)
print("Salida:", OUTPUT_DIR)
print("DRY_RUN:", DRY_RUN)

Preparacion: c:\Users\esrlrivero_adm\Documents\Geosupport\amsa-pao-geosupport\outputs\preparacion_carga_mosaico\20260615_155625
CSV carga: c:\Users\esrlrivero_adm\Documents\Geosupport\amsa-pao-geosupport\outputs\preparacion_carga_mosaico\20260615_155625\04_ready_for_datastore.csv
CSV atributos: c:\Users\esrlrivero_adm\Documents\Geosupport\amsa-pao-geosupport\outputs\preparacion_carga_mosaico\20260615_155625\06_attribute_updates.csv
Mosaic dataset: \\amssclgis08.ams.gmams.cl\CL_MLP_PAO\01_Proyectos_ArcGIS\APRX\CL MLP PAO Aereo Image Server_v2\SQLServer-amssclgis06_ArcGIS-Aereo.sde\OWD.CL_MLP_PAO_IF_Ortho_Geosupport
Salida: c:\Users\esrlrivero_adm\Documents\Geosupport\amsa-pao-geosupport\outputs\carga_mosaico\20260615_162625
DRY_RUN: False

## 1. Cargar manifiestos

Se valida que cada imagen lista tenga atributos asociados antes de ejecutar cualquier operacion.

In [2]:
load_df = load_ready_and_attributes(READY_FOR_DATASTORE_CSV, ATTRIBUTE_UPDATES_CSV)

required_columns = ["path", "destination_path", "Name", "Sector", "Fecha_Adqui", "URL", "Proyecto", "Sensor", "Fecha_Publ"]
missing_columns = [column for column in required_columns if column not in load_df.columns]
if missing_columns:
    raise ValueError(f"Faltan columnas requeridas: {missing_columns}")

validation_summary = pd.DataFrame(
    [
        {"metric": "records_to_process", "value": len(load_df)},
        {"metric": "missing_source_path", "value": int((~load_df["path"].map(lambda value: Path(value).exists())).sum())},
        {"metric": "missing_destination_path", "value": int(load_df["destination_path"].isna().sum())},
        {"metric": "unique_destination_paths", "value": int(load_df["destination_path"].nunique())},
        {"metric": "unique_names", "value": int(load_df["Name"].nunique())},
    ]
)

display(validation_summary)
display(load_df[["file_name", "Name", "destination_path", "Sector", "Fecha_Adqui", "Proyecto", "Sensor", "Fecha_Publ"]].head(20))

                     metric  value
0        records_to_process     32
1       missing_source_path      0
2  missing_destination_path      0
3  unique_destination_paths     32
4              unique_names     32

,file_name,Name,destination_path,Sector,Fecha_Adqui,Proyecto,Sensor,Fecha_Publ
0,GEOSP-TRN-002511_GS_Ortofoto Estación Cabecera...,CL_MLP_PAO_IF_Ortho_26_05_01_Estacion_Cabecera,\\amssclgis10.ams.gmams.cl\CL_MLP_PAO\Chacay_D...,Estacion_Cabecera,2026-05-01,PAO,DJI Mavic Enterprise,2026-06-15
1,GEOSP-TRN-002545_GS_ORTOFOTO_EB3_06-05-26.tif,CL_MLP_PAO_IF_Ortho_26_05_06_Subestacion-El-Ma...,\\amssclgis10.ams.gmams.cl\CL_MLP_PAO\El_Mauro...,Subestacion-El-Mauro,2026-05-06,PAO,DJI Mavic Enterprise,2026-06-15
2,GEOSP-TRN-002546_GS_ORTOFOTO_SSEE_06-05-26.tif,CL_MLP_PAO_IF_Ortho_26_05_06_Subestacion-El-Ma...,\\amssclgis10.ams.gmams.cl\CL_MLP_PAO\El_Mauro...,Subestacion-El-Mauro,2026-05-06,PAO,DJI Mavic Enterprise,2026-06-15
3,GEOSP-TRN-002555_GS_Ortofoto_Tramo 2 Línea 33 ...,CL_MLP_PAO_IF_Ortho_26_05_06_TORRE_E85_A_E_125,\\amssclgis10.ams.gmams.cl\CL_MLP_PAO\Chacay_E...,TORRE_E85_A_E_125,2026-05-06,PAO,DJI Mavic Enterprise,2026-06-15
4,GEOSP-TRN-002591_GS_Ortofoto ED1_10-05-2026.tif,CL_MLP_PAO_IF_Ortho_26_05_10_ED1,\\amssclgis10.ams.gmams.cl\CL_MLP_PAO\Chacay_E...,ED1,2026-05-10,PAO,DJI Mavic Enterprise,2026-06-15
5,GEOSP-TRN-002592_GS_Ortofoto_Helipuerto Mauro ...,CL_MLP_PAO_IF_Ortho_26_05_10_Helipuerto,\\amssclgis10.ams.gmams.cl\CL_MLP_PAO\El_Mauro...,Helipuerto,2026-05-10,PAO,DJI Mavic Enterprise,2026-06-15
6,GEOSP-TRN-002593_GS_ORTOFOTO_PATIO 19B_10-05-2...,CL_MLP_PAO_IF_Ortho_26_05_10_Patio-19B-y-Armado,\\amssclgis10.ams.gmams.cl\CL_MLP_PAO\Chacay_E...,Patio-19B-y-Armado,2026-05-10,PAO,DJI Mavic Enterprise,2026-06-15
7,GEOSP-TRN-002603_ORTOFOTO_CORTADA_EM2_100526.tif,CL_MLP_PAO_IF_Ortho_26_05_10_DME9-PA12-IIFF8,\\amssclgis10.ams.gmams.cl\CL_MLP_PAO\Chacay_E...,DME9-PA12-IIFF8,2026-05-10,PAO,DJI Mavic Enterprise,2026-06-15
8,GEOSP-TRN-002604_GS_Ortofoto_Tramo 2 Línea 33 ...,CL_MLP_PAO_IF_Ortho_26_05_07_TORRES_E48_A_E84_PV4,\\amssclgis10.ams.gmams.cl\CL_MLP_PAO\Chacay_E...,TORRES_E48_A_E84_PV4,2026-05-07,PAO,DJI Mavic Enterprise,2026-06-15
9,GEOSP-TRN-002606_GS_Ortofoto_Tramo 1 Línea 33 ...,CL_MLP_PAO_IF_Ortho_26_05_10_MonteAranda-NSTC-...,\\amssclgis10.ams.gmams.cl\CL_MLP_PAO\Chacay_E...,MonteAranda-NSTC-Km-84p2-a-82p3,2026-05-10,PAO,DJI Mavic Enterprise,2026-06-15
10,GEOSP-TRN-002615_GS_ORTOFOTO_ESTACION DE MONIT...,CL_MLP_PAO_IF_Ortho_26_05_13_DME9-PA12-IIFF8,\\amssclgis10.ams.gmams.cl\CL_MLP_PAO\El_Mauro...,DME9-PA12-IIFF8,2026-05-13,PAO,DJI Mavic Enterprise,2026-06-15
11,GEOSP-TRN-002616_GS_ORTOFOTO_ACCESO POZOS PRP_...,CL_MLP_PAO_IF_Ortho_26_05_13_Subestacion-El-Ma...,\\amssclgis10.ams.gmams.cl\CL_MLP_PAO\El_Mauro...,Subestacion-El-Mauro_A_E35,2026-05-13,PAO,DJI Mavic Enterprise,2026-06-15
12,GEOSP-TRN-002617_GS_ORTOFOTO_SUBESTACION_EL MA...,CL_MLP_PAO_IF_Ortho_26_05_13_Subestacion-El-Ma...,\\amssclgis10.ams.gmams.cl\CL_MLP_PAO\Chacay_E...,Subestacion-El-Mauro,2026-05-13,PAO,DJI Mavic Enterprise,2026-06-15
13,GEOSP-TRN-002618_GS_ORTOFOTO_EM2-2_13-05-2026.tif,CL_MLP_PAO_IF_Ortho_26_05_13_EM2_S2,\\amssclgis10.ams.gmams.cl\CL_MLP_PAO\Chacay_E...,EM2_S2,2026-05-13,PAO,DJI Mavic Enterprise,2026-06-15
14,GEOSP-TRN-002619_GS_ORTOFOTO_EBD_130526.tif,CL_MLP_PAO_IF_Ortho_26_05_13_EBD-1,\\amssclgis10.ams.gmams.cl\CL_MLP_PAO\El_Mauro...,EBD,2026-05-13,PAO,DJI Mavic Enterprise,2026-06-15
15,GEOSP-TRN-002620_GS_ORTOFOTO_ED2_13-05-2026.tif,CL_MLP_PAO_IF_Ortho_26_05_13_ED2,\\amssclgis10.ams.gmams.cl\CL_MLP_PAO\Chacay_E...,ED2,2026-05-13,PAO,DJI Mavic Enterprise,2026-06-15
16,GEOSP-TRN-002621_GS_ORTOFOTO_ESTACION DE BOMBE...,CL_MLP_PAO_IF_Ortho_26_05_13_Subestacion-El-Ma...,\\amssclgis10.ams.gmams.cl\CL_MLP_PAO\El_Mauro...,Subestacion-El-Mauro,2026-05-13,PAO,DJI Mavic Enterprise,2026-06-15
17,GEOSP-TRN-002622_GS_ORTOFOTO_POZOS PRP_130526.tif,CL_MLP_PAO_IF_Ortho_26_05_13_EBD-2,\\amssclgis10.ams.gmams.cl\CL_MLP_PAO\El_Mauro...,EBD,2026-05-13,PAO,DJI Mavic Enterprise,2026-06-15
18,GEOSP-TRN-002623_GS_ORTOFOTO_ESTACIÓN INTERMED...,CL_MLP_PAO_IF_Ortho_26_05_13_Estacion_Intermedia,\\amssclgis10.ams.gmams.cl\CL_MLP_PAO\Chacay_E...,Estacion_Intermedia,2026-05-13,PAO,DJI Mavic Enterprise,2026-06-15
19,GEOSP-TRN-002627_GS_ORTOFOTO_EM3_14-05-2026.tif,CL_MLP_PAO_IF_Ortho_26_05_14_EM3,\\amssclgis10.ams.gmams.cl\CL_MLP_PAO\Chacay_E...,EM3,2026-05-14,PAO,DJI Mavic Enterprise,2026-06-15

## 2. Ejecutar copia, carga al mosaico, footprints y atributos

Con `DRY_RUN=True` no escribe archivos ni modifica el mosaic dataset. Con `DRY_RUN=False` ejecuta el flujo completo por imagen.

In [3]:
results = []

for index, row in load_df.iterrows():
    print(f"[{index + 1}/{len(load_df)}] {row['Name']}")
    result = process_mosaic_load_row(
        row,
        PATH_MOSAIC_DATASET,
        overwrite_copy=OVERWRITE_COPY,
        skip_existing_mosaic_name=SKIP_EXISTING_MOSAIC_NAME,
        maxps_value=MAXPS_VALUE,
        lowps_value=LOWPS_VALUE,
        dry_run=DRY_RUN,
    )
    results.append(result)

results_df = pd.DataFrame(results)
display(results_df)
display(results_df["overall_status"].value_counts(dropna=False).reset_index(name="count").rename(columns={"index": "overall_status"}))

[1/32] CL_MLP_PAO_IF_Ortho_26_05_01_Estacion_Cabecera
[2/32] CL_MLP_PAO_IF_Ortho_26_05_06_Subestacion-El-Mauro-1
[3/32] CL_MLP_PAO_IF_Ortho_26_05_06_Subestacion-El-Mauro-2
[4/32] CL_MLP_PAO_IF_Ortho_26_05_06_TORRE_E85_A_E_125
[5/32] CL_MLP_PAO_IF_Ortho_26_05_10_ED1
[6/32] CL_MLP_PAO_IF_Ortho_26_05_10_Helipuerto
[7/32] CL_MLP_PAO_IF_Ortho_26_05_10_Patio-19B-y-Armado
[8/32] CL_MLP_PAO_IF_Ortho_26_05_10_DME9-PA12-IIFF8
[9/32] CL_MLP_PAO_IF_Ortho_26_05_07_TORRES_E48_A_E84_PV4
[10/32] CL_MLP_PAO_IF_Ortho_26_05_10_MonteAranda-NSTC-Km-84p2-a-82p3
[11/32] CL_MLP_PAO_IF_Ortho_26_05_13_DME9-PA12-IIFF8
[12/32] CL_MLP_PAO_IF_Ortho_26_05_13_Subestacion-El-Mauro_A_E35
[13/32] CL_MLP_PAO_IF_Ortho_26_05_13_Subestacion-El-Mauro-1
[14/32] CL_MLP_PAO_IF_Ortho_26_05_13_EM2_S2
[15/32] CL_MLP_PAO_IF_Ortho_26_05_13_EBD-1
[16/32] CL_MLP_PAO_IF_Ortho_26_05_13_ED2
[17/32] CL_MLP_PAO_IF_Ortho_26_05_13_Subestacion-El-Mauro-2
[18/32] CL_MLP_PAO_IF_Ortho_26_05_13_EBD-2
[19/32] CL_MLP_PAO_IF_Ortho_26_05_13_Estacion_Intermedia
[20/32] CL_MLP_PAO_IF_Ortho_26_05_14_EM3
[21/32] CL_MLP_PAO_IF_Ortho_26_05_14_Camino_Alternativo_Salamanca
[22/32] CL_MLP_PAO_IF_Ortho_26_05_14_TORRES_E31_A_E48_PV4-1
[23/32] CL_MLP_PAO_IF_Ortho_26_05_14_Subestacion-El-Mauro_A_E35
[24/32] CL_MLP_PAO_IF_Ortho_26_05_15_Helipuerto-1
[25/32] CL_MLP_PAO_IF_Ortho_26_05_15_Helipuerto-2
[26/32] CL_MLP_PAO_IF_Ortho_26_05_15_EV1
[27/32] CL_MLP_PAO_IF_Ortho_26_05_15_Estacion_Cabecera
[28/32] CL_MLP_PAO_IF_Ortho_26_05_16_TORRES_E48_A_E84_PV4
[29/32] CL_MLP_PAO_IF_Ortho_26_05_17_EV2
[30/32] CL_MLP_PAO_IF_Ortho_26_05_17_EDT
[31/32] CL_MLP_PAO_IF_Ortho_26_05_14_TORRES_E31_A_E48_PV4-2
[32/32] CL_MLP_PAO_IF_Ortho_26_05_15_EM1

,file_name,Name,destination_path,overall_status,source_path,copy_status,copy_error,mosaic_add_status,mosaic_add_error,footprint_status,footprint_error,attribute_status,attribute_rows_updated,attribute_missing_fields,attribute_error
0,GEOSP-TRN-002511_GS_Ortofoto Estación Cabecera...,CL_MLP_PAO_IF_Ortho_26_05_01_Estacion_Cabecera,\\amssclgis10.ams.gmams.cl\CL_MLP_PAO\Chacay_D...,ok,\\amssclgis10.ams.gmams.cl\CL_MLP_PAO\Vuelos_D...,copied,None,added,None,built,None,updated,1,Fecha_Adqui|Fecha_Publ,None
1,GEOSP-TRN-002545_GS_ORTOFOTO_EB3_06-05-26.tif,CL_MLP_PAO_IF_Ortho_26_05_06_Subestacion-El-Ma...,\\amssclgis10.ams.gmams.cl\CL_MLP_PAO\El_Mauro...,ok,\\amssclgis10.ams.gmams.cl\CL_MLP_PAO\Vuelos_D...,copied,None,added,None,built,None,updated,1,Fecha_Adqui|Fecha_Publ,None
2,GEOSP-TRN-002546_GS_ORTOFOTO_SSEE_06-05-26.tif,CL_MLP_PAO_IF_Ortho_26_05_06_Subestacion-El-Ma...,\\amssclgis10.ams.gmams.cl\CL_MLP_PAO\El_Mauro...,ok,\\amssclgis10.ams.gmams.cl\CL_MLP_PAO\Vuelos_D...,copied,None,added,None,built,None,updated,1,Fecha_Adqui|Fecha_Publ,None
3,GEOSP-TRN-002555_GS_Ortofoto_Tramo 2 Línea 33 ...,CL_MLP_PAO_IF_Ortho_26_05_06_TORRE_E85_A_E_125,\\amssclgis10.ams.gmams.cl\CL_MLP_PAO\Chacay_E...,ok,\\amssclgis10.ams.gmams.cl\CL_MLP_PAO\Vuelos_D...,copied,None,added,None,built,None,updated,1,Fecha_Adqui|Fecha_Publ,None
4,GEOSP-TRN-002591_GS_Ortofoto ED1_10-05-2026.tif,CL_MLP_PAO_IF_Ortho_26_05_10_ED1,\\amssclgis10.ams.gmams.cl\CL_MLP_PAO\Chacay_E...,ok,\\amssclgis10.ams.gmams.cl\CL_MLP_PAO\Vuelos_D...,copied,None,added,None,built,None,updated,1,Fecha_Adqui|Fecha_Publ,None
5,GEOSP-TRN-002592_GS_Ortofoto_Helipuerto Mauro ...,CL_MLP_PAO_IF_Ortho_26_05_10_Helipuerto,\\amssclgis10.ams.gmams.cl\CL_MLP_PAO\El_Mauro...,ok,\\amssclgis10.ams.gmams.cl\CL_MLP_PAO\Vuelos_D...,copied,None,added,None,built,None,updated,1,Fecha_Adqui|Fecha_Publ,None
6,GEOSP-TRN-002593_GS_ORTOFOTO_PATIO 19B_10-05-2...,CL_MLP_PAO_IF_Ortho_26_05_10_Patio-19B-y-Armado,\\amssclgis10.ams.gmams.cl\CL_MLP_PAO\Chacay_E...,ok,\\amssclgis10.ams.gmams.cl\CL_MLP_PAO\Vuelos_D...,copied,None,added,None,built,None,updated,1,Fecha_Adqui|Fecha_Publ,None
7,GEOSP-TRN-002603_ORTOFOTO_CORTADA_EM2_100526.tif,CL_MLP_PAO_IF_Ortho_26_05_10_DME9-PA12-IIFF8,\\amssclgis10.ams.gmams.cl\CL_MLP_PAO\Chacay_E...,ok,\\amssclgis10.ams.gmams.cl\CL_MLP_PAO\Vuelos_D...,copied,None,added,None,built,None,updated,1,Fecha_Adqui|Fecha_Publ,None
8,GEOSP-TRN-002604_GS_Ortofoto_Tramo 2 Línea 33 ...,CL_MLP_PAO_IF_Ortho_26_05_07_TORRES_E48_A_E84_PV4,\\amssclgis10.ams.gmams.cl\CL_MLP_PAO\Chacay_E...,ok,\\amssclgis10.ams.gmams.cl\CL_MLP_PAO\Vuelos_D...,copied,None,added,None,built,None,updated,1,Fecha_Adqui|Fecha_Publ,None
9,GEOSP-TRN-002606_GS_Ortofoto_Tramo 1 Línea 33 ...,CL_MLP_PAO_IF_Ortho_26_05_10_MonteAranda-NSTC-...,\\amssclgis10.ams.gmams.cl\CL_MLP_PAO\Chacay_E...,ok,\\amssclgis10.ams.gmams.cl\CL_MLP_PAO\Vuelos_D...,copied,None,added,None,built,None,updated,1,Fecha_Adqui|Fecha_Publ,None
10,GEOSP-TRN-002615_GS_ORTOFOTO_ESTACION DE MONIT...,CL_MLP_PAO_IF_Ortho_26_05_13_DME9-PA12-IIFF8,\\amssclgis10.ams.gmams.cl\CL_MLP_PAO\El_Mauro...,ok,\\amssclgis10.ams.gmams.cl\CL_MLP_PAO\Vuelos_D...,copied,None,added,None,built,None,updated,1,Fecha_Adqui|Fecha_Publ,None
11,GEOSP-TRN-002616_GS_ORTOFOTO_ACCESO POZOS PRP_...,CL_MLP_PAO_IF_Ortho_26_05_13_Subestacion-El-Ma...,\\amssclgis10.ams.gmams.cl\CL_MLP_PAO\El_Mauro...,ok,\\amssclgis10.ams.gmams.cl\CL_MLP_PAO\Vuelos_D...,copied,None,added,None,built,None,updated,1,Fecha_Adqui|Fecha_Publ,None
12,GEOSP-TRN-002617_GS_ORTOFOTO_SUBESTACION_EL MA...,CL_MLP_PAO_IF_Ortho_26_05_13_Subestacion-El-Ma...,\\amssclgis10.ams.gmams.cl\CL_MLP_PAO\Chacay_E...,ok,\\amssclgis10.ams.gmams.cl\CL_MLP_PAO\Vuelos_D...,copied,None,added,None,built,None,updated,1,Fecha_Adqui|Fecha_Publ,None
13,GEOSP-TRN-002618_GS_ORTOFOTO_EM2-2_13-05-2026.tif,CL_MLP_PAO_IF_Ortho_26_05_13_EM2_S2,\\amssclgis10.ams.gmams.cl\CL_MLP_PAO\Chacay_E...,ok,\\amssclgis10.ams.gmams.cl\CL_MLP_PAO\Vuelos_D...,copied,None,added,None,built,None,updated,1,Fecha_Adqui|Fecha_Publ,None
14,GEOSP-TRN-002619_GS_ORTOFOTO_EBD_130526.tif,CL_MLP_PAO_IF_Ortho_26_05_13_EBD-1,\\amssclgis10.ams.gmams.cl\CL_MLP_PAO\El_Mauro...,ok,\\amssclgis10.ams.gmams.cl\CL_MLP_PAO\Vuelos_D...,copied,None,added,None,built,None,updated,1,Fecha_Adqui|Fecha_Publ,None
15,GEOSP-TRN-002620_GS_ORTOFOTO_ED2_13-05-2026.tif,CL_MLP_PAO_IF_Ortho_26_05_13_ED2,\\amssclgis10.ams.gmams.cl\CL_MLP_PAO\Chacay_E...,ok,\\amssclgis10.ams.gmams.cl\CL_MLP_PAO\Vuelos_D...,copied,None,added,None,built,None,updated,1,Fecha_Adqui|Fecha_Publ,None
16,GEOSP-TRN-002621_GS_ORTOFOTO_ESTACION DE BOMBE...,CL_MLP_PAO_IF_Ortho_26_05_13_Subestacion-El-Ma...,\\amssclgis10.ams.gmams.cl\CL_MLP_PAO\El_Mauro...,ok,\\amssclgis10.ams.gmams.cl\CL_MLP_PAO\Vuelos_D...,copied,None,added,None,built,None,updated,1,Fecha_Adqui|Fecha_Publ,None
17,GEOSP-TRN-002622_GS_ORTOFOTO_POZOS PRP_130526.tif,CL_MLP_PAO_IF_Ortho_26_05_13_EBD-2,\\amssclgis10.ams.gmams.cl\CL_MLP_PAO\El_Mauro...,ok,\\amssclgis10.ams.gmams.cl\CL_MLP_PAO\Vuelos_D...,copied,None,added,None,built,None,updated,1,Fecha_Adqui|Fecha_Publ,None
18,GEOSP-TRN-002623_GS_ORTOFOTO_ESTACIÓN INTERMED...,CL_MLP_PAO_IF_Ortho_26_05_13_Estacion_Intermedia,\\amssclgis10.ams.gmams.cl\CL_MLP_PAO\Chacay_E...,ok,\\amssclgis10.ams.gmams.cl\CL_MLP_PAO\Vuelos_D...,copied,None,added,None,built,None,updated,1,Fecha_Adqui|Fecha_Publ,None
19,GEOSP-TRN-002627_GS_ORTOFOTO_EM3_14-05-2026.tif,CL_MLP_PAO_IF_Ortho_26_05_14_EM3,\\amssclgis10.ams.gmams.cl\CL_MLP_PAO\Chacay_E...,ok,\\amssclgis10.ams.gmams.cl\CL_MLP_PAO\Vuelos_D...,copied,None,added,None,built,None,updated,1,Fecha_Adqui|Fecha_Publ,None
20,GEOSP-TRN-002629_GS_ORTOFOTO_Camino alternativ...,CL_MLP_PAO_IF_Ortho_26_05_14_Camino_Alternativ...,\\amssclgis10.ams.gmams.cl\CL_MLP_PAO\El_Mauro...,ok,\\amssclgis10.ams.gmams.cl\CL_MLP_PAO\Vuelos_D...,copied,None,added,None,built,None,updated,1,Fecha_Adqui|Fecha_Publ,None
21,GEOSP-TRN-002630_GD_ORTOFOTO_Tramo 2 linea 22 ...,CL_MLP_PAO_IF_Ortho_26_05_14_TORRES_E31_A_E48_...,\\amssclgis10.ams.gmams.cl\CL_MLP_PAO\Chacay_E...,ok,\\amssclgis10.ams.gmams.cl\CL_MLP_PAO\Vuelos_D...,copied,None,added,None,built,None,updated,1,Fecha_Adqui|Fecha_Publ,None
22,GEOSP-TRN-002631_GS_ORTOFOTO_EM4_14-05-2026.tif,CL_MLP_PAO_IF_Ortho_26_05_14_Subestacion-El-Ma...,\\amssclgis10.ams.gmams.cl\CL_MLP_PAO\El_Mauro...,ok,\\amssclgis10.ams.gmams.cl\CL_MLP_PAO\Vuelos_D...,copied,None,added,None,built,None,updated,1,Fecha_Adqui|Fecha_Publ,None
23,GEOSP-TRN-002635_GS_ORTOFOTO_HELIPUERTO MAURO_...,CL_MLP_PAO_IF_Ortho_26_05_15_Helipuerto-1,\\amssclgis10.ams.gmams.cl\CL_MLP_PAO\El_Mauro...,ok,\\amssclgis10.ams.gmams.cl\CL_MLP_PAO\Vuelos_D...,copied,None,added,None,built,None,updated,1,Fecha_Adqui|Fecha_Publ,None
24,GEOSP-TRN-002636_GS_ORTOFOTO_HELIPUERTO MAURO_...,CL_MLP_PAO_IF_Ortho_26_05_15_Helipuerto-2,\\amssclgis10.ams.gmams.cl\CL_MLP_PAO\El_Mauro...,ok,\\amssclgis10.ams.gmams.cl\CL_MLP_PAO\Vuelos_D...,copied,None,added,None,built,None,updated,1,Fecha_Adqui|Fecha_Publ,None
25,GEOSP-TRN-002642_GS_ORTOFOTO_EV1_15-05-2026.tif,CL_MLP_PAO_IF_Ortho_26_05_15_EV1,\\amssclgis10.ams.gmams.cl\CL_MLP_PAO\Chacay_E...,ok,\\amssclgis10.ams.gmams.cl\CL_MLP_PAO\Vuelos_D...,copied,None,added,None,built,None,updated,1,Fecha_Adqui|Fecha_Publ,None
26,GEOSP-TRN-002643_GS_Ortofoto_Estacion Cabecera...,CL_MLP_PAO_IF_Ortho_26_05_15_Estacion_Cabecera,\\amssclgis10.ams.gmams.cl\CL_MLP_PAO\Chacay_D...,ok,\\amssclgis10.ams.gmams.cl\CL_MLP_PAO\Vuelos_D...,copied,None,added,None,built,None,updated,1,Fecha_Adqui|Fecha_Publ,None
27,GEOSP-TRN-002647_GS_ORTOFOTO_TORRES E48 A E84_...,CL_MLP_PAO_IF_Ortho_26_05_16_TORRES_E48_A_E84_PV4,\\amssclgis10.ams.gmams.cl\CL_MLP_PAO\Chacay_E...,ok,\\amssclgis10.ams.gmams.cl\CL_MLP_PAO\Vuelos_D...,copied,None,added,None,built,None,updated,1,Fecha_Adqui|Fecha_Publ,None
28,GEOSP-TRN-002652_GS_ORTOFOTO_EV2_170526.tif,CL_MLP_PAO_IF_Ortho_26_05_17_EV2,\\amssclgis10.ams.gmams.cl\CL_MLP_PAO\El_Mauro...,ok,\\amssclgis10.ams.gmams.cl\CL_MLP_PAO\Vuelos_D...,copied,None,added,None,built,None,updated,1,Fecha_Adqui|Fecha_Publ,None
29,GEOSP-TRN-002655_GS_ORTOFOTO_EDT_17-05-2026.tif,CL_MLP_PAO_IF_Ortho_26_05_17_EDT,\\amssclgis10.ams.gmams.cl\CL_MLP_PAO\Puerto_P...,ok,\\amssclgis10.ams.gmams.cl\CL_MLP_PAO\Vuelos_D...,copied,None,added,None,built,None,updated,1,Fecha_Adqui|Fecha_Publ,None
30,GEOSP-TRN-002656_GD_ORTOFOTO_Tramo 2 linea 22 ...,CL_MLP_PAO_IF_Ortho_26_05_14_TORRES_E31_A_E48_...,\\amssclgis10.ams.gmams.cl\CL_MLP_PAO\Chacay_E...,ok,\\amssclgis10.ams.gmams.cl\CL_MLP_PAO\Vuelos_D...,copied,None,added,None,built,None,updated,1,Fecha_Adqui|Fecha_Publ,None
31,GEOSP-TRN-002660_GS_ORTOFOTO_EM1_150526.tif,CL_MLP_PAO_IF_Ortho_26_05_15_EM1,\\amssclgis10.ams.gmams.cl\CL_MLP_PAO\Chacay_D...,ok,\\amssclgis10.ams.gmams.cl\CL_MLP_PAO\Vuelos_D...,copied,None,added,None,built,None,updated,1,Fecha_Adqui|Fecha_Publ,None

  overall_status  count
0             ok     32

## 3. Exportar resultados de ejecucion

In [4]:
summary_rows = [
    {"metric": "run_timestamp", "value": run_timestamp},
    {"metric": "preparation_run", "value": RUN_PREPARACION},
    {"metric": "dry_run", "value": DRY_RUN},
    {"metric": "mosaic_dataset", "value": PATH_MOSAIC_DATASET},
    {"metric": "records_to_process", "value": len(load_df)},
    {"metric": "maxps_value", "value": MAXPS_VALUE},
    {"metric": "lowps_value", "value": LOWPS_VALUE},
]

for column in ["copy_status", "mosaic_add_status", "footprint_status", "attribute_status", "overall_status"]:
    if column in results_df.columns:
        for status, count in results_df[column].value_counts(dropna=False).items():
            summary_rows.append({"metric": f"{column}_{status}", "value": int(count)})

summary_df = pd.DataFrame(summary_rows)

summary_csv = OUTPUT_DIR / "00_summary.csv"
results_csv = OUTPUT_DIR / "01_load_results.csv"
errors_csv = OUTPUT_DIR / "02_errors.csv"

summary_df.to_csv(summary_csv, index=False, encoding="utf-8-sig")
results_df.to_csv(results_csv, index=False, encoding="utf-8-sig")
error_columns = [column for column in results_df.columns if column.endswith("_error")]
error_filter = results_df[error_columns].notna().any(axis=1) if error_columns else pd.Series(False, index=results_df.index)
results_df[error_filter].to_csv(errors_csv, index=False, encoding="utf-8-sig")

display(summary_df)
print("Resultados exportados en:", OUTPUT_DIR)

,metric,value
0,run_timestamp,20260615_162625
1,preparation_run,20260615_155625
2,dry_run,False
3,mosaic_dataset,\\amssclgis08.ams.gmams.cl\CL_MLP_PAO\01_Proye...
4,records_to_process,32
5,maxps_value,10000
6,lowps_value,0.15
7,copy_status_copied,32
8,mosaic_add_status_added,32
9,footprint_status_built,32
10,attribute_status_updated,32
11,overall_status_ok,32

Resultados exportados en: c:\Users\esrlrivero_adm\Documents\Geosupport\amsa-pao-geosupport\outputs\carga_mosaico\20260615_162625

In [5]:
Name = 'CL_MLP_PAO_IF_Ortho_26_05_01_Estacion_Cabecera'
load_df['Name'].tolist()

['CL_MLP_PAO_IF_Ortho_26_05_01_Estacion_Cabecera',
 'CL_MLP_PAO_IF_Ortho_26_05_06_Subestacion-El-Mauro-1',
 'CL_MLP_PAO_IF_Ortho_26_05_06_Subestacion-El-Mauro-2',
 'CL_MLP_PAO_IF_Ortho_26_05_06_TORRE_E85_A_E_125',
 'CL_MLP_PAO_IF_Ortho_26_05_10_ED1',
 'CL_MLP_PAO_IF_Ortho_26_05_10_Helipuerto',
 'CL_MLP_PAO_IF_Ortho_26_05_10_Patio-19B-y-Armado',
 'CL_MLP_PAO_IF_Ortho_26_05_10_DME9-PA12-IIFF8',
 'CL_MLP_PAO_IF_Ortho_26_05_07_TORRES_E48_A_E84_PV4',
 'CL_MLP_PAO_IF_Ortho_26_05_10_MonteAranda-NSTC-Km-84p2-a-82p3',
 'CL_MLP_PAO_IF_Ortho_26_05_13_DME9-PA12-IIFF8',
 'CL_MLP_PAO_IF_Ortho_26_05_13_Subestacion-El-Mauro_A_E35',
 'CL_MLP_PAO_IF_Ortho_26_05_13_Subestacion-El-Mauro-1',
 'CL_MLP_PAO_IF_Ortho_26_05_13_EM2_S2',
 'CL_MLP_PAO_IF_Ortho_26_05_13_EBD-1',
 'CL_MLP_PAO_IF_Ortho_26_05_13_ED2',
 'CL_MLP_PAO_IF_Ortho_26_05_13_Subestacion-El-Mauro-2',
 'CL_MLP_PAO_IF_Ortho_26_05_13_EBD-2',
 'CL_MLP_PAO_IF_Ortho_26_05_13_Estacion_Intermedia',
 'CL_MLP_PAO_IF_Ortho_26_05_14_EM3',
 'CL_MLP_PAO_IF_Ortho_26_05_14_Camino_Alternativo_Salamanca',
 'CL_MLP_PAO_IF_Ortho_26_05_14_TORRES_E31_A_E48_PV4-1',
 'CL_MLP_PAO_IF_Ortho_26_05_14_Subestacion-El-Mauro_A_E35',
 'CL_MLP_PAO_IF_Ortho_26_05_15_Helipuerto-1',
 'CL_MLP_PAO_IF_Ortho_26_05_15_Helipuerto-2',
 'CL_MLP_PAO_IF_Ortho_26_05_15_EV1',
 'CL_MLP_PAO_IF_Ortho_26_05_15_Estacion_Cabecera',
 'CL_MLP_PAO_IF_Ortho_26_05_16_TORRES_E48_A_E84_PV4',
 'CL_MLP_PAO_IF_Ortho_26_05_17_EV2',
 'CL_MLP_PAO_IF_Ortho_26_05_17_EDT',
 'CL_MLP_PAO_IF_Ortho_26_05_14_TORRES_E31_A_E48_PV4-2',
 'CL_MLP_PAO_IF_Ortho_26_05_15_EM1']

In [7]:
q = tuple(results_df['Name'])
q = f'Name IN {q}'
q

"Name IN ('CL_MLP_PAO_IF_Ortho_26_05_01_Estacion_Cabecera', 'CL_MLP_PAO_IF_Ortho_26_05_06_Subestacion-El-Mauro-1', 'CL_MLP_PAO_IF_Ortho_26_05_06_Subestacion-El-Mauro-2', 'CL_MLP_PAO_IF_Ortho_26_05_06_TORRE_E85_A_E_125', 'CL_MLP_PAO_IF_Ortho_26_05_10_ED1', 'CL_MLP_PAO_IF_Ortho_26_05_10_Helipuerto', 'CL_MLP_PAO_IF_Ortho_26_05_10_Patio-19B-y-Armado', 'CL_MLP_PAO_IF_Ortho_26_05_10_DME9-PA12-IIFF8', 'CL_MLP_PAO_IF_Ortho_26_05_07_TORRES_E48_A_E84_PV4', 'CL_MLP_PAO_IF_Ortho_26_05_10_MonteAranda-NSTC-Km-84p2-a-82p3', 'CL_MLP_PAO_IF_Ortho_26_05_13_DME9-PA12-IIFF8', 'CL_MLP_PAO_IF_Ortho_26_05_13_Subestacion-El-Mauro_A_E35', 'CL_MLP_PAO_IF_Ortho_26_05_13_Subestacion-El-Mauro-1', 'CL_MLP_PAO_IF_Ortho_26_05_13_EM2_S2', 'CL_MLP_PAO_IF_Ortho_26_05_13_EBD-1', 'CL_MLP_PAO_IF_Ortho_26_05_13_ED2', 'CL_MLP_PAO_IF_Ortho_26_05_13_Subestacion-El-Mauro-2', 'CL_MLP_PAO_IF_Ortho_26_05_13_EBD-2', 'CL_MLP_PAO_IF_Ortho_26_05_13_Estacion_Intermedia', 'CL_MLP_PAO_IF_Ortho_26_05_14_EM3', 'CL_MLP_PAO_IF_Ortho_26_05_14_Camino_Alternativo_Salamanca', 'CL_MLP_PAO_IF_Ortho_26_05_14_TORRES_E31_A_E48_PV4-1', 'CL_MLP_PAO_IF_Ortho_26_05_14_Subestacion-El-Mauro_A_E35', 'CL_MLP_PAO_IF_Ortho_26_05_15_Helipuerto-1', 'CL_MLP_PAO_IF_Ortho_26_05_15_Helipuerto-2', 'CL_MLP_PAO_IF_Ortho_26_05_15_EV1', 'CL_MLP_PAO_IF_Ortho_26_05_15_Estacion_Cabecera', 'CL_MLP_PAO_IF_Ortho_26_05_16_TORRES_E48_A_E84_PV4', 'CL_MLP_PAO_IF_Ortho_26_05_17_EV2', 'CL_MLP_PAO_IF_Ortho_26_05_17_EDT', 'CL_MLP_PAO_IF_Ortho_26_05_14_TORRES_E31_A_E48_PV4-2', 'CL_MLP_PAO_IF_Ortho_26_05_15_EM1')"

In [ ]:
import arcpy

Estado = 'Activo'
with arcpy.da.SearchCursor(
    PATH_MOSAIC_DATASET,
    ['NombreVuelo'],
    where_clause=None,
    sql_clause=(None, "ORDER BY Name ASC")
) as cursor:
    for c in cursor:
        if c[0] is not None:
            print(c)
            break

('143_25_12_19_Plataforma_Integrada_El_Mauro',)

In [ ]:
# with arcpy.da.UpdateCursor(
#     PATH_MOSAIC_DATASET,
#     ['Estado'],
#     where_clause=q
    
# ) as cursor:
#     for c in cursor:
#         c[0] = 'Activo'
#         cursor.updateRow(c)

['Activo']

## Se cargan los footprint

In [54]:
arcpy.env.overwriteOutput = True
fc_footprint_temp = 'in_memory/foot3'
arcpy.ExportMosaicDatasetGeometry_management(PATH_MOSAIC_DATASET,
                                             out_feature_class=fc_footprint_temp,
                                             where_clause=q)

In [55]:
arcpy.GetCount_management(fc_footprint_temp)[0]

'32'

In [56]:
import re
fc_footprint = r'\\amssclgis08.ams.gmams.cl\CL_MLP_PAO\02_FGDB\CL_MLP_PAO_v1.gdb\CL_MLP_PAO_06_COMPLEMENTOS\CL_MLP_PAO_Indice_Vuelos_PAO_IMGS_PO'

mapsfields = {
    'FechaAdqui':'Fecha_Adqu', 
    'FechaCarga':'Fecha_Publ' ,
    'NombreVuelo':'Nombre_de_Vuelo', 
    'ProductName':'ProductNam'
    }
## Se renombran los campos de la exportacion
for f in mapsfields:
    old_name = f
    new_name = mapsfields[f]
    print(f'{old_name} ==> {new_name}')
    arcpy.AlterField_management(fc_footprint_temp,old_name,new_name)

FechaAdqui ==> Fecha_Adqu
FechaCarga ==> Fecha_Publ
NombreVuelo ==> Nombre_de_Vuelo
ProductName ==> ProductNam

In [57]:
arcpy.Append_management(fc_footprint_temp,fc_footprint,'NO_TEST','')

In [58]:
len([c for c in arcpy.da.SearchCursor(fc_footprint,['Nombre_de_Vuelo'],"Nombre_de_Vuelo is null")])

36

In [73]:
cols = ['Nombre_de_Vuelo','Sector','Fecha_Adqu']
with arcpy.da.UpdateCursor(
    fc_footprint,
    cols,
    where_clause=None,
    sql_clause=(None, "ORDER BY Name ASC")
) as cursor:
    cnt = 0
    for c in cursor:
        if c[1] and c[2]:
            cnt +=1
            fecha = pd.to_datetime(c[2]).strftime('%y_%m_%d')
            numero = str(cnt).zfill(3)
            sector = c[1]
            name_ = f'{numero}_{fecha}_{sector}'
            c[0] = name_
            cursor.updateRow(c)
            print(name_)

001_25_01_08_EB1
002_25_02_26_RutaD835
003_25_03_10_NSTC_116a118
004_25_03_10_NSTC_118a120
005_25_03_12_SRA2
006_25_03_17_NSTC_Km_120_a_121
007_25_03_19_Orejas16_Ruta-D-865
008_25_03_19_Orejas17_Ruta-D-865
009_25_03_19_Orejas18
010_25_03_31_EB2
011_25_03_31_EV2
012_25_04_02_DME-13
013_25_04_02_Patio-Acopio-17
014_25_04_02_Ruta-SE-a-DME-13
015_25_04_03_Area-patio-19b-y-armado
016_25_04_03_Subestacion-El-Mauro
017_25_04_09_Cachimba_de_Bajo_Camisas_ED2
018_25_04_10_Sector_Pupio_I_Area_1
019_25_05_07_Monte-Aranda-84p2-a-82p3
020_25_05_07_Monte_Aranda_82p3_a_80p7
021_25_05_12_EDT
022_25_05_12_IIFF15-Campamento-Tipay
023_25_05_15_DME9_PA12_IIFF8
024_25_05_15_ED1_IIFF7_DME8
025_25_05_15_EM2_PA11_01
026_25_05_29_DME5A_DME17_a_NSTC_78p9
027_25_06_02_ByPassDrenes_Estacion_Drenes_El_Mauro
028_25_06_02_Estacion_Drenes_El_Mauro
029_25_06_04_CaminoAcceso03_LasAnimas
030_25_06_04_EM3
031_25_06_05_33-kv-74p7-a-75p5
032_25_06_05_33-kV-NSTC-km-75p5-a-76p4
033_25_06_09_EB2
034_25_06_09_EV2
035_25_06_09_EV2_a_NSTC_Km_87p1
036_25_06_09_Tramo_EV2_a_EB2
037_25_06_11_Subestacion_El_Mauro
038_25_06_18_NSTC-Km_39_a_40p4f
039_25_06_18_NSTC_Km_36p5_a_37p7
040_25_06_18_NSTC_Km_37p7_a_39
041_25_06_18_NSTC_Km_40p4_a_PA10
042_25_06_23_NSTC_Km_121p5_a_123p5f
043_25_06_23_NSTC_Km_123p5_a_124p7f
044_25_06_26_EV2
045_25_06_26_Monte_Aranda_82p3_a_80p7
046_25_06_26_Monte_Aranda_84p2_a_82p3
047_25_06_26_Tramo_EV2_a_EB2
048_25_07_02_DME9_PA12_IIFF8_2
049_25_07_02_EM2_PA10_PA11_2
050_25_07_03_EV1
051_25_07_03_IIFF4_PA4
052_25_07_03_NSTC_Km_16p1_a_DME4
053_25_07_09_NSTC_Km_100_a_101
054_25_07_15_NSTC_Km_101_a_102f
055_25_07_15_NSTC_Km_102_a_103p2f
056_25_07_15_Oreja_16_NSTC_103p3_a_103p8_2f
057_25_07_15_Oreja_17_NSTC_103p7_a_104p9_2f
058_25_07_16_NSTC_Km_105p6_a_107f
059_25_07_16_NSTC_Km_99_a_100f
060_25_07_16_Oreja_18_NSTC_104p9_a_105p6_2f
061_25_07_22_NSTC_Km_107_a_108
062_25_07_22_NSTC_Km_108_a_109p1
063_25_07_22_NSTC_Km_109p1_a_110
064_25_07_22_NSTC_Km_110_a_111
065_25_07_22_NSTC_Km_111_a_112
066_25_08_12_Linea_33_kV_NorteElMauro_Area11_11
067_25_08_12_Linea_33_kV_NorteElMauro_Area12_12
068_25_08_13_Linea_33_kV_NorteElMauro_Area10_10
069_25_08_13_Linea_33_kV_NorteElMauro_Area9_9
070_25_08_20_Linea_33_kV_NorteElMauro_Area7_7
071_25_08_20_Linea_33_kV_NorteElMauro_Area8_8
072_25_08_26_Linea_33_kV_NorteElMauro_Area5_5
073_25_08_26_Linea_33_kV_NorteElMauro_Area6_6
074_25_08_28_Linea_33_kV_NorteElMauro_Area3_3
075_25_08_28_Linea_33_kV_NorteElMauro_Area4_4
076_25_09_02_DME5C_DME_16_a_NSTC_79p4
077_25_09_02_Instalacion_FaenaN15_Alrededores_Tipay_2
078_25_09_03_EstructuraTranquilla_NSTC_Km_20_a_21
079_25_09_03_NSTC-Km-21-a-22-DME5
080_25_09_03_Tranquilla-NSTC-Km-18-a-19
081_25_09_03_Tranquilla-NSTC-Km-19-a-20
082_25_09_09_NSTC_Km_112_a_113
083_25_09_09_NSTC_Km_113_a_114
084_25_09_09_NSTC_Km_114_a_115
085_25_09_09_NSTC_Km_115_a_116p4
086_25_09_10_Area_Mauro_H
087_25_09_10_ElMauro_Asentamiento_AeronauticoGP
088_25_09_11_Linea33kV_Norte_El_Mauro_Area_1_1
089_25_09_11_Linea33kV_Norte_El_Mauro_Area_2_2
090_25_09_24_EC-TK100-SRA2
091_25_09_24_NSTC-2p3-a-4p4-Area-1
092_25_09_24_NSTC-Km-0-a-1p1-SRA
093_25_09_24_NSTC-Km-1p1-a-1p5-SRA
094_25_09_24_NSTC-Km-1p5-a-2p2
095_25_09_24_NSTC-km-2p2-a-3p5
096_25_09_24_SRA-2-km-56p1-a-57p7-Area-2
097_25_09_24_SRA2-Km-57p7-a-59
098_25_09_25_EM1
099_25_09_25_EM1-EstacionChoapa3
100_25_09_25_NSTC-km-7p0-a-8p3
101_25_09_25_SRA-2-53p2-a-54p6
102_25_10_01_NSTC_Km_87p1_a_88p7
103_25_10_01_Pupio_I_sector_2_2
104_25_10_02_NSTC_Km_91p5_a_92
105_25_10_02_NSTC_Km_92_a_93
106_25_10_02_NSTC_Km_93_a_94
107_25_10_02_NSTC_Km_94_a_95
108_25_10_07_DME5A_DME17_a_NSTC_78p9
109_25_10_07_DME5C_DME_16_a_NSTC_79p4
110_25_10_08_ElMauro_E7_E9
111_25_10_09_ElMauro_E7_E8
112_25_10_15_DME_13
113_25_10_16_NSTC_Km_100_a_101
114_25_10_16_Oreja_17_NSTC_103p7_a_104p9
115_25_10_16_Oreja_18_NSTC_104p9_a_105p6
116_25_10_21_NSTC_km_4p4_a_7p0
117_25_10_21_SRA_2_km_54p6_a_56p1_Area-1
118_25_11_11_CanalAraya_NSTC_Km_17_a_18
119_25_11_11_DME7_PA7_IF6
120_25_11_11_NSTC_Km_21_a_22_DME5
121_25_11_11_NSTC_Km_31_a_32
122_25_11_13_DME9-PA12-IIFF8_03
123_25_11_13_Drenaje-Bajo-Quelen
124_25_11_13_ED1-IIFF7-DME8_02
125_25_11_13_EM2-PA10-PA11_03
126_25_11_18_EB2_03
127_25_11_18_EV2_04
128_25_11_18_IIFFN13A
129_25_11_18_Tramo-EV2-a-EB2_03
130_25_11_19_ED2_02
131_25_11_19_EM3_02
132_25_11_19_NSTC-Km-50p3-a-51
133_25_11_19_NSTC-Km-56-a-57p2
134_25_11_25_Linea-33-kV-NorteElMauro-Area11_02
135_25_11_25_Linea-33-kV-NorteElMauro-Area12_02
136_25_11_27_Linea-33-kV-NorteElMauro-Area10_02
137_25_11_27_Linea-33-kV-NorteElMauro-Area9_02
138_25_12_02_Linea-33-kV-NorteElMauro-Area7_02
139_25_12_02_Linea-33-kV-NorteElMauro-Area8_02
140_25_12_03_Linea-33-kV-NorteElMauro-Area5_02
141_25_12_03_Linea-33-kV-NorteElMauro-Area6_02
142_25_12_19_Plataforma_Integrada_El_Mauro
143_25_12_26_Plataforma_Integrada_El_Mauro
144_26_01_02_Plataforma_Integrada_El_Mauro
145_26_01_03_DME5A-DME17-a-NSTC-78p9
146_26_01_04_EV2
147_26_01_07_ED2
148_26_01_07_Patio-19B-y-Armado
149_26_01_07_TORRE_E48_A_E84_PV4
150_26_01_07_TORRES_E12_-_E30_PV4
151_26_01_08_TORRES_E31_A_E48_PV4
152_26_01_09_Plataforma_Integrada_El_Mauro
153_26_01_09_TORRE_E85_A_E_125
154_26_01_10_ED1-IIFF7-DME8
155_26_01_10_ED2
156_26_01_10_MonteAranda-NSTC-Km-84p2-a-82p3
157_26_01_11_EM1
158_26_01_14_Linea-33-kV-NorteElMauro-Area1
159_26_01_14_Linea-33-kV-NorteElMauro-Area6
160_26_01_14_Linea-33-kV-NorteElMauro-Area7
161_26_01_14_Subestacion-El-Mauro
162_26_01_16_EM1
163_26_01_16_Linea-33-kV-NorteElMauro-Area3
164_26_01_16_Plataforma_Integrada_El_Mauro
165_26_01_17_MonteAranda-NSTC-Km-84p2-a-82p3
166_26_01_20_EV1
167_26_01_20_Linea-33-kV-NorteElMauro-Area3
168_26_01_21_DME9-PA12-IIFF8
169_26_01_21_ED1-IIFF7-DME8
170_26_01_21_IIFF9-PA13
171_26_01_21_InstalacionesTipay
172_26_01_22_Patio-19B-y-Armado
173_26_01_30_Plataforma_Integrada_El_Mauro
174_26_01_31_EB2_1
175_26_01_31_EV2_1
176_26_01_31_Linea-33-kV-NorteElMauro-Area3_1
177_26_01_31_MonteAranda-NSTC-Km-84p2-a-82p3
178_26_01_31_Plataforma_Integrada_El_Mauro
179_26_02_01_TORRES_E12_-_E30_PV4
180_26_02_03_TORRES_E12_-_E30_PV4
181_26_02_04_DME9_PA12_IIFF8
182_26_02_04_ED1-IIFF7-DME8
183_26_02_04_IIFF9-PA13
184_26_02_04_Linea-33-kV-NorteElMauro-Area3
185_26_02_05_33-kV-NSTC-Km-74p7-a-75p5
186_26_02_05_ED2
187_26_02_05_EV1
188_26_02_05_EV2
189_26_02_06_EM1
190_26_02_06_Patio-19B-y-Armado
191_26_02_06_Subestacion-El-Mauro
192_26_02_06_TORRE_E48_A_E84_PV4
193_26_02_07_MonteAranda-NSTC-Km-84p2-a-82p3
194_26_02_07_Plataforma_Integrada_El_Mauro
195_26_02_07_TORRE_E85_A_E_125
196_26_02_09_EM4
197_26_02_09_EM4_PR2
198_26_02_10_ED1-IIFF7-DME8
199_26_02_11_EB2
200_26_02_11_EM1_1
201_26_02_11_EV1_1
202_26_02_11_EV2
203_26_02_11_MonteAranda-NSTC-Km-84p2-a-82p3
204_26_02_11_TORRE_E85_A_E_125
205_26_02_11_TORRES_E12_-_E30_PV4
206_26_02_12_ED2
207_26_02_12_EM4
208_26_02_12_IIFF9-PA13_1
209_26_02_12_Patio-19B-y-Armado
210_26_02_13_DME9_PA12_IIFF8_1
211_26_02_13_Plataforma_Integrada_El_Mauro
212_26_02_14_Subestacion-El-Mauro
213_26_02_14_TORRES_E31_A_E48_PV4
214_26_02_18_DME9-PA12-IIFF8
215_26_02_18_TORRES_E48_A_E84_PV4
216_26_02_19_ED1_IIFF7_DME8
217_26_02_19_MonteAranda-NSTC-Km-84p2-a-82p3
218_26_02_19_TORRES_E12_-_E30_PV4
219_26_02_20_EM1
220_26_02_20_EM4
221_26_02_20_EM4_PR2
222_26_02_20_EV2
223_26_02_20_Plataforma_Integrada_El_Mauro
224_26_02_20_TORRES_E84_A_E127
225_26_02_21_ED2
226_26_02_21_EV1
227_26_02_21_IIFF9-PA13
228_26_02_21_Patio-19B-y-Armado
229_26_02_21_Subestacion-El-Mauro
230_26_02_22_TORRES_E31_A_E48_PV4
231_26_02_24_Linea-33-kV-NorteElMauro-Area3
232_26_02_25_EM4
233_26_02_25_EV1
234_26_02_25_MonteAranda-NSTC-Km-84p2-a-82p3
235_26_02_26_EB3
236_26_02_26_EM2
237_26_02_26_EV1
238_26_02_26_Subestacion-El-Mauro
239_26_02_26_TORRE_E85_A_E_125
240_26_02_27_Plataforma_Integrada_El_Mauro
241_26_02_28_Patio-19B-y-Armado
242_26_02_28_TORRES_E35_A_E48
243_26_03_01_Subestacion-El-Mauro_A_E35
244_26_03_02_ED2
245_26_03_04_DME9-PA12-IIFF8
246_26_03_04_EBD
247_26_03_04_IIFF9-PA13
248_26_03_04_Linea-33-kV-NorteElMauro-Area3
249_26_03_05_ED2
250_26_03_05_EV1
251_26_03_06_EM1
252_26_03_06_EM4
253_26_03_06_Plataforma_Integrada_El_Mauro
254_26_03_06_TORRES_E48_A_E84_PV4
255_26_03_07_EB3
256_26_03_07_ED1-IIFF7-DME8
257_26_03_07_EV2
258_26_03_07_Patio-19B-y-Armado
259_26_03_07_Subestacion-El-Mauro
260_26_03_08_MonteAranda-NSTC-Km-84p2-a-82p3
261_26_03_08_Subestacion-El-Mauro_A_E35
262_26_03_08_TORRES_E35_A_E48
263_26_03_08_TORRES_E85_A_E125
264_26_03_11_EV1
265_26_03_11_TORRES_E035_E048
266_26_03_11_TORRES_E48_A_E84_PV4
267_26_03_12_EB3
268_26_03_12_Subestacion-El-Mauro
269_26_03_12_TORRE_E85_A_E125
270_26_03_13_EM1
271_26_03_13_EM4
272_26_03_13_EV2
273_26_03_13_MonteAranda-NSTC-Km-84p2-a-82p3
274_26_03_13_Plataforma_Integrada_El_Mauro
275_26_03_14_ED1-IIFF7-DME8
276_26_03_14_EM2
277_26_03_14_IIFF9-PA13
278_26_03_14_Subestacion-El-Mauro_A_E35_
279_26_03_15_ED2
280_26_03_15_Linea-33-kV-NorteElMauro-Area3_1
281_26_03_16_Patio-19B-y-Armado
282_26_03_18_EM2
283_26_03_18_EM2_S2
284_26_03_18_EV1
285_26_03_19_ED2
286_26_03_19_EM4
287_26_03_19_Plataforma_Integrada_El_Mauro
288_26_03_20_EB3
289_26_03_20_EM1
290_26_03_20_Estacion_Drenes_El_Mauro
291_26_03_20_Patio-19B-y-Armado
292_26_03_20_Subestacion-El-Mauro
293_26_03_21_Camino_Alternativo_Salamanca
294_26_03_21_EV2
295_26_03_21_Hidrociclones
296_26_03_21_TORRE_E85_A_E_125
297_26_03_21_TORRES_E35_A_E48
298_26_03_21_TORRES_E48_A_E84_PV4
299_26_03_22_MonteAranda-NSTC-Km-84p2-a-82p3
300_26_03_26_Camino_Alternativo_Salamanca
301_26_03_26_EBD
302_26_03_26_ED2
303_26_03_26_EM3
304_26_03_26_Patio-19B-y-Armado
305_26_03_26_Plataforma_Integrada_El_Mauro
306_26_03_26_Pozos_PRP
307_26_03_26_TORRES_E48_A_E84_PV4
308_26_03_27_EB3
309_26_03_27_Estacion_Cabecera
310_26_03_27_Estacion_Intermedia
311_26_03_27_EV1
312_26_03_27_Helipuerto
313_26_03_27_MonteAranda-NSTC-Km-84p2-a-82p3
314_26_03_27_Subestacion-El-Mauro
315_26_03_27_TORRE_E85_A_E_125
316_26_03_28_EM2
317_26_03_28_IIFF9-PA13
318_26_03_28_TORRES_E35_A_E48
319_26_03_29_Acceso_a_pozos
320_26_03_29_EBR
321_26_03_29_EM1
322_26_03_29_EM4
323_26_03_29_Subestacion-El-Mauro_A_E35_
324_26_03_30_EDT
325_26_04_01_EBD
326_26_04_01_EM2
327_26_04_01_EM2_2
328_26_04_01_Pozos_PRP
329_26_04_02_Camino_Alternativo_Salamanca
330_26_04_02_ED2
331_26_04_02_EM3
332_26_04_02_EM4
333_26_04_02_Plataforma_Integrada_El_Mauro
334_26_04_02_Pozos_PRP
335_26_04_02_TORRE_E85_A_E_125
336_26_04_02_TORRES_E35_A_E48
337_26_04_02_TORRES_E48_A_E84_PV4
338_26_04_03_EM1
339_26_04_03_Estacion_Cabecera
340_26_04_04_EBR
341_26_04_04_Estacion_Intermedia
342_26_04_04_MonteAranda-NSTC-Km-84p2-a-82p3
343_26_04_05_EB3
344_26_04_05_EV1
345_26_04_05_Helipuerto
346_26_04_05_Patio-19B-y-Armado
347_26_04_05_Subestacion-El-Mauro
348_26_04_05_Subestacion-El-Mauro_A_E35
349_26_04_08_EV1
350_26_04_08_TORRES_E35_A_E48
351_26_04_09_EB3
352_26_04_09_ED2
353_26_04_09_EM1
354_26_04_09_Estacion_Intermedia
355_26_04_09_Plataforma_Integrada_El_Mauro
356_26_04_09_Subestacion-El-Mauro
357_26_04_09_Subestacion-El-Mauro_A_E35
358_26_04_10_EBD
359_26_04_10_Estacion_Cabecera
360_26_04_10_Helipuerto
361_26_04_10_Patio-19B-y-Armado
362_26_04_10_Pozos_PRP
363_26_04_10_TORRES_E48_A_E84_PV4
364_26_04_11_Camino_Alternativo_Salamanca
365_26_04_11_EDT
366_26_04_11_EM2_S2
367_26_04_11_EM3
368_26_04_11_MonteAranda-NSTC-Km-84p2-a-82p3
369_26_04_11_Pozos_PRP
370_26_04_12_EV2
371_26_04_12_TORRE_E85_A_E_125
372_26_04_13_ED1-IIFF7-DME8
373_26_04_13_EM4
374_26_04_15_EM2
375_26_04_15_EM2_S2
376_26_04_15_EV1
377_26_04_15_TORRES_E35_A_E48
378_26_04_16_Acceso_a_pozos
379_26_04_16_Camino_Alternativo_Salamanca
380_26_04_16_EBD
381_26_04_16_ED2
382_26_04_16_EM3
383_26_04_16_EM4
384_26_04_16_Pozos_PRP
385_26_04_16_TORRES_E48_A_E84_PV4
386_26_04_17_EB3
387_26_04_17_EB3
388_26_04_17_Estacion_Intermedia
389_26_04_17_Subestacion-El-Mauro
390_26_04_17_TORRE_E85_A_E_125
391_26_04_18_EBR
392_26_04_18_ED1
393_26_04_18_EM1
394_26_04_18_Estacion_Cabecera
395_26_04_18_Helipuerto
396_26_04_18_Helipuerto
397_26_04_18_MonteAranda-NSTC-Km-84p2-a-82p3
398_26_04_18_Patio-19B-y-Armado
399_26_04_19_EV2
400_26_04_22_EB3
401_26_04_22_EB3
402_26_04_22_Estacion_Intermedia
403_26_04_22_Subestacion-El-Mauro
404_26_04_23_TORRES_E35_A_E48
405_26_04_23_TORRES_E35_A_E48
406_26_04_24_Patio-19B-y-Armado
407_26_04_24_Patio-19B-y-Armado
408_26_04_25_EBD
409_26_04_25_EBD
410_26_04_25_EM1
411_26_04_25_Pozos_PRP
412_26_04_25_Pozos_PRP
413_26_04_25_TORRE_E85_A_E_125
414_26_04_26_EDT
415_26_04_29_TORRE_E85_A_E_125
416_26_04_30_EM4
417_26_04_30_TORRES_E35_A_E48
418_26_05_01_Acceso_a_pozos
419_26_05_01_EM1
420_26_05_01_Estacion_Cabecera
421_26_05_01_EV1
422_26_05_01_Pozos_PRP
423_26_05_02_ED1
424_26_05_02_EM2
425_26_05_02_EM2_S2
426_26_05_02_EV2
427_26_05_02_Subestacion-El-Mauro_A_E35
428_26_05_02_TORRES_E48_A_E84_PV4
429_26_05_03_Camino_Alternativo_Salamanca
430_26_05_03_EBD
431_26_05_03_ED2
432_26_05_03_EDT
433_26_05_03_EM3
434_26_05_03_MonteAranda-NSTC-Km-84p2-a-82p3
435_26_05_06_Camino_Alternativo_Salamanca
436_26_05_06_Subestacion-El-Mauro
437_26_05_06_Subestacion-El-Mauro
438_26_05_06_TORRE_E85_A_E_125
439_26_05_06_TORRES_E35_A_E48
440_26_05_07_ED2
441_26_05_07_EM2_S2
442_26_05_07_EM3
443_26_05_07_Estacion_Intermedia
444_26_05_07_TORRES_E48_A_E84_PV4
445_26_05_08_Acceso_a_pozos
446_26_05_08_EBD
447_26_05_08_EM4
448_26_05_08_Pozos_PRP
449_26_05_08_Subestacion-El-Mauro_A_E35
450_26_05_09_EDT
451_26_05_09_EM1
452_26_05_09_Estacion_Cabecera
453_26_05_09_EV1
454_26_05_09_EV2
455_26_05_10_DME9-PA12-IIFF8
456_26_05_10_ED1
457_26_05_10_Helipuerto
458_26_05_10_MonteAranda-NSTC-Km-84p2-a-82p3
459_26_05_10_Patio-19B-y-Armado
460_26_05_13_DME9-PA12-IIFF8
461_26_05_13_EBD
462_26_05_13_EBD
463_26_05_13_ED2
464_26_05_13_EM2_S2
465_26_05_13_Estacion_Intermedia
466_26_05_13_Subestacion-El-Mauro
467_26_05_13_Subestacion-El-Mauro
468_26_05_13_Subestacion-El-Mauro_A_E35
469_26_05_14_Camino_Alternativo_Salamanca
470_26_05_14_EM3
471_26_05_14_Subestacion-El-Mauro_A_E35
472_26_05_14_TORRES_E31_A_E48_PV4
473_26_05_14_TORRES_E31_A_E48_PV4
474_26_05_15_EM1
475_26_05_15_Estacion_Cabecera
476_26_05_15_EV1
477_26_05_15_Helipuerto
478_26_05_15_Helipuerto
479_26_05_16_TORRES_E48_A_E84_PV4
480_26_05_17_EDT
481_26_05_17_EV2

In [80]:
## Se actualiza en los footprint
querymosaic = [c[0] for c in arcpy.da.SearchCursor(PATH_MOSAIC_DATASET,['Name'])]

In [81]:
# querymosaic = f"Name IN {tuple(querymosaic)}"
cursor = arcpy.da.SearchCursor(fc_footprint,['Name','Nombre_de_Vuelo'])
df = pd.DataFrame(cursor,columns=['Name','Nombre_de_Vuelo'])
print(f'total de registros {df.shape[0]}')
df = df[df.Name.isin(querymosaic)]
print(f'total de registros {df.shape[0]}') 
df.head()

total de registros 483
total de registros 340

,Name,Nombre_de_Vuelo
141,CL_MLP_PAO_IF_Ortho_26_01_03_DME5A-DME17-a-NST...,145_26_01_03_DME5A-DME17-a-NSTC-78p9
142,CL_MLP_PAO_IF_Ortho_26_01_10_MonteAranda-NSTC-...,156_26_01_10_MonteAranda-NSTC-Km-84p2-a-82p3
143,CL_MLP_PAO_IF_Ortho_26_01_17_MonteAranda-NSTC-...,165_26_01_17_MonteAranda-NSTC-Km-84p2-a-82p3
144,CL_MLP_PAO_IF_Ortho_26_01_21_InstalacionesTipay,171_26_01_21_InstalacionesTipay
145,CL_MLP_PAO_IF_Ortho_26_01_11_EM1,157_26_01_11_EM1

In [98]:
result = []
with arcpy.da.SearchCursor(PATH_MOSAIC_DATASET,['Name','NombreVuelo']) as cursor:
    for c in cursor:
        try:
            name = c[0]
            nombre_vuelo = df.loc[df.Name == name,'Nombre_de_Vuelo'].values[0]
            result.append([c[1],nombre_vuelo])
        except:
            continue
        
df2 = pd.DataFrame(result,columns=['NombreVueloOld','NombreVuelo'])
df2.head()

,NombreVueloOld,NombreVuelo
0,148_26_01_07_ED2,147_26_01_07_ED2
1,379_26_04_11_Camino_Alternativo_Salamanca,364_26_04_11_Camino_Alternativo_Salamanca
2,None,469_26_05_14_Camino_Alternativo_Salamanca
3,394_26_04_16_Camino_Alternativo_Salamanca,379_26_04_16_Camino_Alternativo_Salamanca
4,342_26_04_02_Camino_Alternativo_Salamanca,329_26_04_02_Camino_Alternativo_Salamanca

In [ ]:
query_update = tuple(df2.NombreVueloOld)
query_update = f'NombreVuelo IN {query_update}'
dict_rename = dict(zip(df2.NombreVueloOld,df2.NombreVuelo))

In [109]:
with arcpy.da.UpdateCursor(PATH_MOSAIC_DATASET,['NombreVuelo']) as cursor:
    for c in cursor:
        new_name_ = dict_rename.get(c[0],None)
        if new_name_:
            c[0] = new_name
            cursor.updateRow(c)

'147_26_01_07_ED2'

'148_26_01_07_ED2'

In [ ]:
aprx_path = r"\\amssclgis08.ams.gmams.cl\CL_MLP_PAO\01_Proyectos_ArcGIS\APRX\VISOR TERRITORIAL SIG PAO v7.aprx"
map_name = "CL MLP PAO 27 Imagenes Aereas PAO Image Server"
prefix = "CL_MLP_PAO_IF_Ortho_"
suffix = ".tif"
 
aprx = arcpy.mp.ArcGISProject(aprx_path)
maps = aprx.listMaps(map_name)
 
if not maps:
    print("No se encontró el mapa")
else:
    m = maps[0]
 
    # 1️⃣ Renombrar
    for lyr in m.listLayers():
        try:
            original_name = lyr.name
            new_name = original_name
            if new_name.startswith(prefix):
                new_name = new_name.replace(prefix, "", 1)
            if new_name.endswith(suffix):
                new_name = new_name[:-len(suffix)]
            if new_name != original_name:
                print(f"Renombrando: {original_name} -> {new_name}")
                lyr.name = new_name
        except Exception as e:
            print(f"Error con capa {lyr.name}: {e}")
 
#     # 2️⃣ Ordenar
#     layers = [lyr for lyr in m.listLayers() if lyr.isFeatureLayer or lyr.isRasterLayer]
#     layers_sorted = sorted(layers, key=lambda l: l.name)
#     for lyr in layers_sorted:
#         m.moveLayer(m.listLayers()[0], lyr, "BEFORE")
#     print("Capas ordenadas")
 
#     # 3️⃣ Guardar una sola vez
#     aprx.save()
#     print("Proyecto guardado")
 
# del aprx  # buena práctica siempre

In [19]:
maps

In [111]:
load_df.columns

Index(['ready_for_datastore', 'review_reason', 'path', 'relative_path',
       'file_name', 'expected_file_name', 'destination_path',
       'original_expected_file_name', 'expected_name', 'expected_date_token',
       'destination_folder', 'destination_date_folder', 'expected_sector',
       'sector_source', 'rename_status', 'spatial_status',
       'spatial_sector_raw', 'spatial_sector', 'spatial_overlap_pct',
       'spatial_overlap_count', 'spatial_all_matches',
       'duplicate_expected_file_name', 'duplicate_sequence',
       'duplicate_was_resolved', 'size_mb', 'modified_at', 'Name', 'Raster',
       'Path_Destino', 'Sector', 'Fecha_Adqui', 'URL', 'Proyecto', 'Sensor',
       'Fecha_Publ', 'relative_path_attr'],
      dtype='object')

In [114]:
load_df.loc[0,'destination_path']

'\\\\amssclgis10.ams.gmams.cl\\CL_MLP_PAO\\Chacay_Drone\\26_05\\CL_MLP_PAO_IF_Ortho_26_05_01_Estacion_Cabecera.tif'

In [119]:
from pathlib import Path
import csv
import arcpy

LOAD_RESULTS_CSV = Path.cwd() / "outputs" / "carga_mosaico" / "20260615_162625" / "01_load_results.csv"

aprx_path = r"\\amssclgis08.ams.gmams.cl\CL_MLP_PAO\01_Proyectos_ArcGIS\APRX\VISOR TERRITORIAL SIG PAO v7.aprx"
map_name = "CL MLP PAO 27 Imagenes Aereas PAO Image Server"
TARGET_GROUP_LAYER_NAME = None  # Opcional: escribir aqui el nombre exacto del grupo si quieres forzarlo.
prefix = "CL_MLP_PAO_IF_Ortho_"
suffix = ".tif"
SAVE_COPY_FOR_REVIEW = True
ADD_ONLY_MISSING_TO_GROUP = True  # La lista del CSV se agrega como nuevas capas al grupo existente.
APRX_COPY_PATH = f"{Path.cwd()}\APRX\{Path(aprx_path).stem}_verificacion_carga_imagenes.aprx"

def clean_layer_name(name):
    clean_name = Path(str(name)).name
    if clean_name.startswith(prefix):
        clean_name = clean_name.replace(prefix, "", 1)
    if clean_name.endswith(suffix):
        clean_name = clean_name[:-len(suffix)]
    return clean_name


def read_loaded_image_paths(csv_path):
    with csv_path.open("r", encoding="utf-8-sig", newline="") as file:
        rows = csv.DictReader(file)
        return [
            row["destination_path"]
            for row in rows
            if row.get("overall_status") == "ok" and row.get("destination_path")
        ]


def layer_long_name(layer):
    try:
        return layer.longName
    except Exception:
        return layer.name


def is_child_of_group(layer, group_layer):
    long_name = layer_long_name(layer)
    group_long_name = layer_long_name(group_layer)
    return long_name.startswith(group_long_name + "\\")


def layer_matches_image_naming(layer):
    name = Path(str(layer.name)).name
    return name.startswith(prefix) or name.endswith(suffix) or clean_layer_name(name) != name


def find_target_group_layer(map_obj, explicit_group_name=None):
    groups = [lyr for lyr in map_obj.listLayers() if lyr.isGroupLayer]

    if explicit_group_name:
        matches = [lyr for lyr in groups if lyr.name == explicit_group_name or layer_long_name(lyr) == explicit_group_name]
        if not matches:
            available = [layer_long_name(lyr) for lyr in groups]
            raise ValueError(f"No se encontro el grupo '{explicit_group_name}'. Grupos disponibles: {available}")
        return matches[0]

    candidates = []
    for group_layer in groups:
        child_layers = [lyr for lyr in map_obj.listLayers() if lyr != group_layer and is_child_of_group(lyr, group_layer)]
        image_children = [lyr for lyr in child_layers if (lyr.isRasterLayer or lyr.isFeatureLayer) and layer_matches_image_naming(lyr)]
        if image_children:
            candidates.append((len(image_children), group_layer))

    if not candidates:
        available = [layer_long_name(lyr) for lyr in groups]
        raise ValueError(
            "No se pudo detectar automaticamente el grupo destino. "
            f"Define TARGET_GROUP_LAYER_NAME. Grupos disponibles: {available}"
        )

    candidates.sort(key=lambda item: item[0], reverse=True)
    return candidates[0][1]


def group_child_layers(map_obj, group_layer):
    return [
        lyr
        for lyr in map_obj.listLayers()
        if lyr != group_layer and is_child_of_group(lyr, group_layer) and (lyr.isFeatureLayer or lyr.isRasterLayer)
    ]


def add_raster_to_group(map_obj, group_layer, image_path, target_name):
    top_layer = map_obj.addDataFromPath(image_path)
    top_layer.name = target_name

    grouped_layers = map_obj.addLayerToGroup(group_layer, top_layer, "BOTTOM")
    map_obj.removeLayer(top_layer)

    if grouped_layers:
        grouped_layer = grouped_layers[0] if isinstance(grouped_layers, list) else grouped_layers
        grouped_layer.name = target_name
        return grouped_layer

    for lyr in group_child_layers(map_obj, group_layer):
        if clean_layer_name(lyr.name).lower() == target_name.lower():
            lyr.name = target_name
            return lyr

    return None


image_paths_to_add = read_loaded_image_paths(LOAD_RESULTS_CSV)
print(f"Imagenes cargadas a revisar en APRX: {len(image_paths_to_add)}")

aprx = arcpy.mp.ArcGISProject(aprx_path)

try:
    maps = aprx.listMaps(map_name)

    if not maps:
        print("No se encontro el mapa")
    else:
        m = maps[0]
        target_group = find_target_group_layer(m, TARGET_GROUP_LAYER_NAME)
        print(f"Grupo destino: {layer_long_name(target_group)}")

        existing_group_layers_before = group_child_layers(m, target_group)
        existing_names = {clean_layer_name(lyr.name).lower() for lyr in existing_group_layers_before}
        print(f"Capas existentes en el grupo antes de agregar: {len(existing_group_layers_before)}")
        added_count = 0
        skipped_count = 0
        error_count = 0

        # 1. Agregar al grupo destino solo las imagenes nuevas del CSV.
        #    Las capas que ya existen en el grupo se conservan y no se reemplazan.
        for image_path in image_paths_to_add:
            target_name = clean_layer_name(Path(image_path).name)
            target_key = target_name.lower()

            if ADD_ONLY_MISSING_TO_GROUP and target_key in existing_names:
                print(f"Ya existe en el grupo, se conserva y se omite: {target_name}")
                skipped_count += 1
                continue

            try:
                grouped_layer = add_raster_to_group(m, target_group, image_path, target_name)
                existing_names.add(target_key)
                added_count += 1
                print(f"Agregada al grupo: {target_name}")
            except Exception as exc:
                error_count += 1
                print(f"Error agregando {image_path}: {exc}")

        # 2. Renombrar solamente las capas del grupo destino con la nomenclatura limpia.
        renamed_count = 0
        for lyr in group_child_layers(m, target_group):
            try:
                original_name = lyr.name
                new_name = clean_layer_name(original_name)
                if new_name != original_name:
                    print(f"Renombrando: {original_name} -> {new_name}")
                    lyr.name = new_name
                    renamed_count += 1
            except Exception as exc:
                print(f"Error con capa {lyr.name}: {exc}")

        # 3. Ordenar alfabeticamente solamente las capas del grupo destino.
        layers = group_child_layers(m, target_group)
        for lyr in sorted(layers, key=lambda layer: layer.name, reverse=True):
            current_group_layers = group_child_layers(m, target_group)
            first_layer = current_group_layers[0] if current_group_layers else None
            if first_layer and lyr != first_layer:
                m.moveLayer(first_layer, lyr, "BEFORE")

        print("Capas del grupo ordenadas")
        existing_group_layers_after = group_child_layers(m, target_group)
        print(f"Capas existentes en el grupo despues de agregar: {len(existing_group_layers_after)}")
        print(f"Resumen APRX: nuevas_agregadas={added_count}, existentes_conservadas={skipped_count}, renombradas={renamed_count}, errores={error_count}")

        # 4. Guardar el proyecto o una copia de revision.
        if SAVE_COPY_FOR_REVIEW:
            aprx.saveACopy(APRX_COPY_PATH)
            print(f"Copia de verificacion guardada: {APRX_COPY_PATH}")
        else:
            aprx.save()
            print("Proyecto original guardado")
finally:
    del aprx

Imagenes cargadas a revisar en APRX: 32
Grupo destino: Vuelos Drone PAO
Capas existentes en el grupo antes de agregar: 468
Agregada al grupo: 26_05_01_Estacion_Cabecera
Agregada al grupo: 26_05_06_Subestacion-El-Mauro-1
Agregada al grupo: 26_05_06_Subestacion-El-Mauro-2
Agregada al grupo: 26_05_06_TORRE_E85_A_E_125
Agregada al grupo: 26_05_10_ED1
Agregada al grupo: 26_05_10_Helipuerto
Agregada al grupo: 26_05_10_Patio-19B-y-Armado
Agregada al grupo: 26_05_10_DME9-PA12-IIFF8
Agregada al grupo: 26_05_07_TORRES_E48_A_E84_PV4
Agregada al grupo: 26_05_10_MonteAranda-NSTC-Km-84p2-a-82p3
Agregada al grupo: 26_05_13_DME9-PA12-IIFF8
Agregada al grupo: 26_05_13_Subestacion-El-Mauro_A_E35
Agregada al grupo: 26_05_13_Subestacion-El-Mauro-1
Agregada al grupo: 26_05_13_EM2_S2
Agregada al grupo: 26_05_13_EBD-1
Agregada al grupo: 26_05_13_ED2
Agregada al grupo: 26_05_13_Subestacion-El-Mauro-2
Agregada al grupo: 26_05_13_EBD-2
Agregada al grupo: 26_05_13_Estacion_Intermedia
Agregada al grupo: 26_05_14_EM3
Agregada al grupo: 26_05_14_Camino_Alternativo_Salamanca
Agregada al grupo: 26_05_14_TORRES_E31_A_E48_PV4-1
Agregada al grupo: 26_05_14_Subestacion-El-Mauro_A_E35
Agregada al grupo: 26_05_15_Helipuerto-1
Agregada al grupo: 26_05_15_Helipuerto-2
Agregada al grupo: 26_05_15_EV1
Agregada al grupo: 26_05_15_Estacion_Cabecera
Agregada al grupo: 26_05_16_TORRES_E48_A_E84_PV4
Agregada al grupo: 26_05_17_EV2
Agregada al grupo: 26_05_17_EDT
Agregada al grupo: 26_05_14_TORRES_E31_A_E48_PV4-2
Agregada al grupo: 26_05_15_EM1
Renombrando: CL_MLP_PAO_IF_Ortho_26_05_09_EV1.tif -> 26_05_09_EV1
Renombrando: CL_MLP_PAO_IF_Ortho_26_05_07_EM3.tif -> 26_05_07_EM3
Renombrando: CL_MLP_PAO_IF_Ortho_26_05_07_EM2_S2.tif -> 26_05_07_EM2_S2
Renombrando: CL_MLP_PAO_IF_Ortho_26_05_07_ED2.tif -> 26_05_07_ED2
Renombrando: CL_MLP_PAO_IF_Ortho_26_05_03_EM3.tif -> 26_05_03_EM3
Renombrando: CL_MLP_PAO_IF_Ortho_26_05_03_ED2.tif -> 26_05_03_ED2
Renombrando: CL_MLP_PAO_IF_Ortho_26_05_02_EM2_S2.tif -> 26_05_02_EM2_S2
Renombrando: CL_MLP_PAO_IF_Ortho_26_05_02_EM2.tif -> 26_05_02_EM2
Renombrando: CL_MLP_PAO_IF_Ortho_26_05_02_ED1.tif -> 26_05_02_ED1
Renombrando: CL_MLP_PAO_IF_Ortho_26_05_01_EV1.tif -> 26_05_01_EV1
Capas del grupo ordenadas
Capas existentes en el grupo despues de agregar: 500
Resumen APRX: nuevas_agregadas=32, existentes_conservadas=0, renombradas=10, errores=0
Copia de verificacion guardada: c:\Users\esrlrivero_adm\Documents\Geosupport\amsa-pao-geosupport\APRX\VISOR TERRITORIAL SIG PAO v7_verificacion_carga_imagenes.aprx

In [122]:
fc_footprint
q

"Name IN ('CL_MLP_PAO_IF_Ortho_26_05_01_Estacion_Cabecera', 'CL_MLP_PAO_IF_Ortho_26_05_06_Subestacion-El-Mauro-1', 'CL_MLP_PAO_IF_Ortho_26_05_06_Subestacion-El-Mauro-2', 'CL_MLP_PAO_IF_Ortho_26_05_06_TORRE_E85_A_E_125', 'CL_MLP_PAO_IF_Ortho_26_05_10_ED1', 'CL_MLP_PAO_IF_Ortho_26_05_10_Helipuerto', 'CL_MLP_PAO_IF_Ortho_26_05_10_Patio-19B-y-Armado', 'CL_MLP_PAO_IF_Ortho_26_05_10_DME9-PA12-IIFF8', 'CL_MLP_PAO_IF_Ortho_26_05_07_TORRES_E48_A_E84_PV4', 'CL_MLP_PAO_IF_Ortho_26_05_10_MonteAranda-NSTC-Km-84p2-a-82p3', 'CL_MLP_PAO_IF_Ortho_26_05_13_DME9-PA12-IIFF8', 'CL_MLP_PAO_IF_Ortho_26_05_13_Subestacion-El-Mauro_A_E35', 'CL_MLP_PAO_IF_Ortho_26_05_13_Subestacion-El-Mauro-1', 'CL_MLP_PAO_IF_Ortho_26_05_13_EM2_S2', 'CL_MLP_PAO_IF_Ortho_26_05_13_EBD-1', 'CL_MLP_PAO_IF_Ortho_26_05_13_ED2', 'CL_MLP_PAO_IF_Ortho_26_05_13_Subestacion-El-Mauro-2', 'CL_MLP_PAO_IF_Ortho_26_05_13_EBD-2', 'CL_MLP_PAO_IF_Ortho_26_05_13_Estacion_Intermedia', 'CL_MLP_PAO_IF_Ortho_26_05_14_EM3', 'CL_MLP_PAO_IF_Ortho_26_05_14_Camino_Alternativo_Salamanca', 'CL_MLP_PAO_IF_Ortho_26_05_14_TORRES_E31_A_E48_PV4-1', 'CL_MLP_PAO_IF_Ortho_26_05_14_Subestacion-El-Mauro_A_E35', 'CL_MLP_PAO_IF_Ortho_26_05_15_Helipuerto-1', 'CL_MLP_PAO_IF_Ortho_26_05_15_Helipuerto-2', 'CL_MLP_PAO_IF_Ortho_26_05_15_EV1', 'CL_MLP_PAO_IF_Ortho_26_05_15_Estacion_Cabecera', 'CL_MLP_PAO_IF_Ortho_26_05_16_TORRES_E48_A_E84_PV4', 'CL_MLP_PAO_IF_Ortho_26_05_17_EV2', 'CL_MLP_PAO_IF_Ortho_26_05_17_EDT', 'CL_MLP_PAO_IF_Ortho_26_05_14_TORRES_E31_A_E48_PV4-2', 'CL_MLP_PAO_IF_Ortho_26_05_15_EM1')"

In [136]:
PATH_MOSAIC_DATASET
cursor = arcpy.da.SearchCursor(PATH_MOSAIC_DATASET,['Name','URL','OBJECTID'],q)
df = pd.DataFrame(cursor,columns=['Name','URL','OBJECTID'])

In [139]:
with arcpy.da.UpdateCursor(fc_footprint,['Name','URL','ProductNam'],q) as cursor:
    for c in cursor:
    
        # url_ = df.loc[df.Name == c[0],'URL'].values[0]
        # url_
        # c[1] = url_
        obj = df.loc[df.Name == c[0],'OBJECTID'].values[0]
        c[2] = str(obj)
        
        cursor.updateRow(c)

In [138]:
c

['CL_MLP_PAO_IF_Ortho_26_05_01_Estacion_Cabecera',
 'https://sig.aminerals.cl/imgdyn/rest/services/CL_MLP_PAO/CL_MLP_PAO_IF_Ortho_Geosupport/ImageServer/file?id=.\\Chacay_Drone\\26_05\\CL_MLP_PAO_IF_Ortho_26_05_01_Estacion_Cabecera.tif&rasterId=',
 '20826']

In [133]:
cursor = arcpy.da.SearchCursor(PATH_MOSAIC_DATASET,['Name','URL','ProductName'],q)
df = pd.DataFrame(cursor,columns=['Name','URL','ProductName'])

In [134]:
df = df[df.URL.notnull()].reset_index(drop=True)
df.head()

,Name,URL,ProductName
0,CL_MLP_PAO_IF_Ortho_26_05_01_Estacion_Cabecera,https://sig.aminerals.cl/imgdyn/rest/services/...,
1,CL_MLP_PAO_IF_Ortho_26_05_06_Subestacion-El-Ma...,https://sig.aminerals.cl/imgdyn/rest/services/...,
2,CL_MLP_PAO_IF_Ortho_26_05_06_Subestacion-El-Ma...,https://sig.aminerals.cl/imgdyn/rest/services/...,
3,CL_MLP_PAO_IF_Ortho_26_05_06_TORRE_E85_A_E_125,https://sig.aminerals.cl/imgdyn/rest/services/...,
4,CL_MLP_PAO_IF_Ortho_26_05_10_ED1,https://sig.aminerals.cl/imgdyn/rest/services/...,

In [131]:
df.loc[2,'URL']

'https://sig.aminerals.cl/imgdyn/rest/services/CL_MLP_PAO/CL_MLP_PAO_IF_Ortho_Geosupport/ImageServer/file?id=.\\El_Mauro_Drone\\26_05\\CL_MLP_PAO_IF_Ortho_26_05_14_Camino_Alternativo_Salamanca.tif&rasterId='

In [ ]:
'https://sig.aminerals.cl/imgdyn/rest/services/CL_MLP_PAO/CL_MLP_PAO_IF_Ortho_Geosupport/ImageServer/file?id=.\\El_Mauro_Drone\\26_05\\CL_MLP_PAO_IF_Ortho_26_05_14_Camino_Alternativo_Salamanca.tif&rasterId='

In [144]:
import os
FOLDER_APRX = rf'{Path.cwd()}\APRX'
os.makedirs(FOLDER_APRX,exist_ok=True)

In [145]:
from pathlib import Path
import csv
import re
import arcpy


LOAD_RESULTS_CSV = Path.cwd() / "outputs" / "carga_mosaico" / "20260615_162625" / "01_load_results.csv"

aprx_path = r"\\amssclgis08.ams.gmams.cl\CL_MLP_PAO\01_Proyectos_ArcGIS\APRX\VISOR TERRITORIAL SIG PAO v7.aprx"
map_name = "CL MLP PAO 27 Imagenes Aereas PAO Image Server"
PARENT_GROUP_NAME = "Vuelos Drone PAO"
TARGET_GROUP_NAME = "Imagenes Drone"
prefix = "CL_MLP_PAO_IF_Ortho_"
suffix = ".tif"
SAVE_COPY_FOR_REVIEW = True
ADD_ONLY_MISSING_TO_GROUP = True
APRX_COPY_PATH = fr"{FOLDER_APRX}\{Path(aprx_path).stem}_verificacion_carga_imagenes.aprx"


def layer_long_name(layer):
    try:
        return layer.longName
    except Exception:
        return layer.name


def short_layer_name(name):
    short_name = Path(str(name)).name

    while short_name.startswith("tmp_"):
        short_name = short_name.replace("tmp_", "", 1)

    if short_name.startswith(prefix):
        short_name = short_name.replace(prefix, "", 1)

    if short_name.endswith(suffix):
        short_name = short_name[:-len(suffix)]

    return short_name


def layer_name_from_path(path_value):
    return short_layer_name(Path(str(path_value)).name)


def comparable_layer_keys(name):
    short_name = short_layer_name(name)
    full_name = f"{prefix}{short_name}{suffix}"
    tmp_full_name = f"tmp_{full_name}"
    return {short_name.lower(), full_name.lower(), tmp_full_name.lower()}


def is_image_layer_name(name):
    short_name = short_layer_name(name)
    return bool(re.match(r"^\d{2}_\d{2}_\d{2}_.+", short_name))


def sort_key_newest_first(layer_name):
    name = short_layer_name(layer_name)
    match = re.search(r"^(\d{2})_(\d{2})_(\d{2})_", name)
    if match:
        yy, mm, dd = match.groups()
        return (int(yy), int(mm), int(dd), name.lower())
    return (0, 0, 0, name.lower())


def read_loaded_image_paths(csv_path):
    with csv_path.open("r", encoding="utf-8-sig", newline="") as file:
        rows = csv.DictReader(file)
        return [
            row["destination_path"]
            for row in rows
            if row.get("overall_status") == "ok" and row.get("destination_path")
        ]


def is_descendant_of_group(layer, group_layer):
    return layer_long_name(layer).startswith(layer_long_name(group_layer) + "\\")


def is_direct_child_of_group(layer, group_layer):
    long_name = layer_long_name(layer)
    group_long_name = layer_long_name(group_layer)
    prefix_name = group_long_name + "\\"
    if not long_name.startswith(prefix_name):
        return False
    relative_name = long_name[len(prefix_name):]
    return "\\" not in relative_name


def direct_child_groups(map_obj, parent_group):
    return [
        lyr
        for lyr in map_obj.listLayers()
        if lyr.isGroupLayer and lyr != parent_group and is_direct_child_of_group(lyr, parent_group)
    ]


def group_direct_raster_layers(map_obj, group_layer):
    return [
        lyr
        for lyr in map_obj.listLayers()
        if lyr != group_layer and is_direct_child_of_group(lyr, group_layer) and lyr.isRasterLayer and not lyr.isGroupLayer
    ]


def find_group(map_obj, group_name):
    matches = [lyr for lyr in map_obj.listLayers() if lyr.isGroupLayer and lyr.name == group_name]
    if not matches:
        available = [layer_long_name(lyr) for lyr in map_obj.listLayers() if lyr.isGroupLayer]
        raise ValueError(f"No se encontro el grupo '{group_name}'. Grupos disponibles: {available}")
    if len(matches) > 1:
        print(f"Advertencia: se encontraron {len(matches)} grupos '{group_name}'. Se usara: {layer_long_name(matches[0])}")
    return matches[0]


def find_or_restore_target_group(map_obj, parent_group):
    expected_long_name = f"{layer_long_name(parent_group)}\\{TARGET_GROUP_NAME}"
    exact_matches = [
        lyr
        for lyr in direct_child_groups(map_obj, parent_group)
        if lyr.name == TARGET_GROUP_NAME or layer_long_name(lyr) == expected_long_name
    ]
    if exact_matches:
        return exact_matches[0]

    candidates = []
    for group in direct_child_groups(map_obj, parent_group):
        raster_children = group_direct_raster_layers(map_obj, group)
        image_children = [lyr for lyr in raster_children if is_image_layer_name(lyr.name)]
        if image_children:
            candidates.append((len(image_children), group))

    if candidates:
        candidates.sort(key=lambda item: item[0], reverse=True)
        target_group = candidates[0][1]
        original_group_name = target_group.name
        target_group.name = TARGET_GROUP_NAME
        print(f"Grupo destino restaurado: {original_group_name} -> {TARGET_GROUP_NAME}")
        return target_group

    available = [layer_long_name(lyr) for lyr in direct_child_groups(map_obj, parent_group)]
    raise ValueError(
        f"No se encontro el subgrupo '{TARGET_GROUP_NAME}' bajo '{PARENT_GROUP_NAME}' "
        f"ni un grupo candidato con imagenes. Subgrupos disponibles: {available}"
    )


def add_raster_to_target_group(map_obj, group_layer, image_path, target_name):
    before_layer_names = {layer_long_name(lyr) for lyr in group_direct_raster_layers(map_obj, group_layer)}
    safe_tmp_stem = re.sub(r"[^A-Za-z0-9_]+", "_", Path(image_path).stem)
    tmp_name = f"tmp_{safe_tmp_stem}"
    tmp_layer_file_path = Path.cwd() / f"{tmp_name}.lyrx"

    arcpy.management.MakeRasterLayer(image_path, tmp_name)
    arcpy.management.SaveToLayerFile(tmp_name, str(tmp_layer_file_path), "ABSOLUTE")
    tmp_layer_file = arcpy.mp.LayerFile(str(tmp_layer_file_path))

    try:
        result = map_obj.addLayerToGroup(group_layer, tmp_layer_file, "TOP")
        added_layer = None

        if isinstance(result, list) and result:
            added_layer = result[0]
        elif result is not None:
            added_layer = result

        if added_layer is None:
            after_layers = group_direct_raster_layers(map_obj, group_layer)
            new_layers = [lyr for lyr in after_layers if layer_long_name(lyr) not in before_layer_names]
            if new_layers:
                added_layer = new_layers[0]

        if added_layer is None:
            target_keys = comparable_layer_keys(target_name)
            for lyr in group_direct_raster_layers(map_obj, group_layer):
                if target_keys.intersection(comparable_layer_keys(lyr.name)):
                    added_layer = lyr
                    break

        if added_layer is not None:
            added_layer.name = target_name

        return added_layer
    finally:
        try:
            arcpy.management.Delete(tmp_name)
        except Exception:
            pass
        try:
            tmp_layer_file_path.unlink(missing_ok=True)
        except Exception:
            pass


def move_layer_to_top_of_group(map_obj, group_layer, layer_to_move):
    current_layers = group_direct_raster_layers(map_obj, group_layer)
    if not current_layers or layer_to_move == current_layers[0]:
        return
    map_obj.moveLayer(current_layers[0], layer_to_move, "BEFORE")


def order_group_layers_newest_first(map_obj, group_layer):
    ordered_layers = sorted(
        group_direct_raster_layers(map_obj, group_layer),
        key=lambda layer: sort_key_newest_first(layer.name),
        reverse=True,
    )
    for layer in reversed(ordered_layers):
        move_layer_to_top_of_group(map_obj, group_layer, layer)


image_paths_to_add = read_loaded_image_paths(LOAD_RESULTS_CSV)
print(f"Imagenes cargadas a revisar en APRX: {len(image_paths_to_add)}")

aprx = arcpy.mp.ArcGISProject(aprx_path)

try:
    maps = aprx.listMaps(map_name)

    if not maps:
        print("No se encontro el mapa")
    else:
        m = maps[0]
        parent_group = find_group(m, PARENT_GROUP_NAME)
        target_group = find_or_restore_target_group(m, parent_group)
        print(f"Grupo padre: {layer_long_name(parent_group)}")
        print(f"Grupo destino: {layer_long_name(target_group)}")

        if not is_direct_child_of_group(target_group, parent_group):
            raise ValueError(f"Grupo destino inesperado: {layer_long_name(target_group)}")

        existing_layers_before = group_direct_raster_layers(m, target_group)
        existing_keys = set()
        for lyr in existing_layers_before:
            existing_keys.update(comparable_layer_keys(lyr.name))
        print(f"Raster directos en '{TARGET_GROUP_NAME}' antes de agregar: {len(existing_layers_before)}")

        added_count = 0
        skipped_count = 0
        renamed_count = 0
        error_count = 0

        # 1. Agregar solo las imagenes nuevas como raster directos dentro de Vuelos Drone PAO > Imagenes Drone.
        for image_path in image_paths_to_add:
            target_name = layer_name_from_path(image_path)
            target_keys = comparable_layer_keys(target_name)

            if ADD_ONLY_MISSING_TO_GROUP and target_keys.intersection(existing_keys):
                print(f"Ya existe en el grupo, se conserva y se omite: {target_name}")
                skipped_count += 1
                continue

            try:
                added_layer = add_raster_to_target_group(m, target_group, image_path, target_name)
                if added_layer is None:
                    print(f"Advertencia: no se pudo confirmar el objeto retornado, se continuara con validacion posterior: {target_name}")
                existing_keys.update(target_keys)
                added_count += 1
                print(f"Agregada al grupo: {target_name}")
            except Exception as exc:
                error_count += 1
                print(f"Error agregando {image_path}: {exc}")

        # 2. Renombrar raster directos al formato corto: YY_MM_DD_Sector, sin prefijo, sin tmp_ y sin .tif.
        for lyr in group_direct_raster_layers(m, target_group):
            try:
                original_name = lyr.name
                new_name = short_layer_name(original_name)
                if new_name != original_name:
                    print(f"Renombrando: {original_name} -> {new_name}")
                    lyr.name = new_name
                    renamed_count += 1
            except Exception as exc:
                error_count += 1
                print(f"Error con capa {lyr.name}: {exc}")

        # 3. Ordenar de mas nueva a mas vieja dentro de Imagenes Drone.
        order_group_layers_newest_first(m, target_group)

        layers_after = group_direct_raster_layers(m, target_group)
        print(f"Raster directos en '{TARGET_GROUP_NAME}' despues de agregar: {len(layers_after)}")
        print(f"Resumen APRX: nuevas_agregadas={added_count}, existentes_conservadas={skipped_count}, renombradas={renamed_count}, errores={error_count}")

        if SAVE_COPY_FOR_REVIEW:
            aprx.saveACopy(APRX_COPY_PATH)
            print(f"Copia de verificacion guardada: {APRX_COPY_PATH}")
        else:
            aprx.save()
            print("Proyecto original guardado")
finally:
    del aprx

Imagenes cargadas a revisar en APRX: 32
Grupo padre: Vuelos Drone PAO
Grupo destino: Vuelos Drone PAO\Imagenes Drone
Raster directos en 'Imagenes Drone' antes de agregar: 468
Agregada al grupo: 26_05_01_Estacion_Cabecera
Agregada al grupo: 26_05_06_Subestacion-El-Mauro-1
Agregada al grupo: 26_05_06_Subestacion-El-Mauro-2
Agregada al grupo: 26_05_06_TORRE_E85_A_E_125
Agregada al grupo: 26_05_10_ED1
Agregada al grupo: 26_05_10_Helipuerto
Agregada al grupo: 26_05_10_Patio-19B-y-Armado
Agregada al grupo: 26_05_10_DME9-PA12-IIFF8
Agregada al grupo: 26_05_07_TORRES_E48_A_E84_PV4
Agregada al grupo: 26_05_10_MonteAranda-NSTC-Km-84p2-a-82p3
Agregada al grupo: 26_05_13_DME9-PA12-IIFF8
Agregada al grupo: 26_05_13_Subestacion-El-Mauro_A_E35
Agregada al grupo: 26_05_13_Subestacion-El-Mauro-1
Agregada al grupo: 26_05_13_EM2_S2
Agregada al grupo: 26_05_13_EBD-1
Agregada al grupo: 26_05_13_ED2
Agregada al grupo: 26_05_13_Subestacion-El-Mauro-2
Agregada al grupo: 26_05_13_EBD-2
Agregada al grupo: 26_05_13_Estacion_Intermedia
Agregada al grupo: 26_05_14_EM3
Agregada al grupo: 26_05_14_Camino_Alternativo_Salamanca
Agregada al grupo: 26_05_14_TORRES_E31_A_E48_PV4-1
Agregada al grupo: 26_05_14_Subestacion-El-Mauro_A_E35
Agregada al grupo: 26_05_15_Helipuerto-1
Agregada al grupo: 26_05_15_Helipuerto-2
Agregada al grupo: 26_05_15_EV1
Agregada al grupo: 26_05_15_Estacion_Cabecera
Agregada al grupo: 26_05_16_TORRES_E48_A_E84_PV4
Agregada al grupo: 26_05_17_EV2
Agregada al grupo: 26_05_17_EDT
Agregada al grupo: 26_05_14_TORRES_E31_A_E48_PV4-2
Agregada al grupo: 26_05_15_EM1
Renombrando: tmp_CL_MLP_PAO_IF_Ortho_26_05_15_EM1 -> 26_05_15_EM1
Renombrando: tmp_CL_MLP_PAO_IF_Ortho_26_05_14_TORRES_E31_A_E48_PV4_2 -> 26_05_14_TORRES_E31_A_E48_PV4_2
Renombrando: tmp_CL_MLP_PAO_IF_Ortho_26_05_17_EDT -> 26_05_17_EDT
Renombrando: tmp_CL_MLP_PAO_IF_Ortho_26_05_17_EV2 -> 26_05_17_EV2
Renombrando: tmp_CL_MLP_PAO_IF_Ortho_26_05_16_TORRES_E48_A_E84_PV4 -> 26_05_16_TORRES_E48_A_E84_PV4
Renombrando: tmp_CL_MLP_PAO_IF_Ortho_26_05_15_Estacion_Cabecera -> 26_05_15_Estacion_Cabecera
Renombrando: tmp_CL_MLP_PAO_IF_Ortho_26_05_15_EV1 -> 26_05_15_EV1
Renombrando: tmp_CL_MLP_PAO_IF_Ortho_26_05_15_Helipuerto_2 -> 26_05_15_Helipuerto_2
Renombrando: tmp_CL_MLP_PAO_IF_Ortho_26_05_15_Helipuerto_1 -> 26_05_15_Helipuerto_1
Renombrando: tmp_CL_MLP_PAO_IF_Ortho_26_05_14_Subestacion_El_Mauro_A_E35 -> 26_05_14_Subestacion_El_Mauro_A_E35
Renombrando: tmp_CL_MLP_PAO_IF_Ortho_26_05_14_TORRES_E31_A_E48_PV4_1 -> 26_05_14_TORRES_E31_A_E48_PV4_1
Renombrando: tmp_CL_MLP_PAO_IF_Ortho_26_05_14_Camino_Alternativo_Salamanca -> 26_05_14_Camino_Alternativo_Salamanca
Renombrando: tmp_CL_MLP_PAO_IF_Ortho_26_05_14_EM3 -> 26_05_14_EM3
Renombrando: tmp_CL_MLP_PAO_IF_Ortho_26_05_13_Estacion_Intermedia -> 26_05_13_Estacion_Intermedia
Renombrando: tmp_CL_MLP_PAO_IF_Ortho_26_05_13_EBD_2 -> 26_05_13_EBD_2
Renombrando: tmp_CL_MLP_PAO_IF_Ortho_26_05_13_Subestacion_El_Mauro_2 -> 26_05_13_Subestacion_El_Mauro_2
Renombrando: tmp_CL_MLP_PAO_IF_Ortho_26_05_13_ED2 -> 26_05_13_ED2
Renombrando: tmp_CL_MLP_PAO_IF_Ortho_26_05_13_EBD_1 -> 26_05_13_EBD_1
Renombrando: tmp_CL_MLP_PAO_IF_Ortho_26_05_13_EM2_S2 -> 26_05_13_EM2_S2
Renombrando: tmp_CL_MLP_PAO_IF_Ortho_26_05_13_Subestacion_El_Mauro_1 -> 26_05_13_Subestacion_El_Mauro_1
Renombrando: tmp_CL_MLP_PAO_IF_Ortho_26_05_13_Subestacion_El_Mauro_A_E35 -> 26_05_13_Subestacion_El_Mauro_A_E35
Renombrando: tmp_CL_MLP_PAO_IF_Ortho_26_05_13_DME9_PA12_IIFF8 -> 26_05_13_DME9_PA12_IIFF8
Renombrando: tmp_CL_MLP_PAO_IF_Ortho_26_05_10_MonteAranda_NSTC_Km_84p2_a_82p3 -> 26_05_10_MonteAranda_NSTC_Km_84p2_a_82p3
Renombrando: tmp_CL_MLP_PAO_IF_Ortho_26_05_07_TORRES_E48_A_E84_PV4 -> 26_05_07_TORRES_E48_A_E84_PV4
Renombrando: tmp_CL_MLP_PAO_IF_Ortho_26_05_10_DME9_PA12_IIFF8 -> 26_05_10_DME9_PA12_IIFF8
Renombrando: tmp_CL_MLP_PAO_IF_Ortho_26_05_10_Patio_19B_y_Armado -> 26_05_10_Patio_19B_y_Armado
Renombrando: tmp_CL_MLP_PAO_IF_Ortho_26_05_10_Helipuerto -> 26_05_10_Helipuerto
Renombrando: tmp_CL_MLP_PAO_IF_Ortho_26_05_10_ED1 -> 26_05_10_ED1
Renombrando: tmp_CL_MLP_PAO_IF_Ortho_26_05_06_TORRE_E85_A_E_125 -> 26_05_06_TORRE_E85_A_E_125
Renombrando: tmp_CL_MLP_PAO_IF_Ortho_26_05_06_Subestacion_El_Mauro_2 -> 26_05_06_Subestacion_El_Mauro_2
Renombrando: tmp_CL_MLP_PAO_IF_Ortho_26_05_06_Subestacion_El_Mauro_1 -> 26_05_06_Subestacion_El_Mauro_1
Renombrando: tmp_CL_MLP_PAO_IF_Ortho_26_05_01_Estacion_Cabecera -> 26_05_01_Estacion_Cabecera
Renombrando: CL_MLP_PAO_IF_Ortho_26_05_09_EV1.tif -> 26_05_09_EV1
Renombrando: CL_MLP_PAO_IF_Ortho_26_05_07_EM3.tif -> 26_05_07_EM3
Renombrando: CL_MLP_PAO_IF_Ortho_26_05_07_EM2_S2.tif -> 26_05_07_EM2_S2
Renombrando: CL_MLP_PAO_IF_Ortho_26_05_07_ED2.tif -> 26_05_07_ED2
Renombrando: CL_MLP_PAO_IF_Ortho_26_05_03_EM3.tif -> 26_05_03_EM3
Renombrando: CL_MLP_PAO_IF_Ortho_26_05_03_ED2.tif -> 26_05_03_ED2
Renombrando: CL_MLP_PAO_IF_Ortho_26_05_02_EM2_S2.tif -> 26_05_02_EM2_S2
Renombrando: CL_MLP_PAO_IF_Ortho_26_05_02_EM2.tif -> 26_05_02_EM2
Renombrando: CL_MLP_PAO_IF_Ortho_26_05_02_ED1.tif -> 26_05_02_ED1
Renombrando: CL_MLP_PAO_IF_Ortho_26_05_01_EV1.tif -> 26_05_01_EV1
Raster directos en 'Imagenes Drone' despues de agregar: 500
Resumen APRX: nuevas_agregadas=32, existentes_conservadas=0, renombradas=42, errores=0
Copia de verificacion guardada: c:\Users\esrlrivero_adm\Documents\Geosupport\amsa-pao-geosupport\APRX\VISOR TERRITORIAL SIG PAO v7_verificacion_carga_imagenes.aprx

In [150]:
from pathlib import PurePath
PurePath(image_paths_to_add[0])

PureWindowsPath('//amssclgis10.ams.gmams.cl/CL_MLP_PAO/Chacay_Drone/26_05/CL_MLP_PAO_IF_Ortho_26_05_01_Estacion_Cabecera.tif')

In [16]:
from pathlib import Path
from datetime import datetime
import csv
import json
import shutil
import arcpy

LOAD_RESULTS_CSV = Path.cwd() / "outputs" / "carga_mosaico" / "20260615_162625" / "01_load_results.csv"
PATH_MOSAIC_DATASET = r"\\amssclgis08.ams.gmams.cl\CL_MLP_PAO\01_Proyectos_ArcGIS\APRX\CL MLP PAO Aereo Image Server_v2\SQLServer-amssclgis06_ArcGIS-Aereo.sde\OWD.CL_MLP_PAO_IF_Ortho_Geosupport"

GEOMETRY_SOURCE = "FEATURE_CLASS_ARCPY"  # FEATURE_CLASS_ARCPY o MOSAIC_DATASET
PATH_FC_FOOTPRINTS = r"\\amssclgis08.ams.gmams.cl\CL_MLP_PAO\02_FGDB\CL_MLP_PAO_v1.gdb\CL_MLP_PAO_06_COMPLEMENTOS\CL_MLP_PAO_Indice_Vuelos_PAO_IMGS_PO"
FOOTPRINT_NAME_FIELD = "Name"

NORMALIZED_OUTPUT_ROOT = Path.cwd() / "outputs" / "normalizacion_footprintV7" 
NORMALIZE_METHOD = "RASTERIO_MASK"
REPLACE_ORIGINALS = False
CREATE_ORIGINAL_BACKUP = True
BUILD_PYRAMIDS_AND_STATS = True

arcpy.env.overwriteOutput = True


def read_loaded_rows(csv_path):
    with csv_path.open("r", encoding="utf-8-sig", newline="") as file:
        rows = csv.DictReader(file)
        return [row for row in rows if row.get("overall_status") == "ok" and row.get("destination_path")]


def quote_sql_text(value):
    return str(value).replace("'", "''")


def name_where_clause(dataset, field_name, name):
    field = arcpy.AddFieldDelimiters(dataset, field_name)
    return f"{field} = '{quote_sql_text(name)}'"


def resolve_geometry_source():
    source = str(GEOMETRY_SOURCE).strip()
    if source in {"FEATURE_CLASS_ARCPY", "FEATURE_CLASS_GEOPANDAS", "MOSAIC_DATASET"}:
        if source == "FEATURE_CLASS_GEOPANDAS":
            # El ambiente ArcGIS Pro puede tener pandas/numpy incompatibles. Usamos ArcPy para leer el FC.
            source = "FEATURE_CLASS_ARCPY"
        return source, PATH_FC_FOOTPRINTS

    if source and source not in {"FEATURE_CLASS_ARCPY", "FEATURE_CLASS_GEOPANDAS", "MOSAIC_DATASET"}:
        return "FEATURE_CLASS_ARCPY", source

    return source, PATH_FC_FOOTPRINTS


def raster_clip_output_path(source_path, output_root):
    source = Path(source_path)
    datastore_parent = source.parent.name
    output_dir = output_root / datastore_parent
    output_dir.mkdir(parents=True, exist_ok=True)
    return output_dir / source.name


def arcpy_geometry_to_geojson_geometry(geometry):
    if hasattr(geometry, "__geo_interface__"):
        return geometry.__geo_interface__
    converted = arcpy.AsShape(json.loads(geometry.JSON), True)
    if hasattr(converted, "__geo_interface__"):
        return converted.__geo_interface__
    raise RuntimeError("No se pudo convertir la geometria ArcPy a GeoJSON")


def load_footprints_index(feature_class, name_field):
    if not feature_class:
        raise ValueError("PATH_FC_FOOTPRINTS esta vacio. Define la ruta al feature class de footprints.")

    fields = [field.name for field in arcpy.ListFields(feature_class)]
    if name_field not in fields:
        raise ValueError(f"El campo '{name_field}' no existe en {feature_class}. Campos disponibles: {fields}")

    index = {}
    duplicates = set()
    with arcpy.da.SearchCursor(feature_class, [name_field, "SHAPE@"]) as cursor:
        for name, geometry in cursor:
            if not name or not geometry:
                continue
            key = str(name).lower()
            if key in index:
                duplicates.add(str(name))
            index.setdefault(key, []).append(geometry)

    if duplicates:
        print(f"Advertencia: hay nombres duplicados en footprints: {sorted(duplicates)[:10]}")
    if not index:
        raise RuntimeError(f"No se encontraron geometrías en {feature_class}")

    print(f"Footprints cargados con ArcPy: {sum(len(v) for v in index.values())} desde {feature_class}")
    return index


def footprint_geometry_from_index(footprints_index, raster_name, target_spatial_reference):
    matches = footprints_index.get(str(raster_name).lower(), [])
    if len(matches) != 1:
        raise RuntimeError(f"Footprint esperado 1 en feature class, encontrado {len(matches)}, Name={raster_name}")

    geometry = matches[0]
    if target_spatial_reference and geometry.spatialReference and geometry.spatialReference.factoryCode != target_spatial_reference.factoryCode:
        geometry = geometry.projectAs(target_spatial_reference)

    return arcpy_geometry_to_geojson_geometry(geometry)


def selected_footprint_geometry_from_mosaic(mosaic_dataset, raster_name, target_spatial_reference):
    layer_name = f"footprint_{abs(hash(raster_name))}"
    where_clause = name_where_clause(mosaic_dataset, "Name", raster_name)
    arcpy.management.MakeFeatureLayer(mosaic_dataset, layer_name, where_clause)
    try:
        count = int(arcpy.management.GetCount(layer_name).getOutput(0))
        if count != 1:
            raise RuntimeError(f"Footprint esperado 1, encontrado {count}, Name={raster_name}")

        with arcpy.da.SearchCursor(layer_name, ["SHAPE@"]) as cursor:
            geometry = next(cursor)[0]

        if target_spatial_reference and geometry.spatialReference.factoryCode != target_spatial_reference.factoryCode:
            geometry = geometry.projectAs(target_spatial_reference)

        return arcpy_geometry_to_geojson_geometry(geometry)
    finally:
        arcpy.management.Delete(layer_name)


def normalize_with_rasterio_mask(source_path, footprint_geometry, output_path):
    import rasterio
    from rasterio.mask import mask

    with rasterio.open(source_path) as src:
        masked_data, out_transform = mask(src, [footprint_geometry], crop=True, filled=False)
        profile = src.profile.copy()
        profile.update(
            driver="GTiff",
            height=masked_data.shape[1],
            width=masked_data.shape[2],
            transform=out_transform,
            compress="LZW",
            BIGTIFF="IF_SAFER",
        )

        if src.count == 3 and src.nodata is None:
            rgb = masked_data.filled(0)
            alpha = (~masked_data.mask.all(axis=0)).astype("uint8") * 255
            profile.update(count=4, dtype=rgb.dtype, nodata=None)
            with rasterio.open(output_path, "w", **profile) as dst:
                dst.write(rgb, indexes=[1, 2, 3])
                dst.write(alpha, indexes=4)
                dst.colorinterp = (
                    rasterio.enums.ColorInterp.red,
                    rasterio.enums.ColorInterp.green,
                    rasterio.enums.ColorInterp.blue,
                    rasterio.enums.ColorInterp.alpha,
                )
        else:
            nodata_value = src.nodata if src.nodata is not None else 0
            data = masked_data.filled(nodata_value)
            profile.update(nodata=nodata_value)
            with rasterio.open(output_path, "w", **profile) as dst:
                dst.write(data)
                if src.colorinterp:
                    dst.colorinterp = src.colorinterp


def normalize_raster_by_footprint(source_path, raster_name, output_path, footprints_index=None):
    raster_sr = arcpy.Describe(source_path).spatialReference

    if ACTIVE_GEOMETRY_SOURCE == "FEATURE_CLASS_ARCPY":
        footprint_geometry = footprint_geometry_from_index(footprints_index, raster_name, raster_sr)
    elif ACTIVE_GEOMETRY_SOURCE == "MOSAIC_DATASET":
        footprint_geometry = selected_footprint_geometry_from_mosaic(PATH_MOSAIC_DATASET, raster_name, raster_sr)
    else:
        raise ValueError(f"GEOMETRY_SOURCE no soportado: {GEOMETRY_SOURCE} / activo: {ACTIVE_GEOMETRY_SOURCE}")

    normalize_with_rasterio_mask(source_path, footprint_geometry, output_path)

    if BUILD_PYRAMIDS_AND_STATS:
        arcpy.management.BuildPyramidsandStatistics(str(output_path))


def replace_original_with_backup(original_path, normalized_path):
    original = Path(original_path)
    normalized = Path(normalized_path)
    backup = original.with_suffix(original.suffix + ".bak_original")

    if CREATE_ORIGINAL_BACKUP and not backup.exists():
        shutil.copy2(original, backup)

    shutil.copy2(normalized, original)
    if BUILD_PYRAMIDS_AND_STATS:
        arcpy.management.BuildPyramidsandStatistics(str(original))
    return backup


rows = read_loaded_rows(LOAD_RESULTS_CSV)
NORMALIZED_OUTPUT_ROOT.mkdir(parents=True, exist_ok=True)
ACTIVE_GEOMETRY_SOURCE, ACTIVE_FOOTPRINTS_PATH = resolve_geometry_source()

footprints_index = None
if ACTIVE_GEOMETRY_SOURCE == "FEATURE_CLASS_ARCPY":
    footprints_index = load_footprints_index(ACTIVE_FOOTPRINTS_PATH, FOOTPRINT_NAME_FIELD)

print(f"Imagenes a normalizar por footprint: {len(rows)}")
print(f"Metodo: {NORMALIZE_METHOD}")
print(f"Fuente geometria: {ACTIVE_GEOMETRY_SOURCE}")
print(f"Feature footprints: {ACTIVE_FOOTPRINTS_PATH}")
print(f"Salida de revision: {NORMALIZED_OUTPUT_ROOT}")
print(f"Reemplazar originales: {REPLACE_ORIGINALS}")

results = []
for row in rows:
    raster_name = row["Name"]
    source_path = row["destination_path"]
    output_path = raster_clip_output_path(source_path, NORMALIZED_OUTPUT_ROOT)

    item = {
        "Name": raster_name,
        "source_path": source_path,
        "normalized_path": str(output_path),
        "method": NORMALIZE_METHOD,
        "geometry_source": ACTIVE_GEOMETRY_SOURCE,
        "footprints_path": ACTIVE_FOOTPRINTS_PATH,
        "replace_original": REPLACE_ORIGINALS,
        "status": "pending",
        "error": "",
        "backup_path": "",
    }

    try:
        if not Path(source_path).exists():
            raise FileNotFoundError(source_path)

        normalize_raster_by_footprint(source_path, raster_name, output_path, footprints_index)

        if REPLACE_ORIGINALS:
            backup = replace_original_with_backup(source_path, output_path)
            item["backup_path"] = str(backup)
            item["status"] = "normalized_and_replaced"
        else:
            item["status"] = "normalized_for_review"

        print(f"OK {raster_name} -> {output_path}")
    except Exception as exc:
        item["status"] = "error"
        item["error"] = str(exc)
        print(f"ERROR {raster_name}: {exc}")

    results.append(item)
    

summary_csv = NORMALIZED_OUTPUT_ROOT / "00_normalizacion_footprint_resultados.csv"
with summary_csv.open("w", encoding="utf-8-sig", newline="") as file:
    writer = csv.DictWriter(file, fieldnames=list(results[0].keys()) if results else ["Name", "status"])
    writer.writeheader()
    writer.writerows(results)

status_counts = {}
for item in results:
    status_counts[item["status"]] = status_counts.get(item["status"], 0) + 1

print("Resumen normalizacion:", status_counts)
print(f"CSV resultados: {summary_csv}")

Advertencia: hay nombres duplicados en footprints: ['CL_MLP_PAO_IF_Ortho_26_04_17_EB3', 'CL_MLP_PAO_IF_Ortho_26_04_18_Helipuerto', 'CL_MLP_PAO_IF_Ortho_26_04_22_EB3', 'CL_MLP_PAO_IF_Ortho_26_04_23_TORRES_E35_A_E48', 'CL_MLP_PAO_IF_Ortho_26_04_24_Patio-19B-y-Armado', 'CL_MLP_PAO_IF_Ortho_26_04_25_EBD', 'CL_MLP_PAO_IF_Ortho_26_04_25_Pozos_PRP']
Footprints cargados con ArcPy: 481 desde \\amssclgis08.ams.gmams.cl\CL_MLP_PAO\02_FGDB\CL_MLP_PAO_v1.gdb\CL_MLP_PAO_06_COMPLEMENTOS\CL_MLP_PAO_Indice_Vuelos_PAO_IMGS_PO
Imagenes a normalizar por footprint: 32
Metodo: RASTERIO_MASK
Fuente geometria: FEATURE_CLASS_ARCPY
Feature footprints: \\amssclgis08.ams.gmams.cl\CL_MLP_PAO\02_FGDB\CL_MLP_PAO_v1.gdb\CL_MLP_PAO_06_COMPLEMENTOS\CL_MLP_PAO_Indice_Vuelos_PAO_IMGS_PO
Salida de revision: c:\Users\esrlrivero_adm\Documents\Geosupport\amsa-pao-geosupport\outputs\normalizacion_footprintV7
Reemplazar originales: False

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.2 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\ipykernel_launcher.py", line 17, in <module>
    app.launch_new_instance()
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\traitlets\config\application.py", line 982, in launch_instance
    app.start()
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\ipykernel\kernelapp.py", line 712, in start
    self.io_loop.start()
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\tornado\platform\asyncio.py", line 215, in start
    self.asyncio_loop.run_forever()
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\asyncio\base_events.py", line 601, in run_forever
    self._run_once()
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\asyncio\base_events.py", line 1905, in _run_once
    handle._run()
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\ipykernel\kernelbase.py", line 510, in dispatch_queue
    await self.process_one()
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\ipykernel\kernelbase.py", line 499, in process_one
    await dispatch(*args)
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\ipykernel\kernelbase.py", line 406, in dispatch_shell
    await result
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\ipykernel\kernelbase.py", line 730, in execute_request
    reply_content = await reply_content
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\ipykernel\ipkernel.py", line 383, in do_execute
    res = shell.run_cell(
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\ipykernel\zmqshell.py", line 528, in run_cell
    return super().run_cell(*args, **kwargs)
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\IPython\core\interactiveshell.py", line 2975, in run_cell
    result = self._run_cell(
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\IPython\core\interactiveshell.py", line 3030, in _run_cell
    return runner(coro)
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\IPython\core\async_helpers.py", line 78, in _pseudo_sync_runner
    coro.send(None)
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\IPython\core\interactiveshell.py", line 3257, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\IPython\core\interactiveshell.py", line 3473, in run_ast_nodes
    if (await self.run_code(code, result,  async_=asy)):
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\IPython\core\interactiveshell.py", line 3553, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "C:\Users\esrlrivero_adm\AppData\Local\Temp\ipykernel_22212\1835472039.py", line 237, in <cell line: 215>
    normalize_raster_by_footprint(source_path, raster_name, output_path, footprints_index)
  File "C:\Users\esrlrivero_adm\AppData\Local\Temp\ipykernel_22212\1835472039.py", line 182, in normalize_raster_by_footprint
    arcpy.management.BuildPyramidsandStatistics(str(output_path))
  File "C:\Program Files\ArcGIS\Pro\Resources\ArcPy\arcpy\management.py", line 19519, in BuildPyramidsandStatistics
    retval = convertArcObjectToPythonObject(gp.BuildPyramidsandStatistics_management(*gp_fixargs((in_workspace, include_subdirectories, build_pyramids, calculate_statistics, BUILD_ON_SOURCE, block_field, estimate_statistics, x_skip_factor, y_skip_factor, ignore_values, pyramid_level, SKIP_FIRST, resample_technique, compression_type, compression_quality, skip_existing, where_clause, sips_mode), True)))
  File "C:\Program Files\ArcGIS\Pro\Resources\ArcPy\arcpy\geoprocessing\_base.py", line 520, in <lambda>
    return lambda *args: val(*gp_fixargs(args, True))
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\pyarrow\__init__.py", line 65, in <module>
    import pyarrow.lib as _lib

AttributeError: _ARRAY_API not found

OK CL_MLP_PAO_IF_Ortho_26_05_01_Estacion_Cabecera -> c:\Users\esrlrivero_adm\Documents\Geosupport\amsa-pao-geosupport\outputs\normalizacion_footprintV7\26_05\CL_MLP_PAO_IF_Ortho_26_05_01_Estacion_Cabecera.tif

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.2 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\ipykernel_launcher.py", line 17, in <module>
    app.launch_new_instance()
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\traitlets\config\application.py", line 982, in launch_instance
    app.start()
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\ipykernel\kernelapp.py", line 712, in start
    self.io_loop.start()
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\tornado\platform\asyncio.py", line 215, in start
    self.asyncio_loop.run_forever()
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\asyncio\base_events.py", line 601, in run_forever
    self._run_once()
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\asyncio\base_events.py", line 1905, in _run_once
    handle._run()
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\ipykernel\kernelbase.py", line 510, in dispatch_queue
    await self.process_one()
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\ipykernel\kernelbase.py", line 499, in process_one
    await dispatch(*args)
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\ipykernel\kernelbase.py", line 406, in dispatch_shell
    await result
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\ipykernel\kernelbase.py", line 730, in execute_request
    reply_content = await reply_content
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\ipykernel\ipkernel.py", line 383, in do_execute
    res = shell.run_cell(
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\ipykernel\zmqshell.py", line 528, in run_cell
    return super().run_cell(*args, **kwargs)
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\IPython\core\interactiveshell.py", line 2975, in run_cell
    result = self._run_cell(
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\IPython\core\interactiveshell.py", line 3030, in _run_cell
    return runner(coro)
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\IPython\core\async_helpers.py", line 78, in _pseudo_sync_runner
    coro.send(None)
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\IPython\core\interactiveshell.py", line 3257, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\IPython\core\interactiveshell.py", line 3473, in run_ast_nodes
    if (await self.run_code(code, result,  async_=asy)):
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\IPython\core\interactiveshell.py", line 3553, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "C:\Users\esrlrivero_adm\AppData\Local\Temp\ipykernel_22212\1835472039.py", line 237, in <cell line: 215>
    normalize_raster_by_footprint(source_path, raster_name, output_path, footprints_index)
  File "C:\Users\esrlrivero_adm\AppData\Local\Temp\ipykernel_22212\1835472039.py", line 182, in normalize_raster_by_footprint
    arcpy.management.BuildPyramidsandStatistics(str(output_path))
  File "C:\Program Files\ArcGIS\Pro\Resources\ArcPy\arcpy\management.py", line 19519, in BuildPyramidsandStatistics
    retval = convertArcObjectToPythonObject(gp.BuildPyramidsandStatistics_management(*gp_fixargs((in_workspace, include_subdirectories, build_pyramids, calculate_statistics, BUILD_ON_SOURCE, block_field, estimate_statistics, x_skip_factor, y_skip_factor, ignore_values, pyramid_level, SKIP_FIRST, resample_technique, compression_type, compression_quality, skip_existing, where_clause, sips_mode), True)))
  File "C:\Program Files\ArcGIS\Pro\Resources\ArcPy\arcpy\geoprocessing\_base.py", line 520, in <lambda>
    return lambda *args: val(*gp_fixargs(args, True))
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\pyarrow\__init__.py", line 65, in <module>
    import pyarrow.lib as _lib

AttributeError: _ARRAY_API not found

OK CL_MLP_PAO_IF_Ortho_26_05_06_Subestacion-El-Mauro-1 -> c:\Users\esrlrivero_adm\Documents\Geosupport\amsa-pao-geosupport\outputs\normalizacion_footprintV7\26_05\CL_MLP_PAO_IF_Ortho_26_05_06_Subestacion-El-Mauro-1.tif

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.2 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\ipykernel_launcher.py", line 17, in <module>
    app.launch_new_instance()
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\traitlets\config\application.py", line 982, in launch_instance
    app.start()
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\ipykernel\kernelapp.py", line 712, in start
    self.io_loop.start()
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\tornado\platform\asyncio.py", line 215, in start
    self.asyncio_loop.run_forever()
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\asyncio\base_events.py", line 601, in run_forever
    self._run_once()
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\asyncio\base_events.py", line 1905, in _run_once
    handle._run()
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\ipykernel\kernelbase.py", line 510, in dispatch_queue
    await self.process_one()
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\ipykernel\kernelbase.py", line 499, in process_one
    await dispatch(*args)
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\ipykernel\kernelbase.py", line 406, in dispatch_shell
    await result
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\ipykernel\kernelbase.py", line 730, in execute_request
    reply_content = await reply_content
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\ipykernel\ipkernel.py", line 383, in do_execute
    res = shell.run_cell(
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\ipykernel\zmqshell.py", line 528, in run_cell
    return super().run_cell(*args, **kwargs)
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\IPython\core\interactiveshell.py", line 2975, in run_cell
    result = self._run_cell(
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\IPython\core\interactiveshell.py", line 3030, in _run_cell
    return runner(coro)
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\IPython\core\async_helpers.py", line 78, in _pseudo_sync_runner
    coro.send(None)
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\IPython\core\interactiveshell.py", line 3257, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\IPython\core\interactiveshell.py", line 3473, in run_ast_nodes
    if (await self.run_code(code, result,  async_=asy)):
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\IPython\core\interactiveshell.py", line 3553, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "C:\Users\esrlrivero_adm\AppData\Local\Temp\ipykernel_22212\1835472039.py", line 237, in <cell line: 215>
    normalize_raster_by_footprint(source_path, raster_name, output_path, footprints_index)
  File "C:\Users\esrlrivero_adm\AppData\Local\Temp\ipykernel_22212\1835472039.py", line 182, in normalize_raster_by_footprint
    arcpy.management.BuildPyramidsandStatistics(str(output_path))
  File "C:\Program Files\ArcGIS\Pro\Resources\ArcPy\arcpy\management.py", line 19519, in BuildPyramidsandStatistics
    retval = convertArcObjectToPythonObject(gp.BuildPyramidsandStatistics_management(*gp_fixargs((in_workspace, include_subdirectories, build_pyramids, calculate_statistics, BUILD_ON_SOURCE, block_field, estimate_statistics, x_skip_factor, y_skip_factor, ignore_values, pyramid_level, SKIP_FIRST, resample_technique, compression_type, compression_quality, skip_existing, where_clause, sips_mode), True)))
  File "C:\Program Files\ArcGIS\Pro\Resources\ArcPy\arcpy\geoprocessing\_base.py", line 520, in <lambda>
    return lambda *args: val(*gp_fixargs(args, True))
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\pyarrow\__init__.py", line 65, in <module>
    import pyarrow.lib as _lib

AttributeError: _ARRAY_API not found

OK CL_MLP_PAO_IF_Ortho_26_05_06_Subestacion-El-Mauro-2 -> c:\Users\esrlrivero_adm\Documents\Geosupport\amsa-pao-geosupport\outputs\normalizacion_footprintV7\26_05\CL_MLP_PAO_IF_Ortho_26_05_06_Subestacion-El-Mauro-2.tif

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.2 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\ipykernel_launcher.py", line 17, in <module>
    app.launch_new_instance()
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\traitlets\config\application.py", line 982, in launch_instance
    app.start()
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\ipykernel\kernelapp.py", line 712, in start
    self.io_loop.start()
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\tornado\platform\asyncio.py", line 215, in start
    self.asyncio_loop.run_forever()
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\asyncio\base_events.py", line 601, in run_forever
    self._run_once()
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\asyncio\base_events.py", line 1905, in _run_once
    handle._run()
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\ipykernel\kernelbase.py", line 510, in dispatch_queue
    await self.process_one()
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\ipykernel\kernelbase.py", line 499, in process_one
    await dispatch(*args)
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\ipykernel\kernelbase.py", line 406, in dispatch_shell
    await result
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\ipykernel\kernelbase.py", line 730, in execute_request
    reply_content = await reply_content
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\ipykernel\ipkernel.py", line 383, in do_execute
    res = shell.run_cell(
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\ipykernel\zmqshell.py", line 528, in run_cell
    return super().run_cell(*args, **kwargs)
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\IPython\core\interactiveshell.py", line 2975, in run_cell
    result = self._run_cell(
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\IPython\core\interactiveshell.py", line 3030, in _run_cell
    return runner(coro)
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\IPython\core\async_helpers.py", line 78, in _pseudo_sync_runner
    coro.send(None)
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\IPython\core\interactiveshell.py", line 3257, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\IPython\core\interactiveshell.py", line 3473, in run_ast_nodes
    if (await self.run_code(code, result,  async_=asy)):
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\IPython\core\interactiveshell.py", line 3553, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "C:\Users\esrlrivero_adm\AppData\Local\Temp\ipykernel_22212\1835472039.py", line 237, in <cell line: 215>
    normalize_raster_by_footprint(source_path, raster_name, output_path, footprints_index)
  File "C:\Users\esrlrivero_adm\AppData\Local\Temp\ipykernel_22212\1835472039.py", line 182, in normalize_raster_by_footprint
    arcpy.management.BuildPyramidsandStatistics(str(output_path))
  File "C:\Program Files\ArcGIS\Pro\Resources\ArcPy\arcpy\management.py", line 19519, in BuildPyramidsandStatistics
    retval = convertArcObjectToPythonObject(gp.BuildPyramidsandStatistics_management(*gp_fixargs((in_workspace, include_subdirectories, build_pyramids, calculate_statistics, BUILD_ON_SOURCE, block_field, estimate_statistics, x_skip_factor, y_skip_factor, ignore_values, pyramid_level, SKIP_FIRST, resample_technique, compression_type, compression_quality, skip_existing, where_clause, sips_mode), True)))
  File "C:\Program Files\ArcGIS\Pro\Resources\ArcPy\arcpy\geoprocessing\_base.py", line 520, in <lambda>
    return lambda *args: val(*gp_fixargs(args, True))
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\pyarrow\__init__.py", line 65, in <module>
    import pyarrow.lib as _lib

AttributeError: _ARRAY_API not found

OK CL_MLP_PAO_IF_Ortho_26_05_06_TORRE_E85_A_E_125 -> c:\Users\esrlrivero_adm\Documents\Geosupport\amsa-pao-geosupport\outputs\normalizacion_footprintV7\26_05\CL_MLP_PAO_IF_Ortho_26_05_06_TORRE_E85_A_E_125.tif

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.2 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\ipykernel_launcher.py", line 17, in <module>
    app.launch_new_instance()
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\traitlets\config\application.py", line 982, in launch_instance
    app.start()
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\ipykernel\kernelapp.py", line 712, in start
    self.io_loop.start()
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\tornado\platform\asyncio.py", line 215, in start
    self.asyncio_loop.run_forever()
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\asyncio\base_events.py", line 601, in run_forever
    self._run_once()
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\asyncio\base_events.py", line 1905, in _run_once
    handle._run()
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\ipykernel\kernelbase.py", line 510, in dispatch_queue
    await self.process_one()
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\ipykernel\kernelbase.py", line 499, in process_one
    await dispatch(*args)
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\ipykernel\kernelbase.py", line 406, in dispatch_shell
    await result
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\ipykernel\kernelbase.py", line 730, in execute_request
    reply_content = await reply_content
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\ipykernel\ipkernel.py", line 383, in do_execute
    res = shell.run_cell(
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\ipykernel\zmqshell.py", line 528, in run_cell
    return super().run_cell(*args, **kwargs)
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\IPython\core\interactiveshell.py", line 2975, in run_cell
    result = self._run_cell(
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\IPython\core\interactiveshell.py", line 3030, in _run_cell
    return runner(coro)
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\IPython\core\async_helpers.py", line 78, in _pseudo_sync_runner
    coro.send(None)
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\IPython\core\interactiveshell.py", line 3257, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\IPython\core\interactiveshell.py", line 3473, in run_ast_nodes
    if (await self.run_code(code, result,  async_=asy)):
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\IPython\core\interactiveshell.py", line 3553, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "C:\Users\esrlrivero_adm\AppData\Local\Temp\ipykernel_22212\1835472039.py", line 237, in <cell line: 215>
    normalize_raster_by_footprint(source_path, raster_name, output_path, footprints_index)
  File "C:\Users\esrlrivero_adm\AppData\Local\Temp\ipykernel_22212\1835472039.py", line 182, in normalize_raster_by_footprint
    arcpy.management.BuildPyramidsandStatistics(str(output_path))
  File "C:\Program Files\ArcGIS\Pro\Resources\ArcPy\arcpy\management.py", line 19519, in BuildPyramidsandStatistics
    retval = convertArcObjectToPythonObject(gp.BuildPyramidsandStatistics_management(*gp_fixargs((in_workspace, include_subdirectories, build_pyramids, calculate_statistics, BUILD_ON_SOURCE, block_field, estimate_statistics, x_skip_factor, y_skip_factor, ignore_values, pyramid_level, SKIP_FIRST, resample_technique, compression_type, compression_quality, skip_existing, where_clause, sips_mode), True)))
  File "C:\Program Files\ArcGIS\Pro\Resources\ArcPy\arcpy\geoprocessing\_base.py", line 520, in <lambda>
    return lambda *args: val(*gp_fixargs(args, True))
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\pyarrow\__init__.py", line 65, in <module>
    import pyarrow.lib as _lib

AttributeError: _ARRAY_API not found

OK CL_MLP_PAO_IF_Ortho_26_05_10_ED1 -> c:\Users\esrlrivero_adm\Documents\Geosupport\amsa-pao-geosupport\outputs\normalizacion_footprintV7\26_05\CL_MLP_PAO_IF_Ortho_26_05_10_ED1.tif

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.2 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\ipykernel_launcher.py", line 17, in <module>
    app.launch_new_instance()
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\traitlets\config\application.py", line 982, in launch_instance
    app.start()
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\ipykernel\kernelapp.py", line 712, in start
    self.io_loop.start()
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\tornado\platform\asyncio.py", line 215, in start
    self.asyncio_loop.run_forever()
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\asyncio\base_events.py", line 601, in run_forever
    self._run_once()
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\asyncio\base_events.py", line 1905, in _run_once
    handle._run()
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\ipykernel\kernelbase.py", line 510, in dispatch_queue
    await self.process_one()
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\ipykernel\kernelbase.py", line 499, in process_one
    await dispatch(*args)
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\ipykernel\kernelbase.py", line 406, in dispatch_shell
    await result
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\ipykernel\kernelbase.py", line 730, in execute_request
    reply_content = await reply_content
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\ipykernel\ipkernel.py", line 383, in do_execute
    res = shell.run_cell(
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\ipykernel\zmqshell.py", line 528, in run_cell
    return super().run_cell(*args, **kwargs)
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\IPython\core\interactiveshell.py", line 2975, in run_cell
    result = self._run_cell(
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\IPython\core\interactiveshell.py", line 3030, in _run_cell
    return runner(coro)
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\IPython\core\async_helpers.py", line 78, in _pseudo_sync_runner
    coro.send(None)
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\IPython\core\interactiveshell.py", line 3257, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\IPython\core\interactiveshell.py", line 3473, in run_ast_nodes
    if (await self.run_code(code, result,  async_=asy)):
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\IPython\core\interactiveshell.py", line 3553, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "C:\Users\esrlrivero_adm\AppData\Local\Temp\ipykernel_22212\1835472039.py", line 237, in <cell line: 215>
    normalize_raster_by_footprint(source_path, raster_name, output_path, footprints_index)
  File "C:\Users\esrlrivero_adm\AppData\Local\Temp\ipykernel_22212\1835472039.py", line 182, in normalize_raster_by_footprint
    arcpy.management.BuildPyramidsandStatistics(str(output_path))
  File "C:\Program Files\ArcGIS\Pro\Resources\ArcPy\arcpy\management.py", line 19519, in BuildPyramidsandStatistics
    retval = convertArcObjectToPythonObject(gp.BuildPyramidsandStatistics_management(*gp_fixargs((in_workspace, include_subdirectories, build_pyramids, calculate_statistics, BUILD_ON_SOURCE, block_field, estimate_statistics, x_skip_factor, y_skip_factor, ignore_values, pyramid_level, SKIP_FIRST, resample_technique, compression_type, compression_quality, skip_existing, where_clause, sips_mode), True)))
  File "C:\Program Files\ArcGIS\Pro\Resources\ArcPy\arcpy\geoprocessing\_base.py", line 520, in <lambda>
    return lambda *args: val(*gp_fixargs(args, True))
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\pyarrow\__init__.py", line 65, in <module>
    import pyarrow.lib as _lib

AttributeError: _ARRAY_API not found

OK CL_MLP_PAO_IF_Ortho_26_05_10_Helipuerto -> c:\Users\esrlrivero_adm\Documents\Geosupport\amsa-pao-geosupport\outputs\normalizacion_footprintV7\26_05\CL_MLP_PAO_IF_Ortho_26_05_10_Helipuerto.tif

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.2 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\ipykernel_launcher.py", line 17, in <module>
    app.launch_new_instance()
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\traitlets\config\application.py", line 982, in launch_instance
    app.start()
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\ipykernel\kernelapp.py", line 712, in start
    self.io_loop.start()
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\tornado\platform\asyncio.py", line 215, in start
    self.asyncio_loop.run_forever()
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\asyncio\base_events.py", line 601, in run_forever
    self._run_once()
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\asyncio\base_events.py", line 1905, in _run_once
    handle._run()
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\ipykernel\kernelbase.py", line 510, in dispatch_queue
    await self.process_one()
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\ipykernel\kernelbase.py", line 499, in process_one
    await dispatch(*args)
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\ipykernel\kernelbase.py", line 406, in dispatch_shell
    await result
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\ipykernel\kernelbase.py", line 730, in execute_request
    reply_content = await reply_content
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\ipykernel\ipkernel.py", line 383, in do_execute
    res = shell.run_cell(
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\ipykernel\zmqshell.py", line 528, in run_cell
    return super().run_cell(*args, **kwargs)
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\IPython\core\interactiveshell.py", line 2975, in run_cell
    result = self._run_cell(
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\IPython\core\interactiveshell.py", line 3030, in _run_cell
    return runner(coro)
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\IPython\core\async_helpers.py", line 78, in _pseudo_sync_runner
    coro.send(None)
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\IPython\core\interactiveshell.py", line 3257, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\IPython\core\interactiveshell.py", line 3473, in run_ast_nodes
    if (await self.run_code(code, result,  async_=asy)):
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\IPython\core\interactiveshell.py", line 3553, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "C:\Users\esrlrivero_adm\AppData\Local\Temp\ipykernel_22212\1835472039.py", line 237, in <cell line: 215>
    normalize_raster_by_footprint(source_path, raster_name, output_path, footprints_index)
  File "C:\Users\esrlrivero_adm\AppData\Local\Temp\ipykernel_22212\1835472039.py", line 182, in normalize_raster_by_footprint
    arcpy.management.BuildPyramidsandStatistics(str(output_path))
  File "C:\Program Files\ArcGIS\Pro\Resources\ArcPy\arcpy\management.py", line 19519, in BuildPyramidsandStatistics
    retval = convertArcObjectToPythonObject(gp.BuildPyramidsandStatistics_management(*gp_fixargs((in_workspace, include_subdirectories, build_pyramids, calculate_statistics, BUILD_ON_SOURCE, block_field, estimate_statistics, x_skip_factor, y_skip_factor, ignore_values, pyramid_level, SKIP_FIRST, resample_technique, compression_type, compression_quality, skip_existing, where_clause, sips_mode), True)))
  File "C:\Program Files\ArcGIS\Pro\Resources\ArcPy\arcpy\geoprocessing\_base.py", line 520, in <lambda>
    return lambda *args: val(*gp_fixargs(args, True))
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\pyarrow\__init__.py", line 65, in <module>
    import pyarrow.lib as _lib

AttributeError: _ARRAY_API not found

OK CL_MLP_PAO_IF_Ortho_26_05_10_Patio-19B-y-Armado -> c:\Users\esrlrivero_adm\Documents\Geosupport\amsa-pao-geosupport\outputs\normalizacion_footprintV7\26_05\CL_MLP_PAO_IF_Ortho_26_05_10_Patio-19B-y-Armado.tif
ERROR CL_MLP_PAO_IF_Ortho_26_05_10_DME9-PA12-IIFF8: CL_MLP_PAO_IF_Ortho_26_05_10_DME9-PA12-IIFF8.tif: Currently, PHOTOMETRIC=YCBCR requires COMPRESS=JPEG
ERROR CL_MLP_PAO_IF_Ortho_26_05_07_TORRES_E48_A_E84_PV4: Unable to allocate 11.7 GiB for an array with shape (4, 40844, 76769) and data type bool

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.2 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\ipykernel_launcher.py", line 17, in <module>
    app.launch_new_instance()
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\traitlets\config\application.py", line 982, in launch_instance
    app.start()
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\ipykernel\kernelapp.py", line 712, in start
    self.io_loop.start()
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\tornado\platform\asyncio.py", line 215, in start
    self.asyncio_loop.run_forever()
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\asyncio\base_events.py", line 601, in run_forever
    self._run_once()
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\asyncio\base_events.py", line 1905, in _run_once
    handle._run()
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\ipykernel\kernelbase.py", line 510, in dispatch_queue
    await self.process_one()
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\ipykernel\kernelbase.py", line 499, in process_one
    await dispatch(*args)
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\ipykernel\kernelbase.py", line 406, in dispatch_shell
    await result
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\ipykernel\kernelbase.py", line 730, in execute_request
    reply_content = await reply_content
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\ipykernel\ipkernel.py", line 383, in do_execute
    res = shell.run_cell(
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\ipykernel\zmqshell.py", line 528, in run_cell
    return super().run_cell(*args, **kwargs)
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\IPython\core\interactiveshell.py", line 2975, in run_cell
    result = self._run_cell(
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\IPython\core\interactiveshell.py", line 3030, in _run_cell
    return runner(coro)
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\IPython\core\async_helpers.py", line 78, in _pseudo_sync_runner
    coro.send(None)
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\IPython\core\interactiveshell.py", line 3257, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\IPython\core\interactiveshell.py", line 3473, in run_ast_nodes
    if (await self.run_code(code, result,  async_=asy)):
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\IPython\core\interactiveshell.py", line 3553, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "C:\Users\esrlrivero_adm\AppData\Local\Temp\ipykernel_22212\1835472039.py", line 237, in <cell line: 215>
    normalize_raster_by_footprint(source_path, raster_name, output_path, footprints_index)
  File "C:\Users\esrlrivero_adm\AppData\Local\Temp\ipykernel_22212\1835472039.py", line 182, in normalize_raster_by_footprint
    arcpy.management.BuildPyramidsandStatistics(str(output_path))
  File "C:\Program Files\ArcGIS\Pro\Resources\ArcPy\arcpy\management.py", line 19519, in BuildPyramidsandStatistics
    retval = convertArcObjectToPythonObject(gp.BuildPyramidsandStatistics_management(*gp_fixargs((in_workspace, include_subdirectories, build_pyramids, calculate_statistics, BUILD_ON_SOURCE, block_field, estimate_statistics, x_skip_factor, y_skip_factor, ignore_values, pyramid_level, SKIP_FIRST, resample_technique, compression_type, compression_quality, skip_existing, where_clause, sips_mode), True)))
  File "C:\Program Files\ArcGIS\Pro\Resources\ArcPy\arcpy\geoprocessing\_base.py", line 520, in <lambda>
    return lambda *args: val(*gp_fixargs(args, True))
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\pyarrow\__init__.py", line 65, in <module>
    import pyarrow.lib as _lib

AttributeError: _ARRAY_API not found

OK CL_MLP_PAO_IF_Ortho_26_05_10_MonteAranda-NSTC-Km-84p2-a-82p3 -> c:\Users\esrlrivero_adm\Documents\Geosupport\amsa-pao-geosupport\outputs\normalizacion_footprintV7\26_05\CL_MLP_PAO_IF_Ortho_26_05_10_MonteAranda-NSTC-Km-84p2-a-82p3.tif

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.2 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\ipykernel_launcher.py", line 17, in <module>
    app.launch_new_instance()
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\traitlets\config\application.py", line 982, in launch_instance
    app.start()
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\ipykernel\kernelapp.py", line 712, in start
    self.io_loop.start()
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\tornado\platform\asyncio.py", line 215, in start
    self.asyncio_loop.run_forever()
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\asyncio\base_events.py", line 601, in run_forever
    self._run_once()
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\asyncio\base_events.py", line 1905, in _run_once
    handle._run()
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\ipykernel\kernelbase.py", line 510, in dispatch_queue
    await self.process_one()
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\ipykernel\kernelbase.py", line 499, in process_one
    await dispatch(*args)
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\ipykernel\kernelbase.py", line 406, in dispatch_shell
    await result
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\ipykernel\kernelbase.py", line 730, in execute_request
    reply_content = await reply_content
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\ipykernel\ipkernel.py", line 383, in do_execute
    res = shell.run_cell(
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\ipykernel\zmqshell.py", line 528, in run_cell
    return super().run_cell(*args, **kwargs)
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\IPython\core\interactiveshell.py", line 2975, in run_cell
    result = self._run_cell(
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\IPython\core\interactiveshell.py", line 3030, in _run_cell
    return runner(coro)
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\IPython\core\async_helpers.py", line 78, in _pseudo_sync_runner
    coro.send(None)
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\IPython\core\interactiveshell.py", line 3257, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\IPython\core\interactiveshell.py", line 3473, in run_ast_nodes
    if (await self.run_code(code, result,  async_=asy)):
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\IPython\core\interactiveshell.py", line 3553, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "C:\Users\esrlrivero_adm\AppData\Local\Temp\ipykernel_22212\1835472039.py", line 237, in <cell line: 215>
    normalize_raster_by_footprint(source_path, raster_name, output_path, footprints_index)
  File "C:\Users\esrlrivero_adm\AppData\Local\Temp\ipykernel_22212\1835472039.py", line 182, in normalize_raster_by_footprint
    arcpy.management.BuildPyramidsandStatistics(str(output_path))
  File "C:\Program Files\ArcGIS\Pro\Resources\ArcPy\arcpy\management.py", line 19519, in BuildPyramidsandStatistics
    retval = convertArcObjectToPythonObject(gp.BuildPyramidsandStatistics_management(*gp_fixargs((in_workspace, include_subdirectories, build_pyramids, calculate_statistics, BUILD_ON_SOURCE, block_field, estimate_statistics, x_skip_factor, y_skip_factor, ignore_values, pyramid_level, SKIP_FIRST, resample_technique, compression_type, compression_quality, skip_existing, where_clause, sips_mode), True)))
  File "C:\Program Files\ArcGIS\Pro\Resources\ArcPy\arcpy\geoprocessing\_base.py", line 520, in <lambda>
    return lambda *args: val(*gp_fixargs(args, True))
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\pyarrow\__init__.py", line 65, in <module>
    import pyarrow.lib as _lib

AttributeError: _ARRAY_API not found

OK CL_MLP_PAO_IF_Ortho_26_05_13_DME9-PA12-IIFF8 -> c:\Users\esrlrivero_adm\Documents\Geosupport\amsa-pao-geosupport\outputs\normalizacion_footprintV7\26_05\CL_MLP_PAO_IF_Ortho_26_05_13_DME9-PA12-IIFF8.tif

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.2 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\ipykernel_launcher.py", line 17, in <module>
    app.launch_new_instance()
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\traitlets\config\application.py", line 982, in launch_instance
    app.start()
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\ipykernel\kernelapp.py", line 712, in start
    self.io_loop.start()
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\tornado\platform\asyncio.py", line 215, in start
    self.asyncio_loop.run_forever()
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\asyncio\base_events.py", line 601, in run_forever
    self._run_once()
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\asyncio\base_events.py", line 1905, in _run_once
    handle._run()
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\ipykernel\kernelbase.py", line 510, in dispatch_queue
    await self.process_one()
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\ipykernel\kernelbase.py", line 499, in process_one
    await dispatch(*args)
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\ipykernel\kernelbase.py", line 406, in dispatch_shell
    await result
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\ipykernel\kernelbase.py", line 730, in execute_request
    reply_content = await reply_content
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\ipykernel\ipkernel.py", line 383, in do_execute
    res = shell.run_cell(
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\ipykernel\zmqshell.py", line 528, in run_cell
    return super().run_cell(*args, **kwargs)
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\IPython\core\interactiveshell.py", line 2975, in run_cell
    result = self._run_cell(
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\IPython\core\interactiveshell.py", line 3030, in _run_cell
    return runner(coro)
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\IPython\core\async_helpers.py", line 78, in _pseudo_sync_runner
    coro.send(None)
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\IPython\core\interactiveshell.py", line 3257, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\IPython\core\interactiveshell.py", line 3473, in run_ast_nodes
    if (await self.run_code(code, result,  async_=asy)):
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\IPython\core\interactiveshell.py", line 3553, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "C:\Users\esrlrivero_adm\AppData\Local\Temp\ipykernel_22212\1835472039.py", line 237, in <cell line: 215>
    normalize_raster_by_footprint(source_path, raster_name, output_path, footprints_index)
  File "C:\Users\esrlrivero_adm\AppData\Local\Temp\ipykernel_22212\1835472039.py", line 182, in normalize_raster_by_footprint
    arcpy.management.BuildPyramidsandStatistics(str(output_path))
  File "C:\Program Files\ArcGIS\Pro\Resources\ArcPy\arcpy\management.py", line 19519, in BuildPyramidsandStatistics
    retval = convertArcObjectToPythonObject(gp.BuildPyramidsandStatistics_management(*gp_fixargs((in_workspace, include_subdirectories, build_pyramids, calculate_statistics, BUILD_ON_SOURCE, block_field, estimate_statistics, x_skip_factor, y_skip_factor, ignore_values, pyramid_level, SKIP_FIRST, resample_technique, compression_type, compression_quality, skip_existing, where_clause, sips_mode), True)))
  File "C:\Program Files\ArcGIS\Pro\Resources\ArcPy\arcpy\geoprocessing\_base.py", line 520, in <lambda>
    return lambda *args: val(*gp_fixargs(args, True))
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\pyarrow\__init__.py", line 65, in <module>
    import pyarrow.lib as _lib

AttributeError: _ARRAY_API not found

OK CL_MLP_PAO_IF_Ortho_26_05_13_Subestacion-El-Mauro_A_E35 -> c:\Users\esrlrivero_adm\Documents\Geosupport\amsa-pao-geosupport\outputs\normalizacion_footprintV7\26_05\CL_MLP_PAO_IF_Ortho_26_05_13_Subestacion-El-Mauro_A_E35.tif

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.2 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\ipykernel_launcher.py", line 17, in <module>
    app.launch_new_instance()
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\traitlets\config\application.py", line 982, in launch_instance
    app.start()
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\ipykernel\kernelapp.py", line 712, in start
    self.io_loop.start()
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\tornado\platform\asyncio.py", line 215, in start
    self.asyncio_loop.run_forever()
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\asyncio\base_events.py", line 601, in run_forever
    self._run_once()
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\asyncio\base_events.py", line 1905, in _run_once
    handle._run()
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\ipykernel\kernelbase.py", line 510, in dispatch_queue
    await self.process_one()
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\ipykernel\kernelbase.py", line 499, in process_one
    await dispatch(*args)
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\ipykernel\kernelbase.py", line 406, in dispatch_shell
    await result
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\ipykernel\kernelbase.py", line 730, in execute_request
    reply_content = await reply_content
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\ipykernel\ipkernel.py", line 383, in do_execute
    res = shell.run_cell(
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\ipykernel\zmqshell.py", line 528, in run_cell
    return super().run_cell(*args, **kwargs)
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\IPython\core\interactiveshell.py", line 2975, in run_cell
    result = self._run_cell(
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\IPython\core\interactiveshell.py", line 3030, in _run_cell
    return runner(coro)
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\IPython\core\async_helpers.py", line 78, in _pseudo_sync_runner
    coro.send(None)
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\IPython\core\interactiveshell.py", line 3257, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\IPython\core\interactiveshell.py", line 3473, in run_ast_nodes
    if (await self.run_code(code, result,  async_=asy)):
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\IPython\core\interactiveshell.py", line 3553, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "C:\Users\esrlrivero_adm\AppData\Local\Temp\ipykernel_22212\1835472039.py", line 237, in <cell line: 215>
    normalize_raster_by_footprint(source_path, raster_name, output_path, footprints_index)
  File "C:\Users\esrlrivero_adm\AppData\Local\Temp\ipykernel_22212\1835472039.py", line 182, in normalize_raster_by_footprint
    arcpy.management.BuildPyramidsandStatistics(str(output_path))
  File "C:\Program Files\ArcGIS\Pro\Resources\ArcPy\arcpy\management.py", line 19519, in BuildPyramidsandStatistics
    retval = convertArcObjectToPythonObject(gp.BuildPyramidsandStatistics_management(*gp_fixargs((in_workspace, include_subdirectories, build_pyramids, calculate_statistics, BUILD_ON_SOURCE, block_field, estimate_statistics, x_skip_factor, y_skip_factor, ignore_values, pyramid_level, SKIP_FIRST, resample_technique, compression_type, compression_quality, skip_existing, where_clause, sips_mode), True)))
  File "C:\Program Files\ArcGIS\Pro\Resources\ArcPy\arcpy\geoprocessing\_base.py", line 520, in <lambda>
    return lambda *args: val(*gp_fixargs(args, True))
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\pyarrow\__init__.py", line 65, in <module>
    import pyarrow.lib as _lib

AttributeError: _ARRAY_API not found

OK CL_MLP_PAO_IF_Ortho_26_05_13_Subestacion-El-Mauro-1 -> c:\Users\esrlrivero_adm\Documents\Geosupport\amsa-pao-geosupport\outputs\normalizacion_footprintV7\26_05\CL_MLP_PAO_IF_Ortho_26_05_13_Subestacion-El-Mauro-1.tif

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.2 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\ipykernel_launcher.py", line 17, in <module>
    app.launch_new_instance()
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\traitlets\config\application.py", line 982, in launch_instance
    app.start()
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\ipykernel\kernelapp.py", line 712, in start
    self.io_loop.start()
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\tornado\platform\asyncio.py", line 215, in start
    self.asyncio_loop.run_forever()
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\asyncio\base_events.py", line 601, in run_forever
    self._run_once()
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\asyncio\base_events.py", line 1905, in _run_once
    handle._run()
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\ipykernel\kernelbase.py", line 510, in dispatch_queue
    await self.process_one()
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\ipykernel\kernelbase.py", line 499, in process_one
    await dispatch(*args)
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\ipykernel\kernelbase.py", line 406, in dispatch_shell
    await result
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\ipykernel\kernelbase.py", line 730, in execute_request
    reply_content = await reply_content
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\ipykernel\ipkernel.py", line 383, in do_execute
    res = shell.run_cell(
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\ipykernel\zmqshell.py", line 528, in run_cell
    return super().run_cell(*args, **kwargs)
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\IPython\core\interactiveshell.py", line 2975, in run_cell
    result = self._run_cell(
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\IPython\core\interactiveshell.py", line 3030, in _run_cell
    return runner(coro)
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\IPython\core\async_helpers.py", line 78, in _pseudo_sync_runner
    coro.send(None)
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\IPython\core\interactiveshell.py", line 3257, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\IPython\core\interactiveshell.py", line 3473, in run_ast_nodes
    if (await self.run_code(code, result,  async_=asy)):
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\IPython\core\interactiveshell.py", line 3553, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "C:\Users\esrlrivero_adm\AppData\Local\Temp\ipykernel_22212\1835472039.py", line 237, in <cell line: 215>
    normalize_raster_by_footprint(source_path, raster_name, output_path, footprints_index)
  File "C:\Users\esrlrivero_adm\AppData\Local\Temp\ipykernel_22212\1835472039.py", line 182, in normalize_raster_by_footprint
    arcpy.management.BuildPyramidsandStatistics(str(output_path))
  File "C:\Program Files\ArcGIS\Pro\Resources\ArcPy\arcpy\management.py", line 19519, in BuildPyramidsandStatistics
    retval = convertArcObjectToPythonObject(gp.BuildPyramidsandStatistics_management(*gp_fixargs((in_workspace, include_subdirectories, build_pyramids, calculate_statistics, BUILD_ON_SOURCE, block_field, estimate_statistics, x_skip_factor, y_skip_factor, ignore_values, pyramid_level, SKIP_FIRST, resample_technique, compression_type, compression_quality, skip_existing, where_clause, sips_mode), True)))
  File "C:\Program Files\ArcGIS\Pro\Resources\ArcPy\arcpy\geoprocessing\_base.py", line 520, in <lambda>
    return lambda *args: val(*gp_fixargs(args, True))
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\pyarrow\__init__.py", line 65, in <module>
    import pyarrow.lib as _lib

AttributeError: _ARRAY_API not found

OK CL_MLP_PAO_IF_Ortho_26_05_13_EM2_S2 -> c:\Users\esrlrivero_adm\Documents\Geosupport\amsa-pao-geosupport\outputs\normalizacion_footprintV7\26_05\CL_MLP_PAO_IF_Ortho_26_05_13_EM2_S2.tif

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.2 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\ipykernel_launcher.py", line 17, in <module>
    app.launch_new_instance()
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\traitlets\config\application.py", line 982, in launch_instance
    app.start()
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\ipykernel\kernelapp.py", line 712, in start
    self.io_loop.start()
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\tornado\platform\asyncio.py", line 215, in start
    self.asyncio_loop.run_forever()
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\asyncio\base_events.py", line 601, in run_forever
    self._run_once()
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\asyncio\base_events.py", line 1905, in _run_once
    handle._run()
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\ipykernel\kernelbase.py", line 510, in dispatch_queue
    await self.process_one()
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\ipykernel\kernelbase.py", line 499, in process_one
    await dispatch(*args)
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\ipykernel\kernelbase.py", line 406, in dispatch_shell
    await result
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\ipykernel\kernelbase.py", line 730, in execute_request
    reply_content = await reply_content
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\ipykernel\ipkernel.py", line 383, in do_execute
    res = shell.run_cell(
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\ipykernel\zmqshell.py", line 528, in run_cell
    return super().run_cell(*args, **kwargs)
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\IPython\core\interactiveshell.py", line 2975, in run_cell
    result = self._run_cell(
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\IPython\core\interactiveshell.py", line 3030, in _run_cell
    return runner(coro)
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\IPython\core\async_helpers.py", line 78, in _pseudo_sync_runner
    coro.send(None)
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\IPython\core\interactiveshell.py", line 3257, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\IPython\core\interactiveshell.py", line 3473, in run_ast_nodes
    if (await self.run_code(code, result,  async_=asy)):
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\IPython\core\interactiveshell.py", line 3553, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "C:\Users\esrlrivero_adm\AppData\Local\Temp\ipykernel_22212\1835472039.py", line 237, in <cell line: 215>
    normalize_raster_by_footprint(source_path, raster_name, output_path, footprints_index)
  File "C:\Users\esrlrivero_adm\AppData\Local\Temp\ipykernel_22212\1835472039.py", line 182, in normalize_raster_by_footprint
    arcpy.management.BuildPyramidsandStatistics(str(output_path))
  File "C:\Program Files\ArcGIS\Pro\Resources\ArcPy\arcpy\management.py", line 19519, in BuildPyramidsandStatistics
    retval = convertArcObjectToPythonObject(gp.BuildPyramidsandStatistics_management(*gp_fixargs((in_workspace, include_subdirectories, build_pyramids, calculate_statistics, BUILD_ON_SOURCE, block_field, estimate_statistics, x_skip_factor, y_skip_factor, ignore_values, pyramid_level, SKIP_FIRST, resample_technique, compression_type, compression_quality, skip_existing, where_clause, sips_mode), True)))
  File "C:\Program Files\ArcGIS\Pro\Resources\ArcPy\arcpy\geoprocessing\_base.py", line 520, in <lambda>
    return lambda *args: val(*gp_fixargs(args, True))
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\pyarrow\__init__.py", line 65, in <module>
    import pyarrow.lib as _lib

AttributeError: _ARRAY_API not found

OK CL_MLP_PAO_IF_Ortho_26_05_13_EBD-1 -> c:\Users\esrlrivero_adm\Documents\Geosupport\amsa-pao-geosupport\outputs\normalizacion_footprintV7\26_05\CL_MLP_PAO_IF_Ortho_26_05_13_EBD-1.tif

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.2 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\ipykernel_launcher.py", line 17, in <module>
    app.launch_new_instance()
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\traitlets\config\application.py", line 982, in launch_instance
    app.start()
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\ipykernel\kernelapp.py", line 712, in start
    self.io_loop.start()
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\tornado\platform\asyncio.py", line 215, in start
    self.asyncio_loop.run_forever()
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\asyncio\base_events.py", line 601, in run_forever
    self._run_once()
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\asyncio\base_events.py", line 1905, in _run_once
    handle._run()
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\ipykernel\kernelbase.py", line 510, in dispatch_queue
    await self.process_one()
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\ipykernel\kernelbase.py", line 499, in process_one
    await dispatch(*args)
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\ipykernel\kernelbase.py", line 406, in dispatch_shell
    await result
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\ipykernel\kernelbase.py", line 730, in execute_request
    reply_content = await reply_content
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\ipykernel\ipkernel.py", line 383, in do_execute
    res = shell.run_cell(
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\ipykernel\zmqshell.py", line 528, in run_cell
    return super().run_cell(*args, **kwargs)
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\IPython\core\interactiveshell.py", line 2975, in run_cell
    result = self._run_cell(
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\IPython\core\interactiveshell.py", line 3030, in _run_cell
    return runner(coro)
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\IPython\core\async_helpers.py", line 78, in _pseudo_sync_runner
    coro.send(None)
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\IPython\core\interactiveshell.py", line 3257, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\IPython\core\interactiveshell.py", line 3473, in run_ast_nodes
    if (await self.run_code(code, result,  async_=asy)):
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\IPython\core\interactiveshell.py", line 3553, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "C:\Users\esrlrivero_adm\AppData\Local\Temp\ipykernel_22212\1835472039.py", line 237, in <cell line: 215>
    normalize_raster_by_footprint(source_path, raster_name, output_path, footprints_index)
  File "C:\Users\esrlrivero_adm\AppData\Local\Temp\ipykernel_22212\1835472039.py", line 182, in normalize_raster_by_footprint
    arcpy.management.BuildPyramidsandStatistics(str(output_path))
  File "C:\Program Files\ArcGIS\Pro\Resources\ArcPy\arcpy\management.py", line 19519, in BuildPyramidsandStatistics
    retval = convertArcObjectToPythonObject(gp.BuildPyramidsandStatistics_management(*gp_fixargs((in_workspace, include_subdirectories, build_pyramids, calculate_statistics, BUILD_ON_SOURCE, block_field, estimate_statistics, x_skip_factor, y_skip_factor, ignore_values, pyramid_level, SKIP_FIRST, resample_technique, compression_type, compression_quality, skip_existing, where_clause, sips_mode), True)))
  File "C:\Program Files\ArcGIS\Pro\Resources\ArcPy\arcpy\geoprocessing\_base.py", line 520, in <lambda>
    return lambda *args: val(*gp_fixargs(args, True))
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\pyarrow\__init__.py", line 65, in <module>
    import pyarrow.lib as _lib

AttributeError: _ARRAY_API not found

OK CL_MLP_PAO_IF_Ortho_26_05_13_ED2 -> c:\Users\esrlrivero_adm\Documents\Geosupport\amsa-pao-geosupport\outputs\normalizacion_footprintV7\26_05\CL_MLP_PAO_IF_Ortho_26_05_13_ED2.tif

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.2 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\ipykernel_launcher.py", line 17, in <module>
    app.launch_new_instance()
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\traitlets\config\application.py", line 982, in launch_instance
    app.start()
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\ipykernel\kernelapp.py", line 712, in start
    self.io_loop.start()
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\tornado\platform\asyncio.py", line 215, in start
    self.asyncio_loop.run_forever()
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\asyncio\base_events.py", line 601, in run_forever
    self._run_once()
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\asyncio\base_events.py", line 1905, in _run_once
    handle._run()
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\ipykernel\kernelbase.py", line 510, in dispatch_queue
    await self.process_one()
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\ipykernel\kernelbase.py", line 499, in process_one
    await dispatch(*args)
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\ipykernel\kernelbase.py", line 406, in dispatch_shell
    await result
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\ipykernel\kernelbase.py", line 730, in execute_request
    reply_content = await reply_content
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\ipykernel\ipkernel.py", line 383, in do_execute
    res = shell.run_cell(
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\ipykernel\zmqshell.py", line 528, in run_cell
    return super().run_cell(*args, **kwargs)
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\IPython\core\interactiveshell.py", line 2975, in run_cell
    result = self._run_cell(
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\IPython\core\interactiveshell.py", line 3030, in _run_cell
    return runner(coro)
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\IPython\core\async_helpers.py", line 78, in _pseudo_sync_runner
    coro.send(None)
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\IPython\core\interactiveshell.py", line 3257, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\IPython\core\interactiveshell.py", line 3473, in run_ast_nodes
    if (await self.run_code(code, result,  async_=asy)):
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\IPython\core\interactiveshell.py", line 3553, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "C:\Users\esrlrivero_adm\AppData\Local\Temp\ipykernel_22212\1835472039.py", line 237, in <cell line: 215>
    normalize_raster_by_footprint(source_path, raster_name, output_path, footprints_index)
  File "C:\Users\esrlrivero_adm\AppData\Local\Temp\ipykernel_22212\1835472039.py", line 182, in normalize_raster_by_footprint
    arcpy.management.BuildPyramidsandStatistics(str(output_path))
  File "C:\Program Files\ArcGIS\Pro\Resources\ArcPy\arcpy\management.py", line 19519, in BuildPyramidsandStatistics
    retval = convertArcObjectToPythonObject(gp.BuildPyramidsandStatistics_management(*gp_fixargs((in_workspace, include_subdirectories, build_pyramids, calculate_statistics, BUILD_ON_SOURCE, block_field, estimate_statistics, x_skip_factor, y_skip_factor, ignore_values, pyramid_level, SKIP_FIRST, resample_technique, compression_type, compression_quality, skip_existing, where_clause, sips_mode), True)))
  File "C:\Program Files\ArcGIS\Pro\Resources\ArcPy\arcpy\geoprocessing\_base.py", line 520, in <lambda>
    return lambda *args: val(*gp_fixargs(args, True))
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\pyarrow\__init__.py", line 65, in <module>
    import pyarrow.lib as _lib

AttributeError: _ARRAY_API not found

OK CL_MLP_PAO_IF_Ortho_26_05_13_Subestacion-El-Mauro-2 -> c:\Users\esrlrivero_adm\Documents\Geosupport\amsa-pao-geosupport\outputs\normalizacion_footprintV7\26_05\CL_MLP_PAO_IF_Ortho_26_05_13_Subestacion-El-Mauro-2.tif

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.2 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\ipykernel_launcher.py", line 17, in <module>
    app.launch_new_instance()
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\traitlets\config\application.py", line 982, in launch_instance
    app.start()
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\ipykernel\kernelapp.py", line 712, in start
    self.io_loop.start()
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\tornado\platform\asyncio.py", line 215, in start
    self.asyncio_loop.run_forever()
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\asyncio\base_events.py", line 601, in run_forever
    self._run_once()
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\asyncio\base_events.py", line 1905, in _run_once
    handle._run()
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\ipykernel\kernelbase.py", line 510, in dispatch_queue
    await self.process_one()
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\ipykernel\kernelbase.py", line 499, in process_one
    await dispatch(*args)
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\ipykernel\kernelbase.py", line 406, in dispatch_shell
    await result
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\ipykernel\kernelbase.py", line 730, in execute_request
    reply_content = await reply_content
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\ipykernel\ipkernel.py", line 383, in do_execute
    res = shell.run_cell(
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\ipykernel\zmqshell.py", line 528, in run_cell
    return super().run_cell(*args, **kwargs)
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\IPython\core\interactiveshell.py", line 2975, in run_cell
    result = self._run_cell(
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\IPython\core\interactiveshell.py", line 3030, in _run_cell
    return runner(coro)
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\IPython\core\async_helpers.py", line 78, in _pseudo_sync_runner
    coro.send(None)
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\IPython\core\interactiveshell.py", line 3257, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\IPython\core\interactiveshell.py", line 3473, in run_ast_nodes
    if (await self.run_code(code, result,  async_=asy)):
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\IPython\core\interactiveshell.py", line 3553, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "C:\Users\esrlrivero_adm\AppData\Local\Temp\ipykernel_22212\1835472039.py", line 237, in <cell line: 215>
    normalize_raster_by_footprint(source_path, raster_name, output_path, footprints_index)
  File "C:\Users\esrlrivero_adm\AppData\Local\Temp\ipykernel_22212\1835472039.py", line 182, in normalize_raster_by_footprint
    arcpy.management.BuildPyramidsandStatistics(str(output_path))
  File "C:\Program Files\ArcGIS\Pro\Resources\ArcPy\arcpy\management.py", line 19519, in BuildPyramidsandStatistics
    retval = convertArcObjectToPythonObject(gp.BuildPyramidsandStatistics_management(*gp_fixargs((in_workspace, include_subdirectories, build_pyramids, calculate_statistics, BUILD_ON_SOURCE, block_field, estimate_statistics, x_skip_factor, y_skip_factor, ignore_values, pyramid_level, SKIP_FIRST, resample_technique, compression_type, compression_quality, skip_existing, where_clause, sips_mode), True)))
  File "C:\Program Files\ArcGIS\Pro\Resources\ArcPy\arcpy\geoprocessing\_base.py", line 520, in <lambda>
    return lambda *args: val(*gp_fixargs(args, True))
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\pyarrow\__init__.py", line 65, in <module>
    import pyarrow.lib as _lib

AttributeError: _ARRAY_API not found

OK CL_MLP_PAO_IF_Ortho_26_05_13_EBD-2 -> c:\Users\esrlrivero_adm\Documents\Geosupport\amsa-pao-geosupport\outputs\normalizacion_footprintV7\26_05\CL_MLP_PAO_IF_Ortho_26_05_13_EBD-2.tif

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.2 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\ipykernel_launcher.py", line 17, in <module>
    app.launch_new_instance()
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\traitlets\config\application.py", line 982, in launch_instance
    app.start()
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\ipykernel\kernelapp.py", line 712, in start
    self.io_loop.start()
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\tornado\platform\asyncio.py", line 215, in start
    self.asyncio_loop.run_forever()
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\asyncio\base_events.py", line 601, in run_forever
    self._run_once()
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\asyncio\base_events.py", line 1905, in _run_once
    handle._run()
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\ipykernel\kernelbase.py", line 510, in dispatch_queue
    await self.process_one()
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\ipykernel\kernelbase.py", line 499, in process_one
    await dispatch(*args)
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\ipykernel\kernelbase.py", line 406, in dispatch_shell
    await result
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\ipykernel\kernelbase.py", line 730, in execute_request
    reply_content = await reply_content
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\ipykernel\ipkernel.py", line 383, in do_execute
    res = shell.run_cell(
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\ipykernel\zmqshell.py", line 528, in run_cell
    return super().run_cell(*args, **kwargs)
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\IPython\core\interactiveshell.py", line 2975, in run_cell
    result = self._run_cell(
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\IPython\core\interactiveshell.py", line 3030, in _run_cell
    return runner(coro)
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\IPython\core\async_helpers.py", line 78, in _pseudo_sync_runner
    coro.send(None)
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\IPython\core\interactiveshell.py", line 3257, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\IPython\core\interactiveshell.py", line 3473, in run_ast_nodes
    if (await self.run_code(code, result,  async_=asy)):
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\IPython\core\interactiveshell.py", line 3553, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "C:\Users\esrlrivero_adm\AppData\Local\Temp\ipykernel_22212\1835472039.py", line 237, in <cell line: 215>
    normalize_raster_by_footprint(source_path, raster_name, output_path, footprints_index)
  File "C:\Users\esrlrivero_adm\AppData\Local\Temp\ipykernel_22212\1835472039.py", line 182, in normalize_raster_by_footprint
    arcpy.management.BuildPyramidsandStatistics(str(output_path))
  File "C:\Program Files\ArcGIS\Pro\Resources\ArcPy\arcpy\management.py", line 19519, in BuildPyramidsandStatistics
    retval = convertArcObjectToPythonObject(gp.BuildPyramidsandStatistics_management(*gp_fixargs((in_workspace, include_subdirectories, build_pyramids, calculate_statistics, BUILD_ON_SOURCE, block_field, estimate_statistics, x_skip_factor, y_skip_factor, ignore_values, pyramid_level, SKIP_FIRST, resample_technique, compression_type, compression_quality, skip_existing, where_clause, sips_mode), True)))
  File "C:\Program Files\ArcGIS\Pro\Resources\ArcPy\arcpy\geoprocessing\_base.py", line 520, in <lambda>
    return lambda *args: val(*gp_fixargs(args, True))
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\pyarrow\__init__.py", line 65, in <module>
    import pyarrow.lib as _lib

AttributeError: _ARRAY_API not found

OK CL_MLP_PAO_IF_Ortho_26_05_13_Estacion_Intermedia -> c:\Users\esrlrivero_adm\Documents\Geosupport\amsa-pao-geosupport\outputs\normalizacion_footprintV7\26_05\CL_MLP_PAO_IF_Ortho_26_05_13_Estacion_Intermedia.tif

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.2 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\ipykernel_launcher.py", line 17, in <module>
    app.launch_new_instance()
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\traitlets\config\application.py", line 982, in launch_instance
    app.start()
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\ipykernel\kernelapp.py", line 712, in start
    self.io_loop.start()
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\tornado\platform\asyncio.py", line 215, in start
    self.asyncio_loop.run_forever()
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\asyncio\base_events.py", line 601, in run_forever
    self._run_once()
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\asyncio\base_events.py", line 1905, in _run_once
    handle._run()
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\ipykernel\kernelbase.py", line 510, in dispatch_queue
    await self.process_one()
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\ipykernel\kernelbase.py", line 499, in process_one
    await dispatch(*args)
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\ipykernel\kernelbase.py", line 406, in dispatch_shell
    await result
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\ipykernel\kernelbase.py", line 730, in execute_request
    reply_content = await reply_content
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\ipykernel\ipkernel.py", line 383, in do_execute
    res = shell.run_cell(
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\ipykernel\zmqshell.py", line 528, in run_cell
    return super().run_cell(*args, **kwargs)
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\IPython\core\interactiveshell.py", line 2975, in run_cell
    result = self._run_cell(
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\IPython\core\interactiveshell.py", line 3030, in _run_cell
    return runner(coro)
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\IPython\core\async_helpers.py", line 78, in _pseudo_sync_runner
    coro.send(None)
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\IPython\core\interactiveshell.py", line 3257, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\IPython\core\interactiveshell.py", line 3473, in run_ast_nodes
    if (await self.run_code(code, result,  async_=asy)):
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\IPython\core\interactiveshell.py", line 3553, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "C:\Users\esrlrivero_adm\AppData\Local\Temp\ipykernel_22212\1835472039.py", line 237, in <cell line: 215>
    normalize_raster_by_footprint(source_path, raster_name, output_path, footprints_index)
  File "C:\Users\esrlrivero_adm\AppData\Local\Temp\ipykernel_22212\1835472039.py", line 182, in normalize_raster_by_footprint
    arcpy.management.BuildPyramidsandStatistics(str(output_path))
  File "C:\Program Files\ArcGIS\Pro\Resources\ArcPy\arcpy\management.py", line 19519, in BuildPyramidsandStatistics
    retval = convertArcObjectToPythonObject(gp.BuildPyramidsandStatistics_management(*gp_fixargs((in_workspace, include_subdirectories, build_pyramids, calculate_statistics, BUILD_ON_SOURCE, block_field, estimate_statistics, x_skip_factor, y_skip_factor, ignore_values, pyramid_level, SKIP_FIRST, resample_technique, compression_type, compression_quality, skip_existing, where_clause, sips_mode), True)))
  File "C:\Program Files\ArcGIS\Pro\Resources\ArcPy\arcpy\geoprocessing\_base.py", line 520, in <lambda>
    return lambda *args: val(*gp_fixargs(args, True))
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\pyarrow\__init__.py", line 65, in <module>
    import pyarrow.lib as _lib

AttributeError: _ARRAY_API not found

OK CL_MLP_PAO_IF_Ortho_26_05_14_EM3 -> c:\Users\esrlrivero_adm\Documents\Geosupport\amsa-pao-geosupport\outputs\normalizacion_footprintV7\26_05\CL_MLP_PAO_IF_Ortho_26_05_14_EM3.tif

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.2 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\ipykernel_launcher.py", line 17, in <module>
    app.launch_new_instance()
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\traitlets\config\application.py", line 982, in launch_instance
    app.start()
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\ipykernel\kernelapp.py", line 712, in start
    self.io_loop.start()
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\tornado\platform\asyncio.py", line 215, in start
    self.asyncio_loop.run_forever()
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\asyncio\base_events.py", line 601, in run_forever
    self._run_once()
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\asyncio\base_events.py", line 1905, in _run_once
    handle._run()
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\ipykernel\kernelbase.py", line 510, in dispatch_queue
    await self.process_one()
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\ipykernel\kernelbase.py", line 499, in process_one
    await dispatch(*args)
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\ipykernel\kernelbase.py", line 406, in dispatch_shell
    await result
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\ipykernel\kernelbase.py", line 730, in execute_request
    reply_content = await reply_content
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\ipykernel\ipkernel.py", line 383, in do_execute
    res = shell.run_cell(
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\ipykernel\zmqshell.py", line 528, in run_cell
    return super().run_cell(*args, **kwargs)
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\IPython\core\interactiveshell.py", line 2975, in run_cell
    result = self._run_cell(
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\IPython\core\interactiveshell.py", line 3030, in _run_cell
    return runner(coro)
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\IPython\core\async_helpers.py", line 78, in _pseudo_sync_runner
    coro.send(None)
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\IPython\core\interactiveshell.py", line 3257, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\IPython\core\interactiveshell.py", line 3473, in run_ast_nodes
    if (await self.run_code(code, result,  async_=asy)):
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\IPython\core\interactiveshell.py", line 3553, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "C:\Users\esrlrivero_adm\AppData\Local\Temp\ipykernel_22212\1835472039.py", line 237, in <cell line: 215>
    normalize_raster_by_footprint(source_path, raster_name, output_path, footprints_index)
  File "C:\Users\esrlrivero_adm\AppData\Local\Temp\ipykernel_22212\1835472039.py", line 182, in normalize_raster_by_footprint
    arcpy.management.BuildPyramidsandStatistics(str(output_path))
  File "C:\Program Files\ArcGIS\Pro\Resources\ArcPy\arcpy\management.py", line 19519, in BuildPyramidsandStatistics
    retval = convertArcObjectToPythonObject(gp.BuildPyramidsandStatistics_management(*gp_fixargs((in_workspace, include_subdirectories, build_pyramids, calculate_statistics, BUILD_ON_SOURCE, block_field, estimate_statistics, x_skip_factor, y_skip_factor, ignore_values, pyramid_level, SKIP_FIRST, resample_technique, compression_type, compression_quality, skip_existing, where_clause, sips_mode), True)))
  File "C:\Program Files\ArcGIS\Pro\Resources\ArcPy\arcpy\geoprocessing\_base.py", line 520, in <lambda>
    return lambda *args: val(*gp_fixargs(args, True))
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\pyarrow\__init__.py", line 65, in <module>
    import pyarrow.lib as _lib

AttributeError: _ARRAY_API not found

OK CL_MLP_PAO_IF_Ortho_26_05_14_Camino_Alternativo_Salamanca -> c:\Users\esrlrivero_adm\Documents\Geosupport\amsa-pao-geosupport\outputs\normalizacion_footprintV7\26_05\CL_MLP_PAO_IF_Ortho_26_05_14_Camino_Alternativo_Salamanca.tif

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.2 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\ipykernel_launcher.py", line 17, in <module>
    app.launch_new_instance()
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\traitlets\config\application.py", line 982, in launch_instance
    app.start()
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\ipykernel\kernelapp.py", line 712, in start
    self.io_loop.start()
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\tornado\platform\asyncio.py", line 215, in start
    self.asyncio_loop.run_forever()
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\asyncio\base_events.py", line 601, in run_forever
    self._run_once()
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\asyncio\base_events.py", line 1905, in _run_once
    handle._run()
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\ipykernel\kernelbase.py", line 510, in dispatch_queue
    await self.process_one()
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\ipykernel\kernelbase.py", line 499, in process_one
    await dispatch(*args)
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\ipykernel\kernelbase.py", line 406, in dispatch_shell
    await result
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\ipykernel\kernelbase.py", line 730, in execute_request
    reply_content = await reply_content
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\ipykernel\ipkernel.py", line 383, in do_execute
    res = shell.run_cell(
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\ipykernel\zmqshell.py", line 528, in run_cell
    return super().run_cell(*args, **kwargs)
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\IPython\core\interactiveshell.py", line 2975, in run_cell
    result = self._run_cell(
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\IPython\core\interactiveshell.py", line 3030, in _run_cell
    return runner(coro)
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\IPython\core\async_helpers.py", line 78, in _pseudo_sync_runner
    coro.send(None)
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\IPython\core\interactiveshell.py", line 3257, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\IPython\core\interactiveshell.py", line 3473, in run_ast_nodes
    if (await self.run_code(code, result,  async_=asy)):
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\IPython\core\interactiveshell.py", line 3553, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "C:\Users\esrlrivero_adm\AppData\Local\Temp\ipykernel_22212\1835472039.py", line 237, in <cell line: 215>
    normalize_raster_by_footprint(source_path, raster_name, output_path, footprints_index)
  File "C:\Users\esrlrivero_adm\AppData\Local\Temp\ipykernel_22212\1835472039.py", line 182, in normalize_raster_by_footprint
    arcpy.management.BuildPyramidsandStatistics(str(output_path))
  File "C:\Program Files\ArcGIS\Pro\Resources\ArcPy\arcpy\management.py", line 19519, in BuildPyramidsandStatistics
    retval = convertArcObjectToPythonObject(gp.BuildPyramidsandStatistics_management(*gp_fixargs((in_workspace, include_subdirectories, build_pyramids, calculate_statistics, BUILD_ON_SOURCE, block_field, estimate_statistics, x_skip_factor, y_skip_factor, ignore_values, pyramid_level, SKIP_FIRST, resample_technique, compression_type, compression_quality, skip_existing, where_clause, sips_mode), True)))
  File "C:\Program Files\ArcGIS\Pro\Resources\ArcPy\arcpy\geoprocessing\_base.py", line 520, in <lambda>
    return lambda *args: val(*gp_fixargs(args, True))
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\pyarrow\__init__.py", line 65, in <module>
    import pyarrow.lib as _lib

AttributeError: _ARRAY_API not found

OK CL_MLP_PAO_IF_Ortho_26_05_14_TORRES_E31_A_E48_PV4-1 -> c:\Users\esrlrivero_adm\Documents\Geosupport\amsa-pao-geosupport\outputs\normalizacion_footprintV7\26_05\CL_MLP_PAO_IF_Ortho_26_05_14_TORRES_E31_A_E48_PV4-1.tif

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.2 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\ipykernel_launcher.py", line 17, in <module>
    app.launch_new_instance()
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\traitlets\config\application.py", line 982, in launch_instance
    app.start()
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\ipykernel\kernelapp.py", line 712, in start
    self.io_loop.start()
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\tornado\platform\asyncio.py", line 215, in start
    self.asyncio_loop.run_forever()
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\asyncio\base_events.py", line 601, in run_forever
    self._run_once()
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\asyncio\base_events.py", line 1905, in _run_once
    handle._run()
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\ipykernel\kernelbase.py", line 510, in dispatch_queue
    await self.process_one()
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\ipykernel\kernelbase.py", line 499, in process_one
    await dispatch(*args)
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\ipykernel\kernelbase.py", line 406, in dispatch_shell
    await result
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\ipykernel\kernelbase.py", line 730, in execute_request
    reply_content = await reply_content
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\ipykernel\ipkernel.py", line 383, in do_execute
    res = shell.run_cell(
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\ipykernel\zmqshell.py", line 528, in run_cell
    return super().run_cell(*args, **kwargs)
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\IPython\core\interactiveshell.py", line 2975, in run_cell
    result = self._run_cell(
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\IPython\core\interactiveshell.py", line 3030, in _run_cell
    return runner(coro)
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\IPython\core\async_helpers.py", line 78, in _pseudo_sync_runner
    coro.send(None)
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\IPython\core\interactiveshell.py", line 3257, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\IPython\core\interactiveshell.py", line 3473, in run_ast_nodes
    if (await self.run_code(code, result,  async_=asy)):
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\IPython\core\interactiveshell.py", line 3553, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "C:\Users\esrlrivero_adm\AppData\Local\Temp\ipykernel_22212\1835472039.py", line 237, in <cell line: 215>
    normalize_raster_by_footprint(source_path, raster_name, output_path, footprints_index)
  File "C:\Users\esrlrivero_adm\AppData\Local\Temp\ipykernel_22212\1835472039.py", line 182, in normalize_raster_by_footprint
    arcpy.management.BuildPyramidsandStatistics(str(output_path))
  File "C:\Program Files\ArcGIS\Pro\Resources\ArcPy\arcpy\management.py", line 19519, in BuildPyramidsandStatistics
    retval = convertArcObjectToPythonObject(gp.BuildPyramidsandStatistics_management(*gp_fixargs((in_workspace, include_subdirectories, build_pyramids, calculate_statistics, BUILD_ON_SOURCE, block_field, estimate_statistics, x_skip_factor, y_skip_factor, ignore_values, pyramid_level, SKIP_FIRST, resample_technique, compression_type, compression_quality, skip_existing, where_clause, sips_mode), True)))
  File "C:\Program Files\ArcGIS\Pro\Resources\ArcPy\arcpy\geoprocessing\_base.py", line 520, in <lambda>
    return lambda *args: val(*gp_fixargs(args, True))
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\pyarrow\__init__.py", line 65, in <module>
    import pyarrow.lib as _lib

AttributeError: _ARRAY_API not found

OK CL_MLP_PAO_IF_Ortho_26_05_14_Subestacion-El-Mauro_A_E35 -> c:\Users\esrlrivero_adm\Documents\Geosupport\amsa-pao-geosupport\outputs\normalizacion_footprintV7\26_05\CL_MLP_PAO_IF_Ortho_26_05_14_Subestacion-El-Mauro_A_E35.tif

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.2 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\ipykernel_launcher.py", line 17, in <module>
    app.launch_new_instance()
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\traitlets\config\application.py", line 982, in launch_instance
    app.start()
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\ipykernel\kernelapp.py", line 712, in start
    self.io_loop.start()
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\tornado\platform\asyncio.py", line 215, in start
    self.asyncio_loop.run_forever()
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\asyncio\base_events.py", line 601, in run_forever
    self._run_once()
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\asyncio\base_events.py", line 1905, in _run_once
    handle._run()
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\ipykernel\kernelbase.py", line 510, in dispatch_queue
    await self.process_one()
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\ipykernel\kernelbase.py", line 499, in process_one
    await dispatch(*args)
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\ipykernel\kernelbase.py", line 406, in dispatch_shell
    await result
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\ipykernel\kernelbase.py", line 730, in execute_request
    reply_content = await reply_content
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\ipykernel\ipkernel.py", line 383, in do_execute
    res = shell.run_cell(
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\ipykernel\zmqshell.py", line 528, in run_cell
    return super().run_cell(*args, **kwargs)
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\IPython\core\interactiveshell.py", line 2975, in run_cell
    result = self._run_cell(
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\IPython\core\interactiveshell.py", line 3030, in _run_cell
    return runner(coro)
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\IPython\core\async_helpers.py", line 78, in _pseudo_sync_runner
    coro.send(None)
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\IPython\core\interactiveshell.py", line 3257, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\IPython\core\interactiveshell.py", line 3473, in run_ast_nodes
    if (await self.run_code(code, result,  async_=asy)):
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\IPython\core\interactiveshell.py", line 3553, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "C:\Users\esrlrivero_adm\AppData\Local\Temp\ipykernel_22212\1835472039.py", line 237, in <cell line: 215>
    normalize_raster_by_footprint(source_path, raster_name, output_path, footprints_index)
  File "C:\Users\esrlrivero_adm\AppData\Local\Temp\ipykernel_22212\1835472039.py", line 182, in normalize_raster_by_footprint
    arcpy.management.BuildPyramidsandStatistics(str(output_path))
  File "C:\Program Files\ArcGIS\Pro\Resources\ArcPy\arcpy\management.py", line 19519, in BuildPyramidsandStatistics
    retval = convertArcObjectToPythonObject(gp.BuildPyramidsandStatistics_management(*gp_fixargs((in_workspace, include_subdirectories, build_pyramids, calculate_statistics, BUILD_ON_SOURCE, block_field, estimate_statistics, x_skip_factor, y_skip_factor, ignore_values, pyramid_level, SKIP_FIRST, resample_technique, compression_type, compression_quality, skip_existing, where_clause, sips_mode), True)))
  File "C:\Program Files\ArcGIS\Pro\Resources\ArcPy\arcpy\geoprocessing\_base.py", line 520, in <lambda>
    return lambda *args: val(*gp_fixargs(args, True))
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\pyarrow\__init__.py", line 65, in <module>
    import pyarrow.lib as _lib

AttributeError: _ARRAY_API not found

OK CL_MLP_PAO_IF_Ortho_26_05_15_Helipuerto-1 -> c:\Users\esrlrivero_adm\Documents\Geosupport\amsa-pao-geosupport\outputs\normalizacion_footprintV7\26_05\CL_MLP_PAO_IF_Ortho_26_05_15_Helipuerto-1.tif

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.2 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\ipykernel_launcher.py", line 17, in <module>
    app.launch_new_instance()
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\traitlets\config\application.py", line 982, in launch_instance
    app.start()
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\ipykernel\kernelapp.py", line 712, in start
    self.io_loop.start()
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\tornado\platform\asyncio.py", line 215, in start
    self.asyncio_loop.run_forever()
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\asyncio\base_events.py", line 601, in run_forever
    self._run_once()
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\asyncio\base_events.py", line 1905, in _run_once
    handle._run()
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\ipykernel\kernelbase.py", line 510, in dispatch_queue
    await self.process_one()
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\ipykernel\kernelbase.py", line 499, in process_one
    await dispatch(*args)
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\ipykernel\kernelbase.py", line 406, in dispatch_shell
    await result
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\ipykernel\kernelbase.py", line 730, in execute_request
    reply_content = await reply_content
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\ipykernel\ipkernel.py", line 383, in do_execute
    res = shell.run_cell(
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\ipykernel\zmqshell.py", line 528, in run_cell
    return super().run_cell(*args, **kwargs)
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\IPython\core\interactiveshell.py", line 2975, in run_cell
    result = self._run_cell(
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\IPython\core\interactiveshell.py", line 3030, in _run_cell
    return runner(coro)
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\IPython\core\async_helpers.py", line 78, in _pseudo_sync_runner
    coro.send(None)
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\IPython\core\interactiveshell.py", line 3257, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\IPython\core\interactiveshell.py", line 3473, in run_ast_nodes
    if (await self.run_code(code, result,  async_=asy)):
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\IPython\core\interactiveshell.py", line 3553, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "C:\Users\esrlrivero_adm\AppData\Local\Temp\ipykernel_22212\1835472039.py", line 237, in <cell line: 215>
    normalize_raster_by_footprint(source_path, raster_name, output_path, footprints_index)
  File "C:\Users\esrlrivero_adm\AppData\Local\Temp\ipykernel_22212\1835472039.py", line 182, in normalize_raster_by_footprint
    arcpy.management.BuildPyramidsandStatistics(str(output_path))
  File "C:\Program Files\ArcGIS\Pro\Resources\ArcPy\arcpy\management.py", line 19519, in BuildPyramidsandStatistics
    retval = convertArcObjectToPythonObject(gp.BuildPyramidsandStatistics_management(*gp_fixargs((in_workspace, include_subdirectories, build_pyramids, calculate_statistics, BUILD_ON_SOURCE, block_field, estimate_statistics, x_skip_factor, y_skip_factor, ignore_values, pyramid_level, SKIP_FIRST, resample_technique, compression_type, compression_quality, skip_existing, where_clause, sips_mode), True)))
  File "C:\Program Files\ArcGIS\Pro\Resources\ArcPy\arcpy\geoprocessing\_base.py", line 520, in <lambda>
    return lambda *args: val(*gp_fixargs(args, True))
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\pyarrow\__init__.py", line 65, in <module>
    import pyarrow.lib as _lib

AttributeError: _ARRAY_API not found

OK CL_MLP_PAO_IF_Ortho_26_05_15_Helipuerto-2 -> c:\Users\esrlrivero_adm\Documents\Geosupport\amsa-pao-geosupport\outputs\normalizacion_footprintV7\26_05\CL_MLP_PAO_IF_Ortho_26_05_15_Helipuerto-2.tif

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.2 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\ipykernel_launcher.py", line 17, in <module>
    app.launch_new_instance()
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\traitlets\config\application.py", line 982, in launch_instance
    app.start()
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\ipykernel\kernelapp.py", line 712, in start
    self.io_loop.start()
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\tornado\platform\asyncio.py", line 215, in start
    self.asyncio_loop.run_forever()
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\asyncio\base_events.py", line 601, in run_forever
    self._run_once()
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\asyncio\base_events.py", line 1905, in _run_once
    handle._run()
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\ipykernel\kernelbase.py", line 510, in dispatch_queue
    await self.process_one()
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\ipykernel\kernelbase.py", line 499, in process_one
    await dispatch(*args)
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\ipykernel\kernelbase.py", line 406, in dispatch_shell
    await result
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\ipykernel\kernelbase.py", line 730, in execute_request
    reply_content = await reply_content
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\ipykernel\ipkernel.py", line 383, in do_execute
    res = shell.run_cell(
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\ipykernel\zmqshell.py", line 528, in run_cell
    return super().run_cell(*args, **kwargs)
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\IPython\core\interactiveshell.py", line 2975, in run_cell
    result = self._run_cell(
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\IPython\core\interactiveshell.py", line 3030, in _run_cell
    return runner(coro)
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\IPython\core\async_helpers.py", line 78, in _pseudo_sync_runner
    coro.send(None)
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\IPython\core\interactiveshell.py", line 3257, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\IPython\core\interactiveshell.py", line 3473, in run_ast_nodes
    if (await self.run_code(code, result,  async_=asy)):
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\IPython\core\interactiveshell.py", line 3553, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "C:\Users\esrlrivero_adm\AppData\Local\Temp\ipykernel_22212\1835472039.py", line 237, in <cell line: 215>
    normalize_raster_by_footprint(source_path, raster_name, output_path, footprints_index)
  File "C:\Users\esrlrivero_adm\AppData\Local\Temp\ipykernel_22212\1835472039.py", line 182, in normalize_raster_by_footprint
    arcpy.management.BuildPyramidsandStatistics(str(output_path))
  File "C:\Program Files\ArcGIS\Pro\Resources\ArcPy\arcpy\management.py", line 19519, in BuildPyramidsandStatistics
    retval = convertArcObjectToPythonObject(gp.BuildPyramidsandStatistics_management(*gp_fixargs((in_workspace, include_subdirectories, build_pyramids, calculate_statistics, BUILD_ON_SOURCE, block_field, estimate_statistics, x_skip_factor, y_skip_factor, ignore_values, pyramid_level, SKIP_FIRST, resample_technique, compression_type, compression_quality, skip_existing, where_clause, sips_mode), True)))
  File "C:\Program Files\ArcGIS\Pro\Resources\ArcPy\arcpy\geoprocessing\_base.py", line 520, in <lambda>
    return lambda *args: val(*gp_fixargs(args, True))
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\pyarrow\__init__.py", line 65, in <module>
    import pyarrow.lib as _lib

AttributeError: _ARRAY_API not found

OK CL_MLP_PAO_IF_Ortho_26_05_15_EV1 -> c:\Users\esrlrivero_adm\Documents\Geosupport\amsa-pao-geosupport\outputs\normalizacion_footprintV7\26_05\CL_MLP_PAO_IF_Ortho_26_05_15_EV1.tif

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.2 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\ipykernel_launcher.py", line 17, in <module>
    app.launch_new_instance()
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\traitlets\config\application.py", line 982, in launch_instance
    app.start()
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\ipykernel\kernelapp.py", line 712, in start
    self.io_loop.start()
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\tornado\platform\asyncio.py", line 215, in start
    self.asyncio_loop.run_forever()
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\asyncio\base_events.py", line 601, in run_forever
    self._run_once()
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\asyncio\base_events.py", line 1905, in _run_once
    handle._run()
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\ipykernel\kernelbase.py", line 510, in dispatch_queue
    await self.process_one()
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\ipykernel\kernelbase.py", line 499, in process_one
    await dispatch(*args)
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\ipykernel\kernelbase.py", line 406, in dispatch_shell
    await result
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\ipykernel\kernelbase.py", line 730, in execute_request
    reply_content = await reply_content
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\ipykernel\ipkernel.py", line 383, in do_execute
    res = shell.run_cell(
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\ipykernel\zmqshell.py", line 528, in run_cell
    return super().run_cell(*args, **kwargs)
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\IPython\core\interactiveshell.py", line 2975, in run_cell
    result = self._run_cell(
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\IPython\core\interactiveshell.py", line 3030, in _run_cell
    return runner(coro)
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\IPython\core\async_helpers.py", line 78, in _pseudo_sync_runner
    coro.send(None)
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\IPython\core\interactiveshell.py", line 3257, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\IPython\core\interactiveshell.py", line 3473, in run_ast_nodes
    if (await self.run_code(code, result,  async_=asy)):
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\IPython\core\interactiveshell.py", line 3553, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "C:\Users\esrlrivero_adm\AppData\Local\Temp\ipykernel_22212\1835472039.py", line 237, in <cell line: 215>
    normalize_raster_by_footprint(source_path, raster_name, output_path, footprints_index)
  File "C:\Users\esrlrivero_adm\AppData\Local\Temp\ipykernel_22212\1835472039.py", line 182, in normalize_raster_by_footprint
    arcpy.management.BuildPyramidsandStatistics(str(output_path))
  File "C:\Program Files\ArcGIS\Pro\Resources\ArcPy\arcpy\management.py", line 19519, in BuildPyramidsandStatistics
    retval = convertArcObjectToPythonObject(gp.BuildPyramidsandStatistics_management(*gp_fixargs((in_workspace, include_subdirectories, build_pyramids, calculate_statistics, BUILD_ON_SOURCE, block_field, estimate_statistics, x_skip_factor, y_skip_factor, ignore_values, pyramid_level, SKIP_FIRST, resample_technique, compression_type, compression_quality, skip_existing, where_clause, sips_mode), True)))
  File "C:\Program Files\ArcGIS\Pro\Resources\ArcPy\arcpy\geoprocessing\_base.py", line 520, in <lambda>
    return lambda *args: val(*gp_fixargs(args, True))
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\pyarrow\__init__.py", line 65, in <module>
    import pyarrow.lib as _lib

AttributeError: _ARRAY_API not found

OK CL_MLP_PAO_IF_Ortho_26_05_15_Estacion_Cabecera -> c:\Users\esrlrivero_adm\Documents\Geosupport\amsa-pao-geosupport\outputs\normalizacion_footprintV7\26_05\CL_MLP_PAO_IF_Ortho_26_05_15_Estacion_Cabecera.tif

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.2 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\ipykernel_launcher.py", line 17, in <module>
    app.launch_new_instance()
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\traitlets\config\application.py", line 982, in launch_instance
    app.start()
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\ipykernel\kernelapp.py", line 712, in start
    self.io_loop.start()
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\tornado\platform\asyncio.py", line 215, in start
    self.asyncio_loop.run_forever()
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\asyncio\base_events.py", line 601, in run_forever
    self._run_once()
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\asyncio\base_events.py", line 1905, in _run_once
    handle._run()
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\ipykernel\kernelbase.py", line 510, in dispatch_queue
    await self.process_one()
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\ipykernel\kernelbase.py", line 499, in process_one
    await dispatch(*args)
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\ipykernel\kernelbase.py", line 406, in dispatch_shell
    await result
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\ipykernel\kernelbase.py", line 730, in execute_request
    reply_content = await reply_content
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\ipykernel\ipkernel.py", line 383, in do_execute
    res = shell.run_cell(
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\ipykernel\zmqshell.py", line 528, in run_cell
    return super().run_cell(*args, **kwargs)
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\IPython\core\interactiveshell.py", line 2975, in run_cell
    result = self._run_cell(
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\IPython\core\interactiveshell.py", line 3030, in _run_cell
    return runner(coro)
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\IPython\core\async_helpers.py", line 78, in _pseudo_sync_runner
    coro.send(None)
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\IPython\core\interactiveshell.py", line 3257, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\IPython\core\interactiveshell.py", line 3473, in run_ast_nodes
    if (await self.run_code(code, result,  async_=asy)):
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\IPython\core\interactiveshell.py", line 3553, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "C:\Users\esrlrivero_adm\AppData\Local\Temp\ipykernel_22212\1835472039.py", line 237, in <cell line: 215>
    normalize_raster_by_footprint(source_path, raster_name, output_path, footprints_index)
  File "C:\Users\esrlrivero_adm\AppData\Local\Temp\ipykernel_22212\1835472039.py", line 182, in normalize_raster_by_footprint
    arcpy.management.BuildPyramidsandStatistics(str(output_path))
  File "C:\Program Files\ArcGIS\Pro\Resources\ArcPy\arcpy\management.py", line 19519, in BuildPyramidsandStatistics
    retval = convertArcObjectToPythonObject(gp.BuildPyramidsandStatistics_management(*gp_fixargs((in_workspace, include_subdirectories, build_pyramids, calculate_statistics, BUILD_ON_SOURCE, block_field, estimate_statistics, x_skip_factor, y_skip_factor, ignore_values, pyramid_level, SKIP_FIRST, resample_technique, compression_type, compression_quality, skip_existing, where_clause, sips_mode), True)))
  File "C:\Program Files\ArcGIS\Pro\Resources\ArcPy\arcpy\geoprocessing\_base.py", line 520, in <lambda>
    return lambda *args: val(*gp_fixargs(args, True))
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\pyarrow\__init__.py", line 65, in <module>
    import pyarrow.lib as _lib

AttributeError: _ARRAY_API not found

OK CL_MLP_PAO_IF_Ortho_26_05_16_TORRES_E48_A_E84_PV4 -> c:\Users\esrlrivero_adm\Documents\Geosupport\amsa-pao-geosupport\outputs\normalizacion_footprintV7\26_05\CL_MLP_PAO_IF_Ortho_26_05_16_TORRES_E48_A_E84_PV4.tif

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.2 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\ipykernel_launcher.py", line 17, in <module>
    app.launch_new_instance()
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\traitlets\config\application.py", line 982, in launch_instance
    app.start()
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\ipykernel\kernelapp.py", line 712, in start
    self.io_loop.start()
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\tornado\platform\asyncio.py", line 215, in start
    self.asyncio_loop.run_forever()
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\asyncio\base_events.py", line 601, in run_forever
    self._run_once()
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\asyncio\base_events.py", line 1905, in _run_once
    handle._run()
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\ipykernel\kernelbase.py", line 510, in dispatch_queue
    await self.process_one()
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\ipykernel\kernelbase.py", line 499, in process_one
    await dispatch(*args)
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\ipykernel\kernelbase.py", line 406, in dispatch_shell
    await result
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\ipykernel\kernelbase.py", line 730, in execute_request
    reply_content = await reply_content
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\ipykernel\ipkernel.py", line 383, in do_execute
    res = shell.run_cell(
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\ipykernel\zmqshell.py", line 528, in run_cell
    return super().run_cell(*args, **kwargs)
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\IPython\core\interactiveshell.py", line 2975, in run_cell
    result = self._run_cell(
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\IPython\core\interactiveshell.py", line 3030, in _run_cell
    return runner(coro)
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\IPython\core\async_helpers.py", line 78, in _pseudo_sync_runner
    coro.send(None)
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\IPython\core\interactiveshell.py", line 3257, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\IPython\core\interactiveshell.py", line 3473, in run_ast_nodes
    if (await self.run_code(code, result,  async_=asy)):
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\IPython\core\interactiveshell.py", line 3553, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "C:\Users\esrlrivero_adm\AppData\Local\Temp\ipykernel_22212\1835472039.py", line 237, in <cell line: 215>
    normalize_raster_by_footprint(source_path, raster_name, output_path, footprints_index)
  File "C:\Users\esrlrivero_adm\AppData\Local\Temp\ipykernel_22212\1835472039.py", line 182, in normalize_raster_by_footprint
    arcpy.management.BuildPyramidsandStatistics(str(output_path))
  File "C:\Program Files\ArcGIS\Pro\Resources\ArcPy\arcpy\management.py", line 19519, in BuildPyramidsandStatistics
    retval = convertArcObjectToPythonObject(gp.BuildPyramidsandStatistics_management(*gp_fixargs((in_workspace, include_subdirectories, build_pyramids, calculate_statistics, BUILD_ON_SOURCE, block_field, estimate_statistics, x_skip_factor, y_skip_factor, ignore_values, pyramid_level, SKIP_FIRST, resample_technique, compression_type, compression_quality, skip_existing, where_clause, sips_mode), True)))
  File "C:\Program Files\ArcGIS\Pro\Resources\ArcPy\arcpy\geoprocessing\_base.py", line 520, in <lambda>
    return lambda *args: val(*gp_fixargs(args, True))
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\pyarrow\__init__.py", line 65, in <module>
    import pyarrow.lib as _lib

AttributeError: _ARRAY_API not found

OK CL_MLP_PAO_IF_Ortho_26_05_17_EV2 -> c:\Users\esrlrivero_adm\Documents\Geosupport\amsa-pao-geosupport\outputs\normalizacion_footprintV7\26_05\CL_MLP_PAO_IF_Ortho_26_05_17_EV2.tif

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.2 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\ipykernel_launcher.py", line 17, in <module>
    app.launch_new_instance()
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\traitlets\config\application.py", line 982, in launch_instance
    app.start()
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\ipykernel\kernelapp.py", line 712, in start
    self.io_loop.start()
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\tornado\platform\asyncio.py", line 215, in start
    self.asyncio_loop.run_forever()
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\asyncio\base_events.py", line 601, in run_forever
    self._run_once()
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\asyncio\base_events.py", line 1905, in _run_once
    handle._run()
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\ipykernel\kernelbase.py", line 510, in dispatch_queue
    await self.process_one()
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\ipykernel\kernelbase.py", line 499, in process_one
    await dispatch(*args)
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\ipykernel\kernelbase.py", line 406, in dispatch_shell
    await result
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\ipykernel\kernelbase.py", line 730, in execute_request
    reply_content = await reply_content
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\ipykernel\ipkernel.py", line 383, in do_execute
    res = shell.run_cell(
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\ipykernel\zmqshell.py", line 528, in run_cell
    return super().run_cell(*args, **kwargs)
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\IPython\core\interactiveshell.py", line 2975, in run_cell
    result = self._run_cell(
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\IPython\core\interactiveshell.py", line 3030, in _run_cell
    return runner(coro)
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\IPython\core\async_helpers.py", line 78, in _pseudo_sync_runner
    coro.send(None)
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\IPython\core\interactiveshell.py", line 3257, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\IPython\core\interactiveshell.py", line 3473, in run_ast_nodes
    if (await self.run_code(code, result,  async_=asy)):
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\IPython\core\interactiveshell.py", line 3553, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "C:\Users\esrlrivero_adm\AppData\Local\Temp\ipykernel_22212\1835472039.py", line 237, in <cell line: 215>
    normalize_raster_by_footprint(source_path, raster_name, output_path, footprints_index)
  File "C:\Users\esrlrivero_adm\AppData\Local\Temp\ipykernel_22212\1835472039.py", line 182, in normalize_raster_by_footprint
    arcpy.management.BuildPyramidsandStatistics(str(output_path))
  File "C:\Program Files\ArcGIS\Pro\Resources\ArcPy\arcpy\management.py", line 19519, in BuildPyramidsandStatistics
    retval = convertArcObjectToPythonObject(gp.BuildPyramidsandStatistics_management(*gp_fixargs((in_workspace, include_subdirectories, build_pyramids, calculate_statistics, BUILD_ON_SOURCE, block_field, estimate_statistics, x_skip_factor, y_skip_factor, ignore_values, pyramid_level, SKIP_FIRST, resample_technique, compression_type, compression_quality, skip_existing, where_clause, sips_mode), True)))
  File "C:\Program Files\ArcGIS\Pro\Resources\ArcPy\arcpy\geoprocessing\_base.py", line 520, in <lambda>
    return lambda *args: val(*gp_fixargs(args, True))
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\pyarrow\__init__.py", line 65, in <module>
    import pyarrow.lib as _lib

AttributeError: _ARRAY_API not found

OK CL_MLP_PAO_IF_Ortho_26_05_17_EDT -> c:\Users\esrlrivero_adm\Documents\Geosupport\amsa-pao-geosupport\outputs\normalizacion_footprintV7\26_05\CL_MLP_PAO_IF_Ortho_26_05_17_EDT.tif

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.2 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\ipykernel_launcher.py", line 17, in <module>
    app.launch_new_instance()
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\traitlets\config\application.py", line 982, in launch_instance
    app.start()
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\ipykernel\kernelapp.py", line 712, in start
    self.io_loop.start()
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\tornado\platform\asyncio.py", line 215, in start
    self.asyncio_loop.run_forever()
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\asyncio\base_events.py", line 601, in run_forever
    self._run_once()
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\asyncio\base_events.py", line 1905, in _run_once
    handle._run()
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\ipykernel\kernelbase.py", line 510, in dispatch_queue
    await self.process_one()
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\ipykernel\kernelbase.py", line 499, in process_one
    await dispatch(*args)
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\ipykernel\kernelbase.py", line 406, in dispatch_shell
    await result
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\ipykernel\kernelbase.py", line 730, in execute_request
    reply_content = await reply_content
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\ipykernel\ipkernel.py", line 383, in do_execute
    res = shell.run_cell(
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\ipykernel\zmqshell.py", line 528, in run_cell
    return super().run_cell(*args, **kwargs)
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\IPython\core\interactiveshell.py", line 2975, in run_cell
    result = self._run_cell(
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\IPython\core\interactiveshell.py", line 3030, in _run_cell
    return runner(coro)
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\IPython\core\async_helpers.py", line 78, in _pseudo_sync_runner
    coro.send(None)
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\IPython\core\interactiveshell.py", line 3257, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\IPython\core\interactiveshell.py", line 3473, in run_ast_nodes
    if (await self.run_code(code, result,  async_=asy)):
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\IPython\core\interactiveshell.py", line 3553, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "C:\Users\esrlrivero_adm\AppData\Local\Temp\ipykernel_22212\1835472039.py", line 237, in <cell line: 215>
    normalize_raster_by_footprint(source_path, raster_name, output_path, footprints_index)
  File "C:\Users\esrlrivero_adm\AppData\Local\Temp\ipykernel_22212\1835472039.py", line 182, in normalize_raster_by_footprint
    arcpy.management.BuildPyramidsandStatistics(str(output_path))
  File "C:\Program Files\ArcGIS\Pro\Resources\ArcPy\arcpy\management.py", line 19519, in BuildPyramidsandStatistics
    retval = convertArcObjectToPythonObject(gp.BuildPyramidsandStatistics_management(*gp_fixargs((in_workspace, include_subdirectories, build_pyramids, calculate_statistics, BUILD_ON_SOURCE, block_field, estimate_statistics, x_skip_factor, y_skip_factor, ignore_values, pyramid_level, SKIP_FIRST, resample_technique, compression_type, compression_quality, skip_existing, where_clause, sips_mode), True)))
  File "C:\Program Files\ArcGIS\Pro\Resources\ArcPy\arcpy\geoprocessing\_base.py", line 520, in <lambda>
    return lambda *args: val(*gp_fixargs(args, True))
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\pyarrow\__init__.py", line 65, in <module>
    import pyarrow.lib as _lib

AttributeError: _ARRAY_API not found

OK CL_MLP_PAO_IF_Ortho_26_05_14_TORRES_E31_A_E48_PV4-2 -> c:\Users\esrlrivero_adm\Documents\Geosupport\amsa-pao-geosupport\outputs\normalizacion_footprintV7\26_05\CL_MLP_PAO_IF_Ortho_26_05_14_TORRES_E31_A_E48_PV4-2.tif

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.2 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\ipykernel_launcher.py", line 17, in <module>
    app.launch_new_instance()
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\traitlets\config\application.py", line 982, in launch_instance
    app.start()
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\ipykernel\kernelapp.py", line 712, in start
    self.io_loop.start()
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\tornado\platform\asyncio.py", line 215, in start
    self.asyncio_loop.run_forever()
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\asyncio\base_events.py", line 601, in run_forever
    self._run_once()
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\asyncio\base_events.py", line 1905, in _run_once
    handle._run()
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\ipykernel\kernelbase.py", line 510, in dispatch_queue
    await self.process_one()
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\ipykernel\kernelbase.py", line 499, in process_one
    await dispatch(*args)
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\ipykernel\kernelbase.py", line 406, in dispatch_shell
    await result
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\ipykernel\kernelbase.py", line 730, in execute_request
    reply_content = await reply_content
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\ipykernel\ipkernel.py", line 383, in do_execute
    res = shell.run_cell(
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\ipykernel\zmqshell.py", line 528, in run_cell
    return super().run_cell(*args, **kwargs)
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\IPython\core\interactiveshell.py", line 2975, in run_cell
    result = self._run_cell(
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\IPython\core\interactiveshell.py", line 3030, in _run_cell
    return runner(coro)
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\IPython\core\async_helpers.py", line 78, in _pseudo_sync_runner
    coro.send(None)
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\IPython\core\interactiveshell.py", line 3257, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\IPython\core\interactiveshell.py", line 3473, in run_ast_nodes
    if (await self.run_code(code, result,  async_=asy)):
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\IPython\core\interactiveshell.py", line 3553, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "C:\Users\esrlrivero_adm\AppData\Local\Temp\ipykernel_22212\1835472039.py", line 237, in <cell line: 215>
    normalize_raster_by_footprint(source_path, raster_name, output_path, footprints_index)
  File "C:\Users\esrlrivero_adm\AppData\Local\Temp\ipykernel_22212\1835472039.py", line 182, in normalize_raster_by_footprint
    arcpy.management.BuildPyramidsandStatistics(str(output_path))
  File "C:\Program Files\ArcGIS\Pro\Resources\ArcPy\arcpy\management.py", line 19519, in BuildPyramidsandStatistics
    retval = convertArcObjectToPythonObject(gp.BuildPyramidsandStatistics_management(*gp_fixargs((in_workspace, include_subdirectories, build_pyramids, calculate_statistics, BUILD_ON_SOURCE, block_field, estimate_statistics, x_skip_factor, y_skip_factor, ignore_values, pyramid_level, SKIP_FIRST, resample_technique, compression_type, compression_quality, skip_existing, where_clause, sips_mode), True)))
  File "C:\Program Files\ArcGIS\Pro\Resources\ArcPy\arcpy\geoprocessing\_base.py", line 520, in <lambda>
    return lambda *args: val(*gp_fixargs(args, True))
  File "c:\Users\esrlrivero_adm\AppData\Local\ESRI\conda\envs\arcgispro\lib\site-packages\pyarrow\__init__.py", line 65, in <module>
    import pyarrow.lib as _lib

AttributeError: _ARRAY_API not found

OK CL_MLP_PAO_IF_Ortho_26_05_15_EM1 -> c:\Users\esrlrivero_adm\Documents\Geosupport\amsa-pao-geosupport\outputs\normalizacion_footprintV7\26_05\CL_MLP_PAO_IF_Ortho_26_05_15_EM1.tif
Resumen normalizacion: {'normalized_for_review': 30, 'error': 2}
CSV resultados: c:\Users\esrlrivero_adm\Documents\Geosupport\amsa-pao-geosupport\outputs\normalizacion_footprintV7\00_normalizacion_footprint_resultados.csv